//! btree — forge lab 02 (tablespace).
//!
//! The default index, built honestly: a B+tree over i64 keys. Records live
//! only in the leaves; internal nodes carry separators that route, not data;
//! every leaf sits at the same depth — and stays there through ascending,
//! descending, and zipf-skewed key orders. Lab 01 gave you the page; lab 03
//! will make this tree durable.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/tree.rs        (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The ops: insert (upsert) / get / scan / delete, plus len, height, and
//! validate — your own invariant checker, which the checks call. The hard
//! parts:
//!   * a leaf split promotes a COPY of the separator (it stays in the right
//!     leaf); an internal split pushes the middle separator UP (it stays in
//!     no child); only a root split grows the tree;
//!   * delete underflow borrows from a sibling before it merges; a
//!     one-child root shrinks;
//!   * a separator is a promise: keys[i] is the smallest key of the subtree
//!     to its right. Break it and lookups go silently wrong.

mod tree;

use kslab::{Check, Report};
use std::collections::BTreeMap;
use tree::{BTree, Node, NodeId, INTERNAL_MAX, INTERNAL_MIN, LEAF_MAX, LEAF_MIN};

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* ------------------------- harness toolbox -------------------------- */

/// Levels a packed tree needs at the pinned capacities: height 1 holds up to
/// LEAF_MAX records, and each level above multiplies capacity by the fanout.
/// At N = 2048 the ascending-insert split pattern lands exactly on this
/// bound (the reference solution agrees), so an extra level is a balance
/// bug, not bad luck.
fn expected_height(n: usize) -> usize {
    let mut h = 1;
    let mut cap = LEAF_MAX;
    while n > cap {
        cap *= INTERNAL_MAX + 1;
        h += 1;
    }
    h
}

/// The first divergence between a scan result and the model's, as a sentence.
fn scan_diff(got: &[(i64, i64)], want: &[(i64, i64)]) -> Option<String> {
    if got.len() != want.len() {
        return Some(format!("{} records returned, the model holds {}", got.len(), want.len()));
    }
    for (i, (g, w)) in got.iter().zip(want).enumerate() {
        if g != w {
            return Some(format!("record {i}: got {g:?}, want {w:?}"));
        }
    }
    None
}

/// Fetch a live node, or say which pointer dangled.
fn node(t: &BTree, id: NodeId) -> Result<&Node, String> {
    t.nodes
        .get(id as usize)
        .and_then(|slot| slot.as_ref())
        .ok_or_else(|| format!("node id {id} is a tombstone or out of the arena — a live pointer must name a live node"))
}

/// The harness's own invariant walk — independent of the student's
/// validate(). Err strings are written to teach: the node, the key, the law.
fn audit(t: &BTree) -> Result<(), String> {
    node(t, t.root)?;
    let mut leaf_depths = Vec::new();
    let mut records = 0usize;
    audit_node(t, t.root, 0, true, &mut leaf_depths, &mut records)?;
    let d0 = leaf_depths[0];
    if let Some(&d) = leaf_depths.iter().find(|&&d| d != d0) {
        return Err(format!("leaf at depth {d} found, others at {d0} — tree unbalanced"));
    }
    if t.height() != d0 + 1 {
        return Err(format!("height() = {} but the leaves sit {} levels deep", t.height(), d0 + 1));
    }
    if records != t.len {
        return Err(format!("len = {} but the leaves hold {records} records — the counter drifted from the data", t.len));
    }
    // the leaf chain, from the leftmost leaf, must carry every record ascending
    let mut id = t.root;
    loop {
        match node(t, id)? {
            Node::Leaf(_) => break,
            Node::Internal(n) => id = n.children[0],
        }
    }
    let mut chained = 0usize;
    let mut prev: Option<i64> = None;
    loop {
        let l = match node(t, id)? {
            Node::Leaf(l) => l,
            Node::Internal(_) => {
                return Err(format!("the next chain reaches internal node {id} — next links leaves only"));
            }
        };
        for &k in &l.keys {
            if let Some(p) = prev {
                if k <= p {
                    return Err(format!("leaf chain not ascending: {k} follows {p} — the chain is the scan's spine"));
                }
            }
            prev = Some(k);
            chained += 1;
        }
        match l.next {
            Some(nx) => id = nx,
            None => break,
        }
    }
    if chained != records {
        return Err(format!(
            "the next chain carries {chained} records but the tree holds {records} — a split or merge forgot to splice the chain"
        ));
    }
    Ok(())
}

/// Recursive half of audit: occupancy, ordering, separator truth. Returns
/// the subtree's (min, max) key; None only for an empty root leaf.
fn audit_node(
    t: &BTree,
    id: NodeId,
    depth: usize,
    is_root: bool,
    leaf_depths: &mut Vec<usize>,
    records: &mut usize,
) -> Result<Option<(i64, i64)>, String> {
    match node(t, id)? {
        Node::Leaf(l) => {
            if l.keys.len() != l.vals.len() {
                return Err(format!("leaf {id}: {} keys but {} values — the two arrays move as one", l.keys.len(), l.vals.len()));
            }
            if l.keys.len() > LEAF_MAX {
                return Err(format!("leaf {id} holds {} records, max is {LEAF_MAX} — an overflowing leaf must split", l.keys.len()));
            }
            if !is_root && l.keys.len() < LEAF_MIN {
                return Err(format!("leaf {id} holds {} records, min is {LEAF_MIN} — underflow must borrow or merge", l.keys.len()));
            }
            if !l.keys.windows(2).all(|w| w[0] < w[1]) {
                return Err(format!("leaf {id}: keys not strictly ascending"));
            }
            leaf_depths.push(depth);
            *records += l.keys.len();
            Ok(l.keys.first().map(|&f| (f, *l.keys.last().unwrap())))
        }
        Node::Internal(n) => {
            if n.children.len() != n.keys.len() + 1 {
                return Err(format!(
                    "internal {id}: {} separators but {} children — always exactly one more child",
                    n.keys.len(),
                    n.children.len()
                ));
            }
            if n.keys.len() > INTERNAL_MAX {
                return Err(format!("internal {id} holds {} separators, max is {INTERNAL_MAX} — an overflowing node must split", n.keys.len()));
            }
            if !is_root && n.keys.len() < INTERNAL_MIN {
                return Err(format!(
                    "internal {id} holds {} separators, min is {INTERNAL_MIN} — underflow must borrow or merge",
                    n.keys.len()
                ));
            }
            if is_root && n.keys.is_empty() {
                return Err("the root is internal with no separators — a one-child root must shrink".to_string());
            }
            if !n.keys.windows(2).all(|w| w[0] < w[1]) {
                return Err(format!("internal {id}: separators not strictly ascending"));
            }
            let mut lo = None;
            let mut hi = None;
            for (c, &child) in n.children.iter().enumerate() {
                let Some((cmin, cmax)) = audit_node(t, child, depth + 1, false, leaf_depths, records)? else {
                    return Err(format!("internal {id} points at an empty subtree — only the root leaf may be empty"));
                };
                if let Some(p) = hi {
                    if cmin <= p {
                        return Err(format!("internal {id}: child {child} starts at {cmin} but the previous child reaches {p} — subtrees overlap"));
                    }
                }
                if c == 0 {
                    lo = Some(cmin);
                } else if n.keys[c - 1] != cmin {
                    return Err(format!(
                        "internal {id}: separator {} = {} but the subtree to its right starts at {cmin} — a separator is a copy of its right subtree's smallest key",
                        c - 1,
                        n.keys[c - 1]
                    ));
                }
                hi = Some(cmax);
            }
            Ok(Some((lo.unwrap(), hi.unwrap())))
        }
    }
}

/// Whole-tree equivalence against the model: the tree's own validate(), the
/// harness audit, the full scan, and every point lookup. Returns the failure
/// sentence, if any.
fn tree_vs_model(t: &BTree, model: &BTreeMap<i64, i64>, ctx: &str) -> Option<String> {
    if t.len() != model.len() {
        return Some(format!("{ctx}: len() = {} but the model holds {} keys", t.len(), model.len()));
    }
    if let Err(e) = t.validate() {
        return Some(format!("{ctx}: your validate() rejected the tree: {e}"));
    }
    if let Err(e) = audit(t) {
        return Some(format!("{ctx}: {e}"));
    }
    let want: Vec<(i64, i64)> = model.iter().map(|(&k, &v)| (k, v)).collect();
    if let Some(d) = scan_diff(&t.scan(i64::MIN, i64::MAX), &want) {
        return Some(format!("{ctx}: full scan diverges — {d}"));
    }
    for (&k, &v) in model {
        if t.get(k) != Some(v) {
            return Some(format!("{ctx}: get({k}) = {:?} but the model has {k} → {v}", t.get(k)));
        }
    }
    None
}

/* ------------------------------ checks ------------------------------ */

/// 1. lookup_correct: a hand-written edge set plus a few hundred seeded
///    upserts; every key returns its LATEST value, and a spread of
///    never-written keys — inside and outside the inserted band — returns
///    None.
pub fn check_lookup_correct() -> Check {
    const ID: &str = "lookup_correct";
    const LABEL: &str = "every inserted key found; absent keys absent";
    let mut t = BTree::new();
    if t.get(0).is_some() {
        return Check::fail(ID, LABEL, "get on an empty tree must be None");
    }
    if t.len() != 0 || t.height() != 1 {
        return Check::fail(
            ID,
            LABEL,
            format!("a fresh tree has len {} height {}, want 0 and 1 — one empty root leaf", t.len(), t.height()),
        );
    }
    let mut model: BTreeMap<i64, i64> = BTreeMap::new();
    let mut rng = Rng(0xB7EE_0001);
    let mut ops = 0usize;
    for &(k, v) in &[(i64::MIN, -1i64), (-1, -2), (0, 0), (1, 2), (i64::MAX, 1)] {
        t.insert(k, v);
        model.insert(k, v);
        ops += 1;
    }
    for _ in 0..400 {
        let k = rng.below(300) as i64 - 150; // [-150, 150): collisions force upserts
        let v = rng.next() as i64;
        t.insert(k, v);
        model.insert(k, v);
        ops += 1;
    }
    if t.len() != model.len() {
        return Check::fail(
            ID,
            LABEL,
            format!("after {ops} inserts, len() = {} but only {} keys are distinct — an upsert is not an insert", t.len(), model.len()),
        );
    }
    for (&k, &v) in &model {
        match t.get(k) {
            Some(got) if got == v => {}
            Some(got) => return Check::fail(ID, LABEL, format!("get({k}) = {got} but the latest write was {v} — upserts must overwrite")),
            None => return Check::fail(ID, LABEL, format!("get({k}) = None but the model has {k} → {v} — an inserted key went missing")),
        }
    }
    // never written: the gaps inside the band, and the far outside
    for k in (-150i64..150).filter(|k| !model.contains_key(k)) {
        if let Some(got) = t.get(k) {
            return Check::fail(ID, LABEL, format!("get({k}) = Some({got}) but {k} was never written — phantoms are corruption"));
        }
    }
    for k in [-1000i64, -500, 500, 1000, i64::MIN + 1, i64::MAX - 1] {
        if let Some(got) = t.get(k) {
            return Check::fail(ID, LABEL, format!("get({k}) = Some({got}) but {k} was never written"));
        }
    }
    Check::pass(ID, LABEL, format!("{} distinct keys through {ops} ops: latest values exact, absent keys absent", model.len()))
}

/// 2. ordered_scans: the full scan equals the sorted model snapshot, and a
///    dozen seeded ranges match the model's filtered output exactly —
///    including point ranges and backwards (empty) ones.
pub fn check_ordered_scans() -> Check {
    const ID: &str = "ordered_scans";
    const LABEL: &str = "full and range scans come back sorted";
    let empty = BTree::new();
    if !empty.scan(i64::MIN, i64::MAX).is_empty() || !empty.scan(10, 4).is_empty() {
        return Check::fail(ID, LABEL, "an empty tree scans empty — and lo > hi must be empty, never a panic");
    }
    let mut t = BTree::new();
    let mut model: BTreeMap<i64, i64> = BTreeMap::new();
    let mut rng = Rng(0xB7EE_0002);
    for &(k, v) in &[(i64::MIN, 11i64), (i64::MAX, 12), (0, 13)] {
        t.insert(k, v);
        model.insert(k, v);
    }
    for _ in 0..600 {
        let k = rng.below(4000) as i64 - 2000;
        let v = rng.next() as i64;
        t.insert(k, v);
        model.insert(k, v);
    }
    let want: Vec<(i64, i64)> = model.iter().map(|(&k, &v)| (k, v)).collect();
    if let Some(d) = scan_diff(&t.scan(i64::MIN, i64::MAX), &want) {
        return Check::fail(ID, LABEL, format!("full scan diverges — {d} — a scan returns every record, ascending, no gaps"));
    }
    for r in 0..12 {
        let lo = rng.below(4400) as i64 - 2200;
        let hi = lo + rng.below(900) as i64;
        let want: Vec<(i64, i64)> = model.range(lo..=hi).map(|(&k, &v)| (k, v)).collect();
        if let Some(d) = scan_diff(&t.scan(lo, hi), &want) {
            return Check::fail(ID, LABEL, format!("range #{r} [{lo}, {hi}]: {d} — both ends are inclusive"));
        }
    }
    // a point range hits exactly the one key; backwards ranges are empty
    let k = *model.keys().nth(model.len() / 2).unwrap();
    if t.scan(k, k) != vec![(k, model[&k])] {
        return Check::fail(ID, LABEL, format!("scan({k}, {k}) must return exactly the record at {k} — inclusive means inclusive"));
    }
    if !t.scan(4, -4).is_empty() || !t.scan(i64::MAX, i64::MIN).is_empty() {
        return Check::fail(ID, LABEL, "lo > hi scans empty — an inverted range is a caller's bug, not yours to panic on");
    }
    Check::pass(ID, LABEL, format!("full scan + 12 ranges + point and inverted ranges all match the model ({} keys)", model.len()))
}

/// 3. split_balance: 2048 ascending keys — the auto-increment primary key
///    that haunts production — force exactly three levels at these
///    capacities. The tree's own validate() must agree with the harness's
///    independent walk: one leaf depth, every non-root node at least half
///    full, separators truthful.
pub fn check_split_balance() -> Check {
    const ID: &str = "split_balance";
    const LABEL: &str = "minimum occupancy holds after splits";
    const N: usize = 2048;
    let mut t = BTree::new();
    for k in 0..N as i64 {
        t.insert(k, k * 3);
    }
    if t.len() != N {
        return Check::fail(ID, LABEL, format!("after {N} distinct inserts, len() = {} — splits are losing records", t.len()));
    }
    let want_h = expected_height(N);
    if t.height() != want_h {
        return Check::fail(
            ID,
            LABEL,
            format!(
                "after {N} ascending inserts, height() = {}, want {want_h} — leaves of {LEAF_MAX} and fanout {} pack {N} keys into exactly {want_h} levels; only a root split may add one",
                t.height(),
                INTERNAL_MAX + 1
            ),
        );
    }
    if let Err(e) = audit(&t) {
        return Check::fail(ID, LABEL, e);
    }
    if let Err(e) = t.validate() {
        return Check::fail(ID, LABEL, format!("your validate() rejected a correct tree: {e}"));
    }
    Check::pass(
        ID,
        LABEL,
        format!(
            "{N} ascending keys: height {want_h}, every leaf at depth {}, every non-root node at least half full — and your validate() agrees",
            want_h - 1
        ),
    )
}

/// 4. adversarial_orders: three fresh trees, three nasty workloads —
///    (a) 2000 descending inserts (leftmost-path splits forever, a new tree
///        minimum on every insert),
///    (b) zipf-skewed writes into a tiny hot range (upsert storms),
///    (c) the same 50 keys written 40 times (last write wins, len == 50).
///    Each tree must validate and match the reference model exactly.
pub fn check_adversarial_orders() -> Check {
    const ID: &str = "adversarial_orders";
    const LABEL: &str = "descending / zipf / dup-heavy key orders";

    // (a) descending: every split happens on the leftmost path
    let mut t = BTree::new();
    let mut model: BTreeMap<i64, i64> = BTreeMap::new();
    for k in (0..2000i64).rev() {
        t.insert(k, -k);
        model.insert(k, -k);
    }
    if let Some(m) = tree_vs_model(&t, &model, "descending 2000") {
        return Check::fail(ID, LABEL, m);
    }

    // (b) zipf: quadratic skew keeps most writes in a tiny hot range —
    //     collisions and upserts, few structural changes
    let mut t = BTree::new();
    let mut model: BTreeMap<i64, i64> = BTreeMap::new();
    let mut rng = Rng(0xB7EE_000B);
    for _ in 0..1500 {
        let x = rng.below(256);
        let k = ((x * x) / 256) as i64; // hot near 0, cold tail out to 255
        let v = rng.next() as i64;
        t.insert(k, v);
        model.insert(k, v);
    }
    if let Some(m) = tree_vs_model(&t, &model, "zipf hot-range") {
        return Check::fail(ID, LABEL, m);
    }

    // (c) dup-heavy: the same 50 keys, 40 rounds of different values —
    //     final values must be the LAST writes, and len must stay 50
    let mut t = BTree::new();
    let mut model: BTreeMap<i64, i64> = BTreeMap::new();
    let mut rng = Rng(0xB7EE_000C);
    for _ in 0..40 {
        for i in 0..50i64 {
            let k = 3 + i * 7;
            let v = rng.next() as i64;
            t.insert(k, v);
            model.insert(k, v);
        }
    }
    if t.len() != 50 {
        return Check::fail(ID, LABEL, format!("dup-heavy: len() = {} after 2000 writes to the same 50 keys — upserts are not inserts", t.len()));
    }
    if let Some(m) = tree_vs_model(&t, &model, "dup-heavy 40×50") {
        return Check::fail(ID, LABEL, m);
    }

    Check::pass(ID, LABEL, "descending 2000, zipf hot-range 1500, dup-heavy 40×50 — every tree model-exact and provably balanced")
}

/// 5. storm: 3000 seeded ops — insert ~55%, delete ~30% (of live and absent
///    keys), point lookups ~15% asserted inline — then the reckoning: full
///    scan equality, the harness's invariant walk, and the tree's own
///    validate().
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "3000 mixed ops vs a reference model";
    let mut t = BTree::new();
    let mut model: BTreeMap<i64, i64> = BTreeMap::new();
    let mut rng = Rng(0xB7EE);
    for i in 0..3000usize {
        match rng.below(100) {
            0..=54 => {
                let k = rng.below(1500) as i64;
                let v = rng.next() as i64;
                t.insert(k, v);
                model.insert(k, v);
            }
            55..=84 => {
                let k = if !model.is_empty() && rng.below(2) == 0 {
                    *model.keys().nth(rng.below(model.len())).unwrap() // a live key
                } else {
                    rng.below(1500) as i64 // maybe live, maybe not
                };
                let was = model.remove(&k).is_some();
                if t.delete(k) != was {
                    return Check::fail(ID, LABEL, if was {
                        format!("op {i}: delete({k}) = false but the key is live — a lost delete corrupts len and scans")
                    } else {
                        format!("op {i}: delete({k}) = true but the key is not live — delete says true only when it removed a record")
                    });
                }
            }
            _ => {
                let k = rng.below(1500) as i64;
                match (t.get(k), model.get(&k)) {
                    (got, want) if got == want.copied() => {}
                    (got, Some(&v)) => return Check::fail(ID, LABEL, format!("op {i}: get({k}) = {got:?} but the model has {k} → {v}")),
                    (got, None) => return Check::fail(ID, LABEL, format!("op {i}: get({k}) = {got:?} but the key is not live")),
                }
            }
        }
        if i % 300 == 0 {
            if let Err(e) = t.validate() {
                return Check::fail(ID, LABEL, format!("op {i}: your validate() rejected the tree mid-storm: {e}"));
            }
            if let Err(e) = audit(&t) {
                return Check::fail(ID, LABEL, format!("op {i}: {e}"));
            }
        }
    }
    if let Some(m) = tree_vs_model(&t, &model, "after the storm") {
        return Check::fail(ID, LABEL, m);
    }
    Check::pass(ID, LABEL, format!("3000 ops model-exact; {} keys survive, balanced and self-validated", model.len()))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_lookup_correct(),
        check_ordered_scans(),
        check_split_balance(),
        check_adversarial_orders(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "btree", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
