//! rust-kv — forge lab 00 (tablespace). The warmup.
//!
//! This lab teaches the LOOP before the concepts bite. The template you
//! unzipped does not compile — five deliberate errors in src/kv.rs, each one
//! a Rust move the rest of the course assumes. Fixing them, with the
//! compiler's messages as the tutor, IS the first half of the lab. The
//! second half is two methods: cas (compare-and-set) and scan_prefix.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/kv.rs          (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The checks, in grading order: basics grades the get/put/delete your
//! compile fixes just finished; cas_semantics grades the one-decision write
//! (apply iff current == expected, with None claiming "the key is absent");
//! storm runs 500 seeded ops — puts, deletes, gets, cas, prefix scans —
//! against a reference BTreeMap model and your store must match it exactly.

mod kv;

use kslab::{Check, Report};
use kv::Kv;
use std::collections::BTreeMap;

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* ------------------------------ checks ------------------------------ */

/// 1. basics: the ops the compile fixes just finished. Absence reads as
///    None, put hands back the previous value, delete reports whether the
///    key existed — and a deleted key stays gone without disturbing its
///    neighbors.
pub fn check_basics() -> Check {
    const ID: &str = "basics";
    const LABEL: &str = "get/put/delete round-trip after the compile fixes";
    let mut kv = Kv::new();
    if kv.get("ghost").is_some() {
        return Check::fail(ID, LABEL, "a fresh store holds nothing: get on any key must be None");
    }
    if kv.delete("ghost") {
        return Check::fail(ID, LABEL, "deleting a key that was never there must be false — nothing was evicted");
    }
    if let Some(old) = kv.put("alpha", "1") {
        return Check::fail(ID, LABEL, format!("first put of \"alpha\" returned Some({old:?}) — a brand-new key has no previous value to report"));
    }
    if kv.get("alpha").as_deref() != Some("1") {
        return Check::fail(ID, LABEL, format!("put(\"alpha\", \"1\") then get must read Some(\"1\"), got {:?}", kv.get("alpha")));
    }
    match kv.put("alpha", "2") {
        Some(old) if old == "1" => {}
        other => return Check::fail(ID, LABEL, format!("an overwrite must hand back the value it evicted: expected Some(\"1\"), got {other:?}")),
    }
    let _ = kv.put("beta", "b");
    let _ = kv.put("gamma", "g");
    if !kv.delete("alpha") {
        return Check::fail(ID, LABEL, "delete of a live key returned false — the eviction did not happen");
    }
    if kv.get("alpha").is_some() {
        return Check::fail(ID, LABEL, "a deleted key must read None — eviction is a remove, not a hide");
    }
    if kv.delete("alpha") {
        return Check::fail(ID, LABEL, "the second delete of the same key must be false — you cannot evict an absence");
    }
    if kv.get("beta").as_deref() != Some("b") || kv.get("gamma").as_deref() != Some("g") {
        return Check::fail(ID, LABEL, "deleting \"alpha\" disturbed its neighbors — each key owns its own entry");
    }
    Check::pass(ID, LABEL, "put overwrites and reports the evicted value; delete evicts exactly once; absence always reads None")
}

/// 2. cas_semantics: compare-and-set applies iff the key's current value
///    equals `expected`, where None claims the key is absent. Every
///    combination, in both directions — and a refused cas changes nothing.
pub fn check_cas_semantics() -> Check {
    const ID: &str = "cas_semantics";
    const LABEL: &str = "cas applies iff current == expected (None = absent)";
    let mut kv = Kv::new();
    // create-if-missing: None matches absence, so the write applies
    if !kv.cas("k", None, "v1") {
        return Check::fail(ID, LABEL, "cas(k, None, ..) on an absent key must APPLY — expected None claims \"the key is absent\", and it is");
    }
    if kv.get("k").as_deref() != Some("v1") {
        return Check::fail(ID, LABEL, "an applied cas must be readable immediately");
    }
    // absent key, but the caller expected a value: refuse, create nothing
    if kv.cas("never-seen", Some("anything"), "x") {
        return Check::fail(ID, LABEL, "cas on an absent key with expected Some(..) must REFUSE — the precondition \"current == expected\" is false");
    }
    if kv.get("never-seen").is_some() {
        return Check::fail(ID, LABEL, "a refused cas must change nothing — yet the key exists now");
    }
    // stale expectation on a live key: refuse, and change nothing
    if kv.cas("k", Some("v0"), "v2") {
        return Check::fail(ID, LABEL, "the live value is \"v1\"; expecting \"v0\" is a stale read — cas must refuse");
    }
    if kv.get("k").as_deref() != Some("v1") {
        return Check::fail(ID, LABEL, "a refused cas must change nothing — the live value moved anyway");
    }
    // the key is live, so a claim of absence is false: refuse
    if kv.cas("k", None, "v2") {
        return Check::fail(ID, LABEL, "expected None claims \"k\" is absent — it holds \"v1\"; cas must refuse");
    }
    // the expectation is the truth: apply
    if !kv.cas("k", Some("v1"), "v2") {
        return Check::fail(ID, LABEL, "expected == current (\"v1\") — the write must apply");
    }
    if kv.get("k").as_deref() != Some("v2") {
        return Check::fail(ID, LABEL, "an applied cas must install the new value");
    }
    // delete, cas-style: a guarded tombstone write. Lab 03's log-structured
    // deletes are exactly this — a marker with a precondition, not an erase.
    if !kv.cas("k", Some("v2"), "") {
        return Check::fail(ID, LABEL, "cas to \"\" guarded by the live value must apply — a tombstone is a write like any other");
    }
    if kv.get("k").as_deref() != Some("") {
        return Check::fail(ID, LABEL, "the tombstone write landed but reads back wrong");
    }
    Check::pass(ID, LABEL, "create-if-missing applies; stale reads and false absence claims refuse cleanly; a guarded tombstone stands in for delete")
}

/// 3. storm: 500 seeded ops — put, delete, get, cas, prefix scans — against
///    a reference BTreeMap model. Every return value must match, and a
///    final full scan settles anything the spot checks missed.
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "500 ops vs a reference model";
    let mut kv = Kv::new();
    let mut model: BTreeMap<String, String> = BTreeMap::new();
    let mut rng = Rng(0x5EED);
    // a small key universe on purpose: collisions, overwrites, and shared
    // prefixes are what make cas and scans interesting
    let prefixes = ["user:", "sess:", "cfg:", "tmp:"];
    for i in 0..500usize {
        let key = format!("{}{:02}", prefixes[rng.below(prefixes.len())], rng.below(24));
        match rng.below(100) {
            0..=34 => {
                let val = format!("v{:03}", rng.below(1000));
                let want = model.insert(key.clone(), val.clone());
                let got = kv.put(&key, &val);
                if got != want {
                    return Check::fail(ID, LABEL, format!("op {i}: put({key:?}, {val:?}) returned {got:?}; the model's previous value is {want:?}"));
                }
            }
            35..=54 => {
                let want = model.remove(&key).is_some();
                if kv.delete(&key) != want {
                    return Check::fail(ID, LABEL, format!("op {i}: delete({key:?}) disagrees with the model — the key {} live", if want { "was" } else { "was not" }));
                }
            }
            55..=74 => {
                let (got, want) = (kv.get(&key), model.get(&key).cloned());
                if got != want {
                    return Check::fail(ID, LABEL, format!("op {i}: get({key:?}) = {got:?}, the model says {want:?}"));
                }
            }
            75..=89 => {
                // half the time expect the truth, half a stale guess — both
                // directions of the contract get exercised, on live and
                // absent keys alike
                let expected = if rng.below(2) == 0 {
                    model.get(&key).cloned()
                } else {
                    Some(format!("stale-{}", rng.below(8)))
                };
                let new = format!("c{:03}", rng.below(1000));
                let applies = model.get(&key).map(String::as_str) == expected.as_deref();
                let got = kv.cas(&key, expected.as_deref(), &new);
                if got != applies {
                    return Check::fail(ID, LABEL, format!("op {i}: cas({key:?}, {expected:?}, {new:?}) returned {got}; the model says the precondition is {applies}"));
                }
                if applies {
                    model.insert(key.clone(), new);
                }
                let (got, want) = (kv.get(&key), model.get(&key).cloned());
                if got != want {
                    return Check::fail(ID, LABEL, format!("op {i}: after cas, get({key:?}) = {got:?}, the model says {want:?} — a refused cas must change nothing, an applied one must stick"));
                }
            }
            _ => {
                // scans: a real prefix, a partial one ("u" reaches user:*),
                // and the empty prefix — the whole store, sorted
                let prefix = match rng.below(10) {
                    0 => String::new(),
                    1 => "u".to_string(),
                    _ => prefixes[rng.below(prefixes.len())].to_string(),
                };
                let want: Vec<(String, String)> = model
                    .range(prefix.clone()..)
                    .take_while(|(k, _)| k.starts_with(&prefix))
                    .map(|(k, v)| (k.clone(), v.clone()))
                    .collect();
                let got = kv.scan_prefix(&prefix);
                if got != want {
                    return Check::fail(ID, LABEL, format!("op {i}: scan_prefix({prefix:?}) returned {} pairs, the model has {} — scans must come back sorted, complete, and prefix-true", got.len(), want.len()));
                }
            }
        }
        if i % 50 == 0 {
            for (k, v) in &model {
                if kv.get(k).as_deref() != Some(v.as_str()) {
                    return Check::fail(ID, LABEL, format!("op {i}: key {k:?} drifted from the model mid-storm"));
                }
            }
        }
    }
    let full = kv.scan_prefix("");
    let want: Vec<(String, String)> = model.iter().map(|(k, v)| (k.clone(), v.clone())).collect();
    if full != want {
        return Check::fail(ID, LABEL, format!("after the storm: a full scan returns {} pairs, the model holds {} — something leaked or vanished", full.len(), want.len()));
    }
    Check::pass(ID, LABEL, format!("500 ops model-exact; the final full scan matches key for key ({} live keys)", want.len()))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_basics(),
        check_cas_semantics(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "rust-kv", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
