//! volcano — forge lab 05 (tablespace).
//!
//! Pull, don't push. Labs 01–04 built the page, the tree, the log, and
//! the many-worlds store; this lab gives the store a query language: the
//! volcano model, where every operator is an open/next/close iterator
//! and executing a query means pulling next() at the root. Lab 06 will
//! hand this executor a new kind of index to choose.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/executor.rs    (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The dataset is seeded and fixed: `users` (200 rows, skewed cities)
//! and `orders` (1000 rows, zipf-ish amounts, a few NULL statuses). The
//! checks build operator trees from YOUR operators and pull them to
//! exhaustion, comparing every row against the reference executor below
//! — straight-line correct code that never touches your operators. The
//! hard parts:
//!   * iterator discipline: open() restarts a pass, next() past the end
//!     stays None, close() leaves the operator re-openable — and a
//!     nested-loop join re-opens its right child once per LEFT row;
//!   * SQL is three-valued: WHERE status = 'paid' matches nothing NULL,
//!     but GROUP BY status herds all the NULLs into ONE group — the two
//!     rules differ, and both are graded;
//!   * multiplicity: a user with k orders contributes k rows to a join;
//!     a user with none contributes zero (inner join).

mod executor;
mod storage;

use executor::{
    Agg, Filter, HashAggregate, IndexScan, NestedLoopJoin, Operator, Pred, Project, Row, SeqScan,
    Value,
};
use kslab::{Check, Report};
use std::collections::BTreeMap;
use storage::Table;

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* ------------------- the given storage layer ------------------------ */

mod storage {
    //! Your storage layer from labs 01–02, inlined and cleaned for this
    //! lab. You built these pieces already; the executor you write in
    //! executor.rs runs ON TOP of them, and you do not rebuild them here.
    //!
    //! Rows live in slotted pages: 8192 bytes, an 8-byte header, 6-byte
    //! slots, records growing up from the end — the layout you proved
    //! byte-exact in lab 01. A RowId is (page no, slot id): exactly what
    //! Page::insert handed you there, namespaced by page. The page BYTES
    //! are elided (this lab grades operators, not layouts) but the
    //! packing in `pack` below is real lab-01 accounting.
    //!
    //! Each table carries named secondary indexes:
    //! BTreeMap<i64, Vec<RowId>> — your lab-02 tree, standing behind one
    //! map per indexed column. An index scan is a point lookup in the
    //! tree followed by one rowid fetch per hit.

    use crate::executor::{Row, Value};
    use crate::Rng;
    use std::collections::BTreeMap;
    use std::rc::Rc;

    /// (page no, slot id) — lab 01's slot id, namespaced by page.
    pub type RowId = (u32, u16);

    /// One table: rows in physical order plus named secondary indexes.
    /// Cheap to clone — the data is shared (a refcount bump), never
    /// copied.
    #[derive(Clone)]
    pub struct Table {
        pub name: &'static str,
        #[allow(dead_code)] // documentation for the student; the harness knows the layout
        pub schema: &'static [&'static str],
        rows: Rc<Vec<Row>>,
        by_rid: Rc<BTreeMap<RowId, usize>>,
        indexes: Rc<BTreeMap<&'static str, BTreeMap<i64, Vec<RowId>>>>,
    }

    impl Table {
        /// Every row, in physical (insertion) order — a full scan's stream.
        pub fn rows(&self) -> &[Row] {
            &self.rows
        }
        /// Point-fetch by rowid — what an index scan does with each hit.
        #[allow(dead_code)] // your IndexScan uses this; the harness goes through rows()
        pub fn get(&self, rid: RowId) -> &Row {
            match self.by_rid.get(&rid) {
                Some(&i) => &self.rows[i],
                None => panic!("{}: get({rid:?}) — no such rowid", self.name),
            }
        }
        /// The named secondary index: key → the rowids carrying it, in
        /// insertion order.
        #[allow(dead_code)] // your IndexScan uses this; the harness goes through rows()
        pub fn index(&self, name: &str) -> &BTreeMap<i64, Vec<RowId>> {
            match self.indexes.get(name) {
                Some(ix) => ix,
                None => panic!("{}: no index named '{name}'", self.name),
            }
        }
    }

    pub struct Database {
        users: Table,
        orders: Table,
    }

    impl Database {
        pub fn table(&self, name: &str) -> Table {
            match name {
                "users" => self.users.clone(),
                "orders" => self.orders.clone(),
                _ => panic!("no table named '{name}' (this lab has users and orders)"),
            }
        }
    }

    /// The encoded size of a row — the harness's own estimate, used only
    /// for packing pages at seed time: a tag byte per value, 8 bytes per
    /// Int, 2 + len per Text, nothing per Null.
    fn encoded_len(row: &Row) -> usize {
        row.iter()
            .map(|v| {
                1 + match v {
                    Value::Int(_) => 8,
                    Value::Text(s) => 2 + s.len(),
                    Value::Null => 0,
                }
            })
            .sum()
    }

    /// Pack rows into 8192-byte pages by lab-01 accounting: 8-byte
    /// header, 6-byte slot per record, records growing up from the end.
    /// Returns each row's RowId, in row order.
    fn pack(rows: &[Row]) -> Vec<RowId> {
        const BODY: usize = 8192 - 8;
        let mut rids = Vec::with_capacity(rows.len());
        let (mut page, mut slot, mut free) = (0u32, 0u16, BODY);
        for row in rows {
            let need = encoded_len(row) + 6; // record bytes + its slot
            if free < need {
                page += 1;
                slot = 0;
                free = BODY;
            }
            free -= need;
            rids.push((page, slot));
            slot += 1;
        }
        rids
    }

    fn table(
        name: &'static str,
        schema: &'static [&'static str],
        rows: Vec<Row>,
        indexes: &[(&'static str, usize)],
    ) -> Table {
        let rids = pack(&rows);
        let by_rid: BTreeMap<RowId, usize> = rids.iter().cloned().zip(0..).collect();
        let mut ixs: BTreeMap<&'static str, BTreeMap<i64, Vec<RowId>>> = BTreeMap::new();
        for &(ix_name, col) in indexes {
            let mut m: BTreeMap<i64, Vec<RowId>> = BTreeMap::new();
            for (i, row) in rows.iter().enumerate() {
                if let Value::Int(k) = row[col] {
                    m.entry(k).or_default().push(rids[i]);
                }
            }
            ixs.insert(ix_name, m);
        }
        Table {
            name,
            schema,
            rows: Rc::new(rows),
            by_rid: Rc::new(by_rid),
            indexes: Rc::new(ixs),
        }
    }

    /// The fixed dataset, reseeded identically on every call — the same
    /// rows in the terminal and in the browser.
    pub fn seed() -> Database {
        let mut rng = Rng(0x5EED_0005);

        // users: 200 rows. Cities skew toward Berlin; ages toward the
        // young, with a real retiree tail (the suite groups age >= 60).
        let cities = ["Berlin", "Lisbon", "Osaka", "Nairobi", "Quito"];
        let mut users = Vec::new();
        for i in 1..=200i64 {
            let age = match rng.below(100) {
                0..=39 => 18 + rng.below(10),  // 18..=27
                40..=74 => 28 + rng.below(17), // 28..=44
                75..=91 => 45 + rng.below(20), // 45..=64
                _ => 65 + rng.below(20),       // 65..=84
            };
            let city = cities[match rng.below(100) {
                0..=39 => 0,
                40..=64 => 1,
                65..=79 => 2,
                80..=91 => 3,
                _ => 4,
            }];
            users.push(vec![
                Value::Int(i),
                Value::Text(format!("user{i:03}")),
                Value::Int(age as i64),
                Value::Text(city.to_string()),
            ]);
        }

        // orders: 1000 rows. Ten whale users (~20% of all orders), nobody
        // above user 190 orders at all (inner-join bait: users with zero
        // orders must not appear). Amounts zipf-ish small; ~3% of
        // statuses are NULL — SQL's three-valued logic made real.
        let mut orders = Vec::new();
        for i in 1..=1000i64 {
            let uid = if rng.below(100) < 20 { 1 + rng.below(10) } else { 11 + rng.below(180) };
            let amount = match rng.below(100) {
                0..=69 => 5 + rng.below(46),    // 5..=50
                70..=94 => 50 + rng.below(251), // 50..=300
                _ => 300 + rng.below(1701),     // 300..=2000
            };
            let status = match rng.below(100) {
                0..=54 => Value::Text("paid".to_string()),
                55..=79 => Value::Text("shipped".to_string()),
                80..=96 => Value::Text("pending".to_string()),
                _ => Value::Null,
            };
            orders.push(vec![
                Value::Int(i),
                Value::Int(uid as i64),
                Value::Int(amount as i64),
                status,
            ]);
        }

        Database {
            users: table("users", &["id", "name", "age", "city"], users, &[("id", 0)]),
            orders: table(
                "orders",
                &["id", "user_id", "amount", "status"],
                orders,
                &[("user_id", 1)],
            ),
        }
    }
}

/* --------------------- the reference executor ----------------------- */
/* The oracle. Straight-line correct code over the seeded rows — no      */
/* iterator cleverness, and it never touches the student's operators.    */

/// SQL `=`: like types compare; NULL (or a mismatch) is UNKNOWN → false.
fn sql_eq(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Int(x), Value::Int(y)) => x == y,
        (Value::Text(x), Value::Text(y)) => x == y,
        _ => false,
    }
}

/// SQL ordering: Some(cmp) for like types, None (UNKNOWN) otherwise.
fn sql_ord(a: &Value, b: &Value) -> Option<std::cmp::Ordering> {
    match (a, b) {
        (Value::Int(x), Value::Int(y)) => Some(x.cmp(y)),
        (Value::Text(x), Value::Text(y)) => Some(x.cmp(y)),
        _ => None,
    }
}

fn ref_eval(pred: &Pred, row: &Row) -> bool {
    use std::cmp::Ordering::*;
    match pred {
        Pred::Eq { col, val } => sql_eq(&row[*col], val),
        Pred::Lt { col, val } => sql_ord(&row[*col], val) == Some(Less),
        Pred::Le { col, val } => matches!(sql_ord(&row[*col], val), Some(Less) | Some(Equal)),
        Pred::Gt { col, val } => sql_ord(&row[*col], val) == Some(Greater),
        Pred::Ge { col, val } => matches!(sql_ord(&row[*col], val), Some(Greater) | Some(Equal)),
        Pred::And(a, b) => ref_eval(a, row) && ref_eval(b, row),
    }
}

fn ref_filter(rows: &[Row], pred: &Pred) -> Vec<Row> {
    rows.iter().filter(|r| ref_eval(pred, r)).cloned().collect()
}

fn ref_project(rows: &[Row], cols: &[usize]) -> Vec<Row> {
    rows.iter()
        .map(|r| cols.iter().map(|&c| r[c].clone()).collect())
        .collect()
}

/// Inner equijoin, left-outer loop order: for each left row, every right
/// row whose key equals it — the left row followed by the right row.
/// NULL keys never match.
fn ref_join(left: &[Row], right: &[Row], keys: (usize, usize)) -> Vec<Row> {
    let mut out = Vec::new();
    for l in left {
        for r in right {
            if sql_eq(&l[keys.0], &r[keys.1]) {
                let mut row = l.clone();
                row.extend(r.iter().cloned());
                out.push(row);
            }
        }
    }
    out
}

/// GROUP BY: NULL keys herd into ONE group (WHERE matches no NULLs —
/// the rules differ on purpose). One row per group: the group columns'
/// values, then the aggregates as Int. With no group columns the whole
/// input is ONE group, even an empty one. Sorted by group key.
fn ref_aggregate(rows: &[Row], group_cols: &[usize], aggs: &[Agg]) -> Vec<Row> {
    let mut groups: BTreeMap<Vec<Value>, Vec<i64>> = BTreeMap::new();
    if group_cols.is_empty() {
        groups.insert(Vec::new(), aggs.iter().map(|_| 0).collect());
    }
    for row in rows {
        let key: Vec<Value> = group_cols.iter().map(|&c| row[c].clone()).collect();
        let acc = groups.entry(key).or_insert_with(|| aggs.iter().map(|_| 0).collect());
        for (i, agg) in aggs.iter().enumerate() {
            match *agg {
                Agg::Count => acc[i] += 1,
                Agg::Sum(col) => {
                    if let Value::Int(n) = row[col] {
                        acc[i] += n;
                    }
                }
            }
        }
    }
    groups
        .into_iter()
        .map(|(key, acc)| {
            let mut row = key;
            row.extend(acc.into_iter().map(Value::Int));
            row
        })
        .collect()
}

/* --------------------------- check plumbing ------------------------- */

fn fmt_val(v: &Value) -> String {
    match v {
        Value::Int(n) => n.to_string(),
        Value::Text(s) => format!("\"{s}\""),
        Value::Null => "NULL".to_string(),
    }
}

fn fmt_row(row: &Row) -> String {
    format!("({})", row.iter().map(fmt_val).collect::<Vec<_>>().join(", "))
}

/// Pull an operator to exhaustion, bounded: a stream that will not say
/// None is a bug, not a result.
fn run(op: &mut dyn Operator, ctx: &str) -> Result<Vec<Row>, String> {
    const BOUND: usize = 100_000;
    op.open();
    let mut out = Vec::new();
    while let Some(row) = op.next() {
        out.push(row);
        if out.len() > BOUND {
            return Err(format!(
                "{ctx}: {BOUND} rows and next() still will not return None — the stream must END"
            ));
        }
    }
    op.close();
    Ok(out)
}

/// The first difference between two row streams, in order. None means
/// identical.
fn diff(got: &[Row], want: &[Row], ctx: &str) -> Option<String> {
    for (i, (g, w)) in got.iter().zip(want).enumerate() {
        if g != w {
            return Some(format!("{ctx}: row {i} — got {}, want {}", fmt_row(g), fmt_row(w)));
        }
    }
    if got.len() != want.len() {
        return Some(format!("{ctx}: got {} rows, want {}", got.len(), want.len()));
    }
    None
}

/// diff where SQL promises no order (aggregates): both sides sorted first.
fn diff_unordered(got: &[Row], want: &[Row], ctx: &str) -> Option<String> {
    let mut g = got.to_vec();
    let mut w = want.to_vec();
    g.sort();
    w.sort();
    diff(&g, &w, ctx)
}

/* ------------------------------ checks ------------------------------ */

/// 1. scan_project: a full scan + projection returns the exact rows, in
///    physical order, with the asked columns in the asked order — and a
///    close()/open() pair restarts the pass cleanly.
pub fn check_scan_project() -> Check {
    const ID: &str = "scan_project";
    const LABEL: &str = "scan + project returns the right tuples, in order";
    let db = storage::seed();
    let users = db.table("users");
    let ctx = "SELECT name, age, city FROM users";
    let got = match run(
        &mut Project::new(Box::new(SeqScan::new(users.clone())), vec![1, 2, 3]),
        ctx,
    ) {
        Ok(rows) => rows,
        Err(e) => return Check::fail(ID, LABEL, e),
    };
    let want = ref_project(users.rows(), &[1, 2, 3]);
    if let Some(e) = diff(&got, &want, ctx) {
        return Check::fail(ID, LABEL, format!(
            "{e} — a scan returns every row in physical order, untouched; a projection keeps the asked columns, in the asked order"));
    }
    // iterator discipline: close() mid-stream, re-open(), and the pass
    // must restart from the first row
    let mut scan = SeqScan::new(users.clone());
    scan.open();
    for _ in 0..5 {
        if scan.next().is_none() {
            return Check::fail(ID, LABEL, "the scan ran dry after 5 rows of a 200-row table".to_string());
        }
    }
    scan.close();
    scan.open();
    let mut second: Vec<Row> = Vec::new();
    while let Some(row) = scan.next() {
        second.push(row);
        if second.len() > 10_000 {
            return Check::fail(ID, LABEL, format!(
                "{ctx}: after close();open(), next() will not stop — open() must RESTART the pass, and the pass must end"));
        }
    }
    if let Some(e) = diff(&second, users.rows(), "the re-opened scan") {
        return Check::fail(ID, LABEL, format!("{e} — close() then open() must restart cleanly from the first row"));
    }
    if scan.next().is_some() || scan.next().is_some() {
        return Check::fail(ID, LABEL, "next() after None must keep returning None — the stream is exhausted, not restarted");
    }
    scan.close();
    Check::pass(ID, LABEL, format!("{} rows projected in order; the re-opened pass is row-for-row identical", want.len()))
}

/// 2. select_filter: predicates keep exactly the rows SQL says — ranges,
///    a zero-match predicate (an empty stream, not an error), and NULLs,
///    which no comparison ever keeps.
pub fn check_select_filter() -> Check {
    const ID: &str = "select_filter";
    const LABEL: &str = "predicates filter exactly";
    let db = storage::seed();
    let users = db.table("users");
    let orders = db.table("orders");
    let cases: Vec<(&str, &Table, Pred)> = vec![
        (
            "SELECT * FROM users WHERE city = 'Berlin'",
            &users,
            Pred::Eq { col: 3, val: Value::Text("Berlin".to_string()) },
        ),
        (
            "SELECT * FROM users WHERE age >= 18 AND age <= 24",
            &users,
            Pred::And(
                Box::new(Pred::Ge { col: 2, val: Value::Int(18) }),
                Box::new(Pred::Le { col: 2, val: Value::Int(24) }),
            ),
        ),
        (
            "SELECT * FROM orders WHERE amount > 500",
            &orders,
            Pred::Gt { col: 2, val: Value::Int(500) },
        ),
        (
            "SELECT * FROM users WHERE city = 'Atlantis'",
            &users,
            Pred::Eq { col: 3, val: Value::Text("Atlantis".to_string()) },
        ),
        (
            "SELECT * FROM orders WHERE status = 'paid'",
            &orders,
            Pred::Eq { col: 3, val: Value::Text("paid".to_string()) },
        ),
    ];
    for (sql, table, pred) in &cases {
        let got = match run(
            &mut Filter::new(Box::new(SeqScan::new((*table).clone())), (*pred).clone()),
            sql,
        ) {
            Ok(rows) => rows,
            Err(e) => return Check::fail(ID, LABEL, e),
        };
        let want = ref_filter(table.rows(), pred);
        if let Some(e) = diff(&got, &want, sql) {
            let hint = if sql.contains("status") {
                " — SQL is three-valued: status = 'paid' where status IS NULL is UNKNOWN, and UNKNOWN is not true"
            } else if sql.contains("Atlantis") {
                " — a predicate that matches nothing yields an EMPTY stream, not an error and not a panic"
            } else {
                ""
            };
            return Check::fail(ID, LABEL, format!("{e}{hint}"));
        }
    }
    Check::pass(ID, LABEL, "5 predicates exact — ranges, the empty stream, and NULLs correctly unkept".to_string())
}

/// 3. join_correct: users ⋈ orders on id = user_id through the student's
///    NestedLoopJoin — exact multiset AND order against the reference.
///    Users with many orders appear many times (multiplicity); users
///    with none do not appear (inner join).
pub fn check_join_correct() -> Check {
    const ID: &str = "join_correct";
    const LABEL: &str = "nested-loop join matches the reference";
    let db = storage::seed();
    let users = db.table("users");
    let orders = db.table("orders");
    let ctx = "SELECT * FROM users JOIN orders ON users.id = orders.user_id";
    let mut join = NestedLoopJoin::new(
        Box::new(SeqScan::new(users.clone())),
        Box::new(SeqScan::new(orders.clone())),
        (0, 1),
    );
    let got = match run(&mut join, ctx) {
        Ok(rows) => rows,
        Err(e) => return Check::fail(ID, LABEL, e),
    };
    let want = ref_join(users.rows(), orders.rows(), (0, 1));
    if got.len() != want.len() {
        return Check::fail(ID, LABEL, format!(
            "{ctx}: got {} rows, want {} — a user with k orders contributes k rows (multiplicity!); a user with zero orders contributes none (inner join)",
            got.len(), want.len()));
    }
    if let Some(e) = diff(&got, &want, ctx) {
        return Check::fail(ID, LABEL, format!(
            "{e} — the output row is the left row followed by the right row, in left-outer loop order"));
    }
    Check::pass(ID, LABEL, format!("{} joined rows — multiplicity and order exact, every whale's orders under their own name", want.len()))
}

/// 4. aggregate_correct: COUNT(*)/SUM with no GROUP BY (one group), by
///    status (NULLs form their OWN group — the opposite of WHERE), and
///    by city. Group order is free; the contents are not.
pub fn check_aggregate_correct() -> Check {
    const ID: &str = "aggregate_correct";
    const LABEL: &str = "group/count/sum match the reference";
    let db = storage::seed();
    let users = db.table("users");
    let orders = db.table("orders");

    // global: no GROUP BY — the whole table is ONE group
    let ctx0 = "SELECT COUNT(*), SUM(amount) FROM orders";
    let got0 = match run(
        &mut HashAggregate::new(
            Box::new(SeqScan::new(orders.clone())),
            vec![],
            vec![Agg::Count, Agg::Sum(2)],
        ),
        ctx0,
    ) {
        Ok(rows) => rows,
        Err(e) => return Check::fail(ID, LABEL, e),
    };
    let want0 = ref_aggregate(orders.rows(), &[], &[Agg::Count, Agg::Sum(2)]);
    if got0.len() != 1 {
        return Check::fail(ID, LABEL, format!(
            "{ctx0}: got {} rows, want exactly 1 — with no GROUP BY the whole input is ONE group",
            got0.len()));
    }
    if let Some(e) = diff(&got0, &want0, ctx0) {
        return Check::fail(ID, LABEL, format!(
            "{e} — COUNT(*) counts every row (NULLs included); SUM skips NULLs and totals the Ints"));
    }

    // by status: the NULL group must exist, distinct from 'paid' & co.
    let ctx1 = "SELECT status, COUNT(*), SUM(amount) FROM orders GROUP BY status";
    let got1 = match run(
        &mut HashAggregate::new(
            Box::new(SeqScan::new(orders.clone())),
            vec![3],
            vec![Agg::Count, Agg::Sum(2)],
        ),
        ctx1,
    ) {
        Ok(rows) => rows,
        Err(e) => return Check::fail(ID, LABEL, e),
    };
    let want1 = ref_aggregate(orders.rows(), &[3], &[Agg::Count, Agg::Sum(2)]);
    if got1.len() != want1.len() {
        return Check::fail(ID, LABEL, format!(
            "{ctx1}: got {} groups, want {} — GROUP BY herds all NULL statuses into ONE group of their own (WHERE matches no NULLs; GROUP BY groups them — the two rules DIFFER)",
            got1.len(), want1.len()));
    }
    if let Some(e) = diff_unordered(&got1, &want1, ctx1) {
        return Check::fail(ID, LABEL, format!(
            "{e} — one row per group: the group column's value, then the aggregates in the order given"));
    }

    // by city
    let ctx2 = "SELECT city, COUNT(*) FROM users GROUP BY city";
    let got2 = match run(
        &mut HashAggregate::new(Box::new(SeqScan::new(users.clone())), vec![3], vec![Agg::Count]),
        ctx2,
    ) {
        Ok(rows) => rows,
        Err(e) => return Check::fail(ID, LABEL, e),
    };
    let want2 = ref_aggregate(users.rows(), &[3], &[Agg::Count]);
    if let Some(e) = diff_unordered(&got2, &want2, ctx2) {
        return Check::fail(ID, LABEL, format!("{e} — one row per city, count exact"));
    }
    Check::pass(ID, LABEL, format!(
        "global count/sum exact; {} status groups (NULL included) and {} city groups, all exact",
        want1.len(), want2.len()))
}

/// 5. query_suite: eight canned queries end to end — scan/filter/project,
///    index point lookups, and join/filter/aggregate combos — every row
///    against the reference executor.
pub fn check_query_suite() -> Check {
    const ID: &str = "query_suite";
    const LABEL: &str = "the fixed query suite, end to end, over your own storage";
    let db = storage::seed();
    let users = db.table("users");
    let orders = db.table("orders");

    struct Q {
        sql: &'static str,
        unordered: bool, // SQL promises no order (aggregates)
        plan: Box<dyn FnOnce() -> Box<dyn Operator>>,
        answer: Box<dyn FnOnce() -> Vec<Row>>,
    }

    let text = |s: &str| Value::Text(s.to_string());
    let mut queries: Vec<Q> = Vec::new();

    // q1: scan + filter + project
    queries.push(Q {
        sql: "SELECT name, age FROM users WHERE city = 'Lisbon'",
        unordered: false,
        plan: {
            let t = users.clone();
            Box::new(move || {
                Box::new(Project::new(
                    Box::new(Filter::new(
                        Box::new(SeqScan::new(t)),
                        Pred::Eq { col: 3, val: text("Lisbon") },
                    )),
                    vec![1, 2],
                )) as Box<dyn Operator>
            })
        },
        answer: {
            let t = users.clone();
            Box::new(move || {
                ref_project(
                    &ref_filter(t.rows(), &Pred::Eq { col: 3, val: text("Lisbon") }),
                    &[1, 2],
                )
            })
        },
    });

    // q2: the zipf tail
    queries.push(Q {
        sql: "SELECT id, amount FROM orders WHERE amount >= 1000",
        unordered: false,
        plan: {
            let t = orders.clone();
            Box::new(move || {
                Box::new(Project::new(
                    Box::new(Filter::new(
                        Box::new(SeqScan::new(t)),
                        Pred::Ge { col: 2, val: Value::Int(1000) },
                    )),
                    vec![0, 2],
                )) as Box<dyn Operator>
            })
        },
        answer: {
            let t = orders.clone();
            Box::new(move || {
                ref_project(
                    &ref_filter(t.rows(), &Pred::Ge { col: 2, val: Value::Int(1000) }),
                    &[0, 2],
                )
            })
        },
    });

    // q3: index point lookup — a whale user's orders
    queries.push(Q {
        sql: "SELECT * FROM orders WHERE user_id = 5",
        unordered: false,
        plan: {
            let t = orders.clone();
            Box::new(move || Box::new(IndexScan::new(t, "user_id", 5)) as Box<dyn Operator>)
        },
        answer: {
            let t = orders.clone();
            Box::new(move || ref_filter(t.rows(), &Pred::Eq { col: 1, val: Value::Int(5) }))
        },
    });

    // q4: index point lookup on the primary key + project
    queries.push(Q {
        sql: "SELECT name, city FROM users WHERE id = 7",
        unordered: false,
        plan: {
            let t = users.clone();
            Box::new(move || {
                Box::new(Project::new(Box::new(IndexScan::new(t, "id", 7)), vec![1, 3]))
                    as Box<dyn Operator>
            })
        },
        answer: {
            let t = users.clone();
            Box::new(move || {
                ref_project(&ref_filter(t.rows(), &Pred::Eq { col: 0, val: Value::Int(7) }), &[1, 3])
            })
        },
    });

    // q5: join + filter + project — the big city's order book
    queries.push(Q {
        sql: "SELECT name, amount FROM users JOIN orders ON users.id = orders.user_id WHERE city = 'Berlin'",
        unordered: false,
        plan: {
            let (u, o) = (users.clone(), orders.clone());
            Box::new(move || {
                Box::new(Project::new(
                    Box::new(Filter::new(
                        Box::new(NestedLoopJoin::new(
                            Box::new(SeqScan::new(u)),
                            Box::new(SeqScan::new(o)),
                            (0, 1),
                        )),
                        Pred::Eq { col: 3, val: text("Berlin") },
                    )),
                    vec![1, 6],
                )) as Box<dyn Operator>
            })
        },
        answer: {
            let (u, o) = (users.clone(), orders.clone());
            Box::new(move || {
                let joined = ref_join(u.rows(), o.rows(), (0, 1));
                ref_project(
                    &ref_filter(&joined, &Pred::Eq { col: 3, val: text("Berlin") }),
                    &[1, 6],
                )
            })
        },
    });

    // q6: filter + aggregate — the small-change ledger, NULL group included
    queries.push(Q {
        sql: "SELECT status, COUNT(*), SUM(amount) FROM orders WHERE amount < 100 GROUP BY status",
        unordered: true,
        plan: {
            let t = orders.clone();
            Box::new(move || {
                Box::new(HashAggregate::new(
                    Box::new(Filter::new(
                        Box::new(SeqScan::new(t)),
                        Pred::Lt { col: 2, val: Value::Int(100) },
                    )),
                    vec![3],
                    vec![Agg::Count, Agg::Sum(2)],
                )) as Box<dyn Operator>
            })
        },
        answer: {
            let t = orders.clone();
            Box::new(move || {
                ref_aggregate(
                    &ref_filter(t.rows(), &Pred::Lt { col: 2, val: Value::Int(100) }),
                    &[3],
                    &[Agg::Count, Agg::Sum(2)],
                )
            })
        },
    });

    // q7: filter + aggregate over users
    queries.push(Q {
        sql: "SELECT city, COUNT(*) FROM users WHERE age >= 60 GROUP BY city",
        unordered: true,
        plan: {
            let t = users.clone();
            Box::new(move || {
                Box::new(HashAggregate::new(
                    Box::new(Filter::new(
                        Box::new(SeqScan::new(t)),
                        Pred::Ge { col: 2, val: Value::Int(60) },
                    )),
                    vec![3],
                    vec![Agg::Count],
                )) as Box<dyn Operator>
            })
        },
        answer: {
            let t = users.clone();
            Box::new(move || {
                ref_aggregate(
                    &ref_filter(t.rows(), &Pred::Ge { col: 2, val: Value::Int(60) }),
                    &[3],
                    &[Agg::Count],
                )
            })
        },
    });

    // q8: join + filter — pending orders with their owners (NULLs stay out)
    queries.push(Q {
        sql: "SELECT name, status FROM users JOIN orders ON users.id = orders.user_id WHERE status = 'pending'",
        unordered: false,
        plan: {
            let (u, o) = (users.clone(), orders.clone());
            Box::new(move || {
                Box::new(Project::new(
                    Box::new(Filter::new(
                        Box::new(NestedLoopJoin::new(
                            Box::new(SeqScan::new(u)),
                            Box::new(SeqScan::new(o)),
                            (0, 1),
                        )),
                        Pred::Eq { col: 7, val: text("pending") },
                    )),
                    vec![1, 7],
                )) as Box<dyn Operator>
            })
        },
        answer: {
            let (u, o) = (users.clone(), orders.clone());
            Box::new(move || {
                let joined = ref_join(u.rows(), o.rows(), (0, 1));
                ref_project(
                    &ref_filter(&joined, &Pred::Eq { col: 7, val: text("pending") }),
                    &[1, 7],
                )
            })
        },
    });

    for (i, q) in queries.into_iter().enumerate() {
        let ctx = q.sql;
        let mut op = (q.plan)();
        let got = match run(op.as_mut(), ctx) {
            Ok(rows) => rows,
            Err(e) => return Check::fail(ID, LABEL, format!("query {} of 8 — {e}", i + 1)),
        };
        let want = (q.answer)();
        let d = if q.unordered { diff_unordered(&got, &want, ctx) } else { diff(&got, &want, ctx) };
        if let Some(e) = d {
            return Check::fail(ID, LABEL, format!("query {} of 8 — {e}", i + 1));
        }
    }
    Check::pass(ID, LABEL, "8/8 queries row-for-row exact against the reference executor".to_string())
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_scan_project(),
        check_select_filter(),
        check_join_correct(),
        check_aggregate_correct(),
        check_query_suite(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "volcano", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
