//! mvcc — forge lab 04 (tablespace).
//!
//! Many worlds, one truth each. Labs 01–03 built the page, the tree, and
//! the log; this lab lets many transactions share the store at once —
//! without a single reader ever blocking a writer. The move is MVCC:
//! WRITE never overwrites, it appends a version; every txn reads from a
//! snapshot frozen at begin(). Lab 05 gives these worlds a query language.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/mvcc.rs        (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The ops: begin / write / read / commit / abort. The hard parts:
//!   * the visibility rule is ONE predicate — a version is visible iff
//!     its creator is you, or committed at-or-before your snapshot and
//!     was not in flight when you began — and every wrong answer here is
//!     a way to get that sentence wrong;
//!   * first-writer-wins: a second live writer to the same key is
//!     rejected, and the rejection must survive the loser's commit;
//!   * abort removes every trace: the txn's versions die with it, and
//!     the keys it held become writable again.
//!
//! There are no threads in this lab. The harness enumerates interleavings
//! with a deterministic scheduler — seeded shuffles of the five ops across
//! three txns — and grades every read against a serial reference that
//! computes the snapshot-isolated answer from first principles. Not "it
//! passed when I tried it": it passes every schedule we could construct.

mod mvcc;

use kslab::{Check, Report};
use mvcc::{Mvcc, TxnId};
use std::collections::BTreeMap;

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* --------------------- the serial-SI reference ---------------------- */

const SLOTS: usize = 3; // concurrent txns per schedule
const KEYS: usize = 8; // the key universe: "k0"..="k7"
const SCHEDULES: usize = 200; // seeded interleavings
const OPS: usize = 30; // ops per schedule

/// Snapshot isolation executed SERIALLY — the reference the storm grades
/// against. A read's answer is computed directly from the rule: the
/// reader's own writes overlay the latest version committed at-or-before
/// its snapshot. It never looks at the student's store.
struct Model {
    clock: u64, // commits so far; a begin() snapshots this value
    committed: BTreeMap<String, Vec<(u64, String)>>, // key → versions, ascending commit seq
    pending: BTreeMap<String, usize>, // key → slot holding an uncommitted version
    txns: [Option<ModelTxn>; SLOTS],  // slot → live txn
}

struct ModelTxn {
    snap: u64,                        // the clock value frozen at begin()
    writes: BTreeMap<String, String>, // its own uncommitted writes, latest per key
}

impl Model {
    fn new() -> Model {
        Model { clock: 0, committed: BTreeMap::new(), pending: BTreeMap::new(), txns: [None, None, None] }
    }
    fn begin(&mut self, slot: usize) {
        self.txns[slot] = Some(ModelTxn { snap: self.clock, writes: BTreeMap::new() });
    }
    /// First-writer-wins: false iff ANOTHER live slot holds the key.
    fn write(&mut self, slot: usize, key: &str, value: &str) -> bool {
        if self.pending.get(key).is_some_and(|&holder| holder != slot) {
            return false;
        }
        self.pending.insert(key.to_string(), slot);
        self.txns[slot].as_mut().unwrap().writes.insert(key.to_string(), value.to_string());
        true
    }
    /// Own writes first; else the latest version committed at the snapshot.
    fn read(&self, slot: usize, key: &str) -> Option<String> {
        let txn = self.txns[slot].as_ref().unwrap();
        if let Some(v) = txn.writes.get(key) {
            return Some(v.clone());
        }
        self.committed.get(key)?.iter().rev().find(|(seq, _)| *seq <= txn.snap).map(|(_, v)| v.clone())
    }
    /// Commit publishes the txn's writes at the next clock tick; abort
    /// drops them. Either way the keys it held are free again.
    fn end(&mut self, slot: usize, commit: bool) {
        let txn = self.txns[slot].take().unwrap();
        if commit {
            self.clock += 1;
            for (k, v) in txn.writes {
                self.pending.remove(&k);
                self.committed.entry(k).or_default().push((self.clock, v));
            }
        } else {
            for k in txn.writes.keys() {
                self.pending.remove(k);
            }
        }
    }
}

/* ------------------------- harness toolbox -------------------------- */

/// Assert one read inside a scripted check. `ctx` carries the teaching —
/// the step, the txn, why the answer must be what it must be.
fn expect_read(db: &Mvcc, txn: TxnId, key: &str, want: Option<&str>, ctx: &str) -> Option<String> {
    let got = db.read(txn, key);
    if got.as_deref() == want {
        return None;
    }
    Some(format!("{ctx}: read \"{key}\" = {got:?}, want {want:?}"))
}

/// Assert one write succeeds inside a scripted check.
fn expect_write_ok(db: &mut Mvcc, txn: TxnId, key: &str, value: &str, ctx: &str) -> Option<String> {
    match db.write(txn, key, value) {
        Ok(()) => None,
        Err(c) => Some(format!(
            "{ctx}: write \"{key}\" = {value:?} rejected — WwConflict says txn {} holds it, but no other live txn has an uncommitted version of it",
            c.holder
        )),
    }
}

/// One seeded schedule, replayed against the student's store and the
/// reference in lockstep. OPS ops over SLOTS txn slots and KEYS keys; op
/// kinds and targets come from the seed alone, never from the student's
/// answers, so every schedule is exactly OPS steps and fully reproducible.
/// Returns (reads, writes) checked, or the failure sentence.
fn run_schedule(seed: u64, sched: usize) -> Result<(usize, usize), String> {
    let mut db = Mvcc::new();
    let mut model = Model::new();
    let mut slots: [Option<TxnId>; SLOTS] = [None; SLOTS];
    let mut rng = Rng(seed);
    let (mut reads, mut writes) = (0usize, 0usize);
    for i in 0..OPS {
        let live: Vec<usize> = (0..SLOTS).filter(|&s| slots[s].is_some()).collect();
        let free: Vec<usize> = (0..SLOTS).filter(|&s| slots[s].is_none()).collect();
        // weights: begin 15, write 30, read 40, commit 10, abort 5 — every
        // op applicable, so begins are forced when nothing is live and
        // remapped when all three txns are already running
        let kind = if live.is_empty() { 0 } else if free.is_empty() { 15 + rng.below(85) } else { rng.below(100) };
        match kind {
            0..=14 => {
                let s = free[rng.below(free.len())];
                slots[s] = Some(db.begin());
                model.begin(s);
            }
            15..=44 => {
                let s = live[rng.below(live.len())];
                let key = format!("k{}", rng.below(KEYS));
                let value = format!("s{sched}o{i}"); // unique per write op
                writes += 1;
                let mine = db.write(slots[s].unwrap(), &key, &value).is_ok();
                let want = model.write(s, &key, &value);
                if mine != want {
                    return Err(format!(
                        "schedule {sched} op {i}: slot-{s} write \"{key}\" = {value:?}: {} — first-writer-wins: a key whose newest version belongs to ANOTHER live txn rejects the write, anything else accepts it",
                        if want { "yours returned Err but the reference allows it" } else { "yours succeeded but the reference rejects it" }
                    ));
                }
            }
            45..=84 => {
                let s = live[rng.below(live.len())];
                let key = format!("k{}", rng.below(KEYS));
                reads += 1;
                let got = db.read(slots[s].unwrap(), &key);
                let want = model.read(s, &key);
                if got != want {
                    return Err(format!(
                        "schedule {sched} op {i}: slot-{s} read \"{key}\" = {got:?} but the serial reference says {want:?} — a read sees the latest version committed at its own snapshot, with its own writes overlayed"
                    ));
                }
            }
            85..=94 => {
                let s = live[rng.below(live.len())];
                db.commit(slots[s].take().unwrap());
                model.end(s, true);
            }
            _ => {
                let s = live[rng.below(live.len())];
                db.abort(slots[s].take().unwrap());
                model.end(s, false);
            }
        }
    }
    Ok((reads, writes))
}

/* ------------------------------ checks ------------------------------ */

/// 1. no_dirty_reads: T1 writes k and stays in flight; T2 — whose snapshot
///    cannot contain T1's version — must read the OLD committed value, and
///    must STILL read it after T1 commits (the snapshot froze at begin).
///    A fresh T3 sees the new world.
pub fn check_no_dirty_reads() -> Check {
    const ID: &str = "no_dirty_reads";
    const LABEL: &str = "uncommitted writes are invisible to other txns";
    let mut db = Mvcc::new();
    // T0 leaves k = "old" committed behind it.
    let t0 = db.begin();
    if let Some(m) = expect_write_ok(&mut db, t0, "k", "old", "step 1: T0 seeds \"k\" = \"old\" and commits") {
        return Check::fail(ID, LABEL, m);
    }
    db.commit(t0);

    // T1 overwrites k but stays in flight — its version must be invisible
    // to everyone but itself.
    let t1 = db.begin();
    if let Some(m) = expect_write_ok(&mut db, t1, "k", "new", "step 2: T1's write — the only other version of \"k\" is committed, so nothing blocks it") {
        return Check::fail(ID, LABEL, m);
    }
    // T2 begins while T1 is in flight: T1's version is not in its world.
    let t2 = db.begin();
    if let Some(m) = expect_read(&db, t2, "k", Some("old"), "step 3: T2 reads \"k\" while T1's \"new\" sits uncommitted — the committed truth is \"old\"; a dirty read leaks a version that may never exist") {
        return Check::fail(ID, LABEL, m);
    }
    // a brand-new uncommitted key is equally invisible
    if let Some(m) = expect_write_ok(&mut db, t1, "ghost", "boo", "step 4: T1 creates a key that has no committed version at all") {
        return Check::fail(ID, LABEL, m);
    }
    if let Some(m) = expect_read(&db, t2, "ghost", None, "step 4: T2 must not see it — uncommitted creates are as invisible as uncommitted overwrites") {
        return Check::fail(ID, LABEL, m);
    }
    // T1 commits — AFTER T2's snapshot. T2's world still does not move.
    db.commit(t1);
    if let Some(m) = expect_read(&db, t2, "k", Some("old"), "step 5: T1 committed AFTER T2 began — a snapshot is taken at begin() and never moves") {
        return Check::fail(ID, LABEL, m);
    }
    if let Some(m) = expect_read(&db, t2, "ghost", None, "step 5: \"ghost\" is still outside T2's snapshot") {
        return Check::fail(ID, LABEL, m);
    }
    // …but a fresh txn reads the new world.
    let t3 = db.begin();
    if let Some(m) = expect_read(&db, t3, "k", Some("new"), "step 6: T3 began after T1's commit — the new version is its truth now") {
        return Check::fail(ID, LABEL, m);
    }
    if let Some(m) = expect_read(&db, t3, "ghost", Some("boo"), "step 6: and \"ghost\" exists for T3") {
        return Check::fail(ID, LABEL, m);
    }
    Check::pass(ID, LABEL, "T2 never saw T1's uncommitted versions — not before T1's commit, and (its snapshot froze at begin) not after; fresh T3 sees them")
}

/// 2. snapshot_repeatable: T1 reads three keys; T2..T4 then commit writes
///    over every one of them (plus a brand-new key), strictly after T1's
///    snapshot. Every re-read by T1 — long after those commits — returns
///    identical results. A fresh txn proves the world really moved.
pub fn check_snapshot_repeatable() -> Check {
    const ID: &str = "snapshot_repeatable";
    const LABEL: &str = "a snapshot re-reads its own past, forever";
    let mut db = Mvcc::new();
    // T0 seeds three keys and commits.
    let t0 = db.begin();
    for (k, v) in [("k0", "seed0"), ("k1", "seed1"), ("k2", "seed2")] {
        if let Some(m) = expect_write_ok(&mut db, t0, k, v, "step 1: T0 seeds the committed world") {
            return Check::fail(ID, LABEL, m);
        }
    }
    db.commit(t0);

    // T1 begins — and its world stops moving.
    let t1 = db.begin();
    for (k, v) in [("k0", "seed0"), ("k1", "seed1"), ("k2", "seed2")] {
        if let Some(m) = expect_read(&db, t1, k, Some(v), "step 2: T1's baseline read") {
            return Check::fail(ID, LABEL, m);
        }
    }

    // T2..T4 overwrite keys T1 has read — and create a new one — all
    // committing strictly AFTER T1's snapshot.
    let t2 = db.begin();
    if let Some(m) = expect_write_ok(&mut db, t2, "k0", "t2", "step 3: T2 overwrites \"k0\" — T1 holds no version of it") {
        return Check::fail(ID, LABEL, m);
    }
    db.commit(t2);
    if let Some(m) = expect_read(&db, t1, "k0", Some("seed0"), "step 3: T2 committed k0=\"t2\" after T1 began — T1's snapshot is fixed") {
        return Check::fail(ID, LABEL, m);
    }

    let t3 = db.begin();
    for k in ["k1", "k2"] {
        if let Some(m) = expect_write_ok(&mut db, t3, k, "t3", "step 4: T3 overwrites two more keys T1 has read") {
            return Check::fail(ID, LABEL, m);
        }
    }
    db.commit(t3);
    for (k, v) in [("k1", "seed1"), ("k2", "seed2")] {
        if let Some(m) = expect_read(&db, t1, k, Some(v), "step 4: T3's commits are after T1's snapshot too") {
            return Check::fail(ID, LABEL, m);
        }
    }

    let t4 = db.begin();
    for k in ["k0", "k1", "k2"] {
        if let Some(m) = expect_write_ok(&mut db, t4, k, "t4", "step 5: T4 rewrites everything") {
            return Check::fail(ID, LABEL, m);
        }
    }
    if let Some(m) = expect_write_ok(&mut db, t4, "k3", "t4-new", "step 5: T4 creates a brand-new key") {
        return Check::fail(ID, LABEL, m);
    }
    db.commit(t4);
    for (k, v) in [("k0", "seed0"), ("k1", "seed1"), ("k2", "seed2")] {
        if let Some(m) = expect_read(&db, t1, k, Some(v), "step 5: long after T4's commit, T1 still re-reads its own past") {
            return Check::fail(ID, LABEL, m);
        }
    }
    if let Some(m) = expect_read(&db, t1, "k3", None, "step 5: \"k3\" was CREATED after T1's snapshot — it does not exist in T1's world") {
        return Check::fail(ID, LABEL, m);
    }

    // The world moved on — just not for T1. A fresh txn proves the writes landed.
    let t5 = db.begin();
    for (k, v) in [("k0", "t4"), ("k1", "t4"), ("k2", "t4"), ("k3", "t4-new")] {
        if let Some(m) = expect_read(&db, t5, k, Some(v), "step 6: a fresh txn reads the present") {
            return Check::fail(ID, LABEL, m);
        }
    }
    Check::pass(ID, LABEL, "T1 re-read its snapshot through three later committers — every answer identical; fresh T5 sees the new world")
}

/// 3. ww_conflict: T1 and T2 write the same key while both live — exactly
///    one succeeds; the loser is rejected with a conflict naming the key
///    and the holder, and the loser's later commit must not resurrect the
///    lost write. Commit and abort both release the held key.
pub fn check_ww_conflict() -> Check {
    const ID: &str = "ww_conflict";
    const LABEL: &str = "second writer to the same row is rejected";
    let mut db = Mvcc::new();
    // T0 leaves a committed version of "k" behind — conflicts are about
    // the LIVE version at the head of the chain, not about whether the
    // key exists at all.
    let t0 = db.begin();
    if let Some(m) = expect_write_ok(&mut db, t0, "k", "committed-v", "step 1: T0 seeds \"k\" and commits") {
        return Check::fail(ID, LABEL, m);
    }
    db.commit(t0);

    let t1 = db.begin();
    let t2 = db.begin();
    // step 2: T1 writes k — the head version is committed, nothing blocks.
    if let Some(m) = expect_write_ok(&mut db, t1, "k", "t1-wins", "step 2: T1 writes \"k\" — its newest version is committed, so no one holds it") {
        return Check::fail(ID, LABEL, m);
    }
    // step 3: T2 writes the same key while T1 is in flight — rejected.
    match db.write(t2, "k", "t2-loses") {
        Ok(()) => {
            return Check::fail(ID, LABEL, "step 3: T2's write to \"k\" succeeded while T1 holds an uncommitted version of it — first writer wins; let both through and one committed update silently erases the other (a lost update)");
        }
        Err(c) => {
            if c.key != "k" || c.holder != t1 {
                return Check::fail(ID, LABEL, format!("step 3: WwConflict must name the contended key and the holder — got key {:?}, holder txn {} (want \"k\" held by T1)", c.key, c.holder));
            }
        }
    }
    // step 4: the rejection is per-key — T2 lives on and takes another key.
    if let Some(m) = expect_write_ok(&mut db, t2, "j", "t2-ok", "step 4: a conflict rejects ONE write, it does not doom the txn — T2's write to a different key") {
        return Check::fail(ID, LABEL, m);
    }
    // step 5: the winner commits; the loser commits its OTHER writes. The
    // rejected write must stay rejected — no resurrection at commit time.
    db.commit(t1);
    db.commit(t2);
    let t3 = db.begin();
    if let Some(m) = expect_read(&db, t3, "k", Some("t1-wins"), "step 5: T2's commit must not resurrect its rejected write — the winner's value stands") {
        return Check::fail(ID, LABEL, m);
    }
    if let Some(m) = expect_read(&db, t3, "j", Some("t2-ok"), "step 5: T2's surviving write is the only one its commit published") {
        return Check::fail(ID, LABEL, m);
    }
    // step 6: once the holder commits, the key is writable again.
    let t4 = db.begin();
    if let Some(m) = expect_write_ok(&mut db, t4, "k", "t4-next", "step 6: T1 committed — its version no longer blocks anyone") {
        return Check::fail(ID, LABEL, m);
    }
    db.commit(t4);
    // step 7: abort releases too — an aborted holder's version dies with it.
    let t5 = db.begin();
    if let Some(m) = expect_write_ok(&mut db, t5, "z", "tmp", "step 7: T5 takes \"z\"") {
        return Check::fail(ID, LABEL, m);
    }
    db.abort(t5);
    let t6 = db.begin();
    if let Some(m) = expect_write_ok(&mut db, t6, "z", "after-abort", "step 7: T5 aborted — \"z\" is free again, T6 must not see a conflict") {
        return Check::fail(ID, LABEL, m);
    }
    db.commit(t6);
    let t7 = db.begin();
    if let Some(m) = expect_read(&db, t7, "k", Some("t4-next"), "step 8: the post-conflict rewrite landed") {
        return Check::fail(ID, LABEL, m);
    }
    if let Some(m) = expect_read(&db, t7, "z", Some("after-abort"), "step 8: the post-abort rewrite landed") {
        return Check::fail(ID, LABEL, m);
    }
    Check::pass(ID, LABEL, "T2 was rejected while T1 held \"k\", and the loser's commit changed nothing; commit and abort both release the key")
}

/// 4. read_own_writes: T1's uncommitted versions are visible to T1 (latest
///    first) and to no one else; abort burns them all, even for later txns.
pub fn check_read_own_writes() -> Check {
    const ID: &str = "read_own_writes";
    const LABEL: &str = "a txn sees its own writes; others do not";
    let mut db = Mvcc::new();
    let t0 = db.begin();
    if let Some(m) = expect_write_ok(&mut db, t0, "k", "old", "step 1: T0 seeds \"k\" = \"old\" and commits") {
        return Check::fail(ID, LABEL, m);
    }
    db.commit(t0);

    let t1 = db.begin();
    if let Some(m) = expect_write_ok(&mut db, t1, "k", "mine", "step 2: T1 writes \"k\"") {
        return Check::fail(ID, LABEL, m);
    }
    if let Some(m) = expect_read(&db, t1, "k", Some("mine"), "step 3: a txn reads its own write the moment it lands — no waiting for commit") {
        return Check::fail(ID, LABEL, m);
    }
    let t2 = db.begin();
    if let Some(m) = expect_read(&db, t2, "k", Some("old"), "step 4: T1's uncommitted version is T1's alone — concurrent T2 reads the committed past") {
        return Check::fail(ID, LABEL, m);
    }
    // your own LATEST write wins
    if let Some(m) = expect_write_ok(&mut db, t1, "k", "mine-v2", "step 5: T1 rewrites its own key — stacking your own version is always allowed") {
        return Check::fail(ID, LABEL, m);
    }
    if let Some(m) = expect_read(&db, t1, "k", Some("mine-v2"), "step 5: your own latest version is the one you see") {
        return Check::fail(ID, LABEL, m);
    }
    if let Some(m) = expect_read(&db, t2, "k", Some("old"), "step 5: and T2's world still has not moved") {
        return Check::fail(ID, LABEL, m);
    }
    // a key only T1 has ever written
    if let Some(m) = expect_write_ok(&mut db, t1, "solo", "x", "step 6: T1 creates a brand-new key") {
        return Check::fail(ID, LABEL, m);
    }
    if let Some(m) = expect_read(&db, t1, "solo", Some("x"), "step 6: visible to its creator") {
        return Check::fail(ID, LABEL, m);
    }
    if let Some(m) = expect_read(&db, t2, "solo", None, "step 6: invisible to everyone else until commit") {
        return Check::fail(ID, LABEL, m);
    }
    // abort: every one of T1's versions dies — even for later txns
    db.abort(t1);
    let t3 = db.begin();
    if let Some(m) = expect_read(&db, t3, "k", Some("old"), "step 7: T1 aborted — its versions are gone as if it never ran; the committed past returns") {
        return Check::fail(ID, LABEL, m);
    }
    if let Some(m) = expect_read(&db, t3, "solo", None, "step 7: and its private key died with it") {
        return Check::fail(ID, LABEL, m);
    }
    Check::pass(ID, LABEL, "T1 read its own writes (latest first) while T2 saw only the committed past; abort erased every trace of T1")
}

/// 5. interleaving_storm: the deterministic scheduler enumerates 200 seeded
///    schedules of 30 ops across 3 concurrent txns and an 8-key universe —
///    begin/write/read/commit/abort in every order the seeds construct.
///    Every read must match the serial-SI reference and every write must
///    agree with it on accept/reject. First divergence names the schedule,
///    the op, the key.
pub fn check_interleaving_storm() -> Check {
    const ID: &str = "interleaving_storm";
    const LABEL: &str = "enumerated interleavings vs a serial reference";
    let (mut reads, mut writes) = (0usize, 0usize);
    for s in 0..SCHEDULES {
        match run_schedule(0x4D56_0000 + s as u64, s) {
            Ok((r, w)) => {
                reads += r;
                writes += w;
            }
            Err(m) => return Check::fail(ID, LABEL, m),
        }
    }
    Check::pass(ID, LABEL, format!("{SCHEDULES} seeded schedules × {OPS} ops over {SLOTS} txns and {KEYS} keys: all {reads} reads and all {writes} writes match the serial-SI reference"))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_no_dirty_reads(),
        check_snapshot_repeatable(),
        check_ww_conflict(),
        check_read_own_writes(),
        check_interleaving_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "mvcc", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
