//! wal — forge lab 03 (tablespace).
//!
//! Durability as a protocol: log every mutation BEFORE it touches state,
//! checksum every record, and make recovery a deterministic replay. Labs
//! 01–02 built the page and the tree; this one survives its own death —
//! the harness kills the module at seeded points, tears the log mid-record,
//! flips payload bytes, then grades what rises from the disk.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/wal.rs         (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The seam (documented in wal.rs): the checks drive the student API —
//! put / delete / get / commit_tick / crash / recover — and between a
//! crash() and its recover() the harness owns `wal.disk.bytes`, truncating
//! it to seeded byte boundaries (mid-record tails included) and flipping
//! payload bytes. Ordering is graded off the analyzer tape: every
//! disk.append is a Flushed(lsn), every state apply an Applied(lsn).

mod wal;

use kslab::{Check, Report};
use std::collections::BTreeMap;
use wal::{crc32, Event, Wal, OP_COMMIT, OP_DEL, OP_PUT, REC_CRC, REC_HEADER};

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* ----------------------- the reference logger ----------------------- */

/// One scripted record, as the harness dictates it to the student.
#[derive(Clone)]
struct Rec {
    op: u8,
    key: String,
    val: String,
}

impl Rec {
    fn put(k: &str, v: &str) -> Rec {
        Rec { op: OP_PUT, key: k.to_string(), val: v.to_string() }
    }
    fn del(k: &str) -> Rec {
        Rec { op: OP_DEL, key: k.to_string(), val: String::new() }
    }
    fn commit() -> Rec {
        Rec { op: OP_COMMIT, key: String::new(), val: String::new() }
    }
    /// Byte length of this record under the pinned format.
    fn len(&self) -> usize {
        REC_HEADER + self.key.len() + self.val.len() + REC_CRC
    }
    fn desc(&self) -> String {
        match self.op {
            OP_PUT => format!("put {}={:?}", self.key, self.val),
            OP_DEL => format!("del {}", self.key),
            _ => "commit".to_string(),
        }
    }
}

fn apply(state: &mut BTreeMap<String, String>, r: &Rec) {
    match r.op {
        OP_PUT => {
            state.insert(r.key.clone(), r.val.clone());
        }
        OP_DEL => {
            state.remove(&r.key);
        }
        _ => {}
    }
}

/// The reference logger: what the durable file must hold and what recovery
/// must rebuild, kept by the harness as ops are dictated. Mirrors the
/// recovery contract from wal.rs — committed transactions only, torn tail
/// dropped — written independently of the student's code.
struct Model {
    log: Vec<Rec>,
    live: BTreeMap<String, String>,
    byte_len: usize,
}

impl Model {
    fn new() -> Model {
        Model { log: Vec::new(), live: BTreeMap::new(), byte_len: 0 }
    }
    fn push(&mut self, r: Rec) {
        self.byte_len += r.len();
        if r.op != OP_COMMIT {
            apply(&mut self.live, &r);
        }
        self.log.push(r);
    }
    /// The world after crash() + a tear at byte `cut` + recover(): records
    /// past the cut are gone; of the survivors, only committed transactions
    /// replay. The live view rebases onto the recovered state.
    fn crash_at(&mut self, cut: usize) {
        let mut valid = 0;
        let mut off = 0;
        while valid < self.log.len() && off + self.log[valid].len() <= cut {
            off += self.log[valid].len();
            valid += 1;
        }
        self.log.truncate(valid);
        self.byte_len = off;
        let mut state = BTreeMap::new();
        let mut pending: Vec<Rec> = Vec::new();
        for r in &self.log {
            if r.op == OP_COMMIT {
                for p in pending.drain(..) {
                    apply(&mut state, &p);
                }
            } else {
                pending.push(r.clone());
            }
        }
        self.live = state;
    }
}

/// Drive one scripted record through the student API and the model together.
fn drive(w: &mut Wal, model: &mut Model, rec: &Rec) {
    match rec.op {
        OP_PUT => w.put(&rec.key, &rec.val),
        OP_DEL => w.delete(&rec.key),
        _ => {
            w.commit_tick();
        }
    }
    model.push(rec.clone());
}

/// Remember every key the script ever wrote (first-appearance order).
fn note(universe: &mut Vec<String>, key: &str) {
    if !key.is_empty() && !universe.iter().any(|k| k == key) {
        universe.push(key.to_string());
    }
}

/* ------------------------- harness toolbox -------------------------- */

/// The harness's own walk of the durable file — spans, checksums, and LSN
/// continuity per the pinned format. Runs only where the log must be
/// healthy (before the harness itself tears it), so any Err here is the
/// encoder's confession. Bounded: a runaway log fails the check instead of
/// hanging the suite.
fn walk(bytes: &[u8]) -> Result<Vec<(usize, usize)>, String> {
    const MAX_RECORDS: usize = 10_000;
    let mut spans = Vec::new();
    let mut off = 0usize;
    while off < bytes.len() {
        if spans.len() >= MAX_RECORDS {
            return Err(format!("more than {MAX_RECORDS} records in the log — the harness refuses to walk further (a runaway append?)"));
        }
        let want_lsn = spans.len() as u64 + 1;
        if off + REC_HEADER + REC_CRC > bytes.len() {
            return Err(format!("offset {off}: {} trailing byte(s) after the last full record — not even a header + checksum", bytes.len() - off));
        }
        let lsn = u64::from_le_bytes(bytes[off..off + 8].try_into().unwrap());
        let op = bytes[off + 8];
        let klen = u16::from_le_bytes(bytes[off + 9..off + 11].try_into().unwrap()) as usize;
        let vlen = u16::from_le_bytes(bytes[off + 11..off + 13].try_into().unwrap()) as usize;
        let end = off + REC_HEADER + klen + vlen + REC_CRC;
        if end > bytes.len() {
            return Err(format!("record at offset {off} (lsn {lsn}) claims klen {klen} + vlen {vlen} — runs past the end of the {}-byte log; check the encoder's length fields", bytes.len()));
        }
        let stored = u32::from_le_bytes(bytes[end - REC_CRC..end].try_into().unwrap());
        let computed = crc32(&bytes[off..end - REC_CRC]);
        if stored != computed {
            return Err(format!("record at offset {off} (lsn {lsn}) stores crc {stored:#010x} but its bytes hash to {computed:#010x} — crc32 over every preceding byte of the record, nothing else"));
        }
        if lsn != want_lsn {
            return Err(format!("record at offset {off} carries lsn {lsn} but sits in position {want_lsn} — LSNs run 1, 2, 3… and a crash rebuilds the high-water mark from the log, not from zero"));
        }
        if op != OP_PUT && op != OP_DEL && op != OP_COMMIT {
            return Err(format!("record at offset {off} (lsn {lsn}) has op byte {op} — OP_PUT, OP_DEL or OP_COMMIT"));
        }
        spans.push((off, end));
        off = end;
    }
    Ok(spans)
}

/// The log must hold exactly the model's records — same byte length, same
/// count, same spans. A disagreement is an encoder bug, named as such.
/// Ok carries the record spans for the caller's tear-point arithmetic.
fn log_agrees(w: &Wal, model: &Model, ctx: &str) -> Result<Vec<(usize, usize)>, String> {
    if w.disk.bytes.len() != model.byte_len {
        return Err(format!("{ctx}: the disk holds {} bytes but the {} scripted records need {} — bytes are missing (or invented)", w.disk.bytes.len(), model.log.len(), model.byte_len));
    }
    let spans = walk(&w.disk.bytes).map_err(|e| format!("{ctx}: {e}"))?;
    if spans.len() != model.log.len() {
        return Err(format!("{ctx}: {} records on the disk, {} scripted — one disk.append per record", spans.len(), model.log.len()));
    }
    for (i, (&(s, e), r)) in spans.iter().zip(model.log.iter()).enumerate() {
        if e - s != r.len() {
            return Err(format!("{ctx}: record {} ({}) spans {} bytes on disk, the format says {} — the length fields are the contract", i + 1, r.desc(), e - s, r.len()));
        }
    }
    Ok(spans)
}

/// Full-state comparison over every key the script ever wrote.
fn state_diff(w: &Wal, want: &BTreeMap<String, String>, universe: &[String]) -> Option<String> {
    for k in universe {
        let (got, want) = (w.get(k), want.get(k).map(String::as_str));
        if got != want {
            return Some(format!("key {k}: recovered {got:?}, the committed prefix says {want:?}"));
        }
    }
    if w.store.len() != want.len() {
        return Some(format!("the state holds {} keys, the committed prefix holds {} — phantoms or losses", w.store.len(), want.len()));
    }
    None
}

/* ------------------------------ checks ------------------------------ */

/// 1. log_first: an instrumented ordering probe. A scripted put/delete/
///    commit sequence runs against the analyzer tape — any state apply that
///    precedes its record's durable flush breaks the WAL rule and fails.
pub fn check_log_first() -> Check {
    const ID: &str = "log_first";
    const LABEL: &str = "state never changes before its log record is durable";
    let mut w = Wal::new();
    if w.get("ghost").is_some() {
        return Check::fail(ID, LABEL, "a fresh Wal answers Some for a key that was never written");
    }
    // six scripted ops; the records they produce must be LSNs 1..=6
    let script = [
        Rec::put("alpha", "1"),
        Rec::put("beta", "2"),
        Rec::del("alpha"),
        Rec::commit(),
        Rec::put("gamma", "3"),
        Rec::commit(),
    ];
    for (i, rec) in script.iter().enumerate() {
        let lsn = i as u64 + 1;
        match rec.op {
            OP_PUT => {
                w.put(&rec.key, &rec.val);
                if w.get(&rec.key) != Some(rec.val.as_str()) {
                    return Check::fail(ID, LABEL, format!("op {i} ({}): get({}) = {:?} right after put returned — apply to the state before you return", rec.desc(), rec.key, w.get(&rec.key)));
                }
            }
            OP_DEL => {
                w.delete(&rec.key);
                if w.get(&rec.key).is_some() {
                    return Check::fail(ID, LABEL, format!("op {i} ({}): get({}) still answers Some after delete returned", rec.desc(), rec.key));
                }
            }
            _ => {
                let got = w.commit_tick();
                if got != lsn {
                    return Check::fail(ID, LABEL, format!("op {i} (commit): commit_tick() returned {got} — the commit record is lsn {lsn} (numbered from 1, +1 per record)"));
                }
            }
        }
    }
    // the analyzer tape: every Applied must FOLLOW its record's Flushed
    let tape = w.disk.events();
    let mut flushed: BTreeMap<u64, usize> = BTreeMap::new();
    let mut applied: BTreeMap<u64, usize> = BTreeMap::new();
    let mut last_flushed = 0u64;
    for (idx, ev) in tape.iter().enumerate() {
        match *ev {
            Event::Flushed(l) => {
                if !(1..=script.len() as u64).contains(&l) {
                    return Check::fail(ID, LABEL, format!("event #{idx}: Flushed(lsn {l}) — a {}-op script produces exactly LSNs 1..={}, one disk.append per record", script.len(), script.len()));
                }
                if flushed.insert(l, idx).is_some() {
                    return Check::fail(ID, LABEL, format!("event #{idx}: lsn {l} flushed twice — one disk.append per record"));
                }
                if l <= last_flushed {
                    return Check::fail(ID, LABEL, format!("event #{idx}: lsn {l} flushed after lsn {last_flushed} — records reach the disk in lsn order"));
                }
                last_flushed = l;
            }
            Event::Applied(l) => {
                if applied.insert(l, idx).is_some() {
                    return Check::fail(ID, LABEL, format!("event #{idx}: lsn {l} applied twice"));
                }
            }
            Event::Crashed => {
                return Check::fail(ID, LABEL, format!("event #{idx}: a crash in the middle of a clean run — put/delete/commit_tick must not drop the state"));
            }
        }
    }
    for (i, rec) in script.iter().enumerate() {
        let l = i as u64 + 1;
        let Some(&f) = flushed.get(&l) else {
            return Check::fail(ID, LABEL, format!("op {i} ({}): no Flushed event for lsn {l} — the record must reach the disk INSIDE the op, not someday", rec.desc()));
        };
        match (rec.op, applied.get(&l)) {
            (OP_COMMIT, Some(_)) => {
                return Check::fail(ID, LABEL, format!("lsn {l} is a commit record — there is no state to apply"));
            }
            (OP_COMMIT, None) => {}
            (_, None) => {
                return Check::fail(ID, LABEL, format!("op {i} ({}): lsn {l} was flushed but never applied — get() answered, so apply through self.store and the analyzer sees it", rec.desc()));
            }
            (_, Some(&a)) => {
                if a < f {
                    return Check::fail(ID, LABEL, format!("op {i} ({}): lsn {l} changed the state (event #{a}) BEFORE its record was durable (event #{f}) — the WAL rule is the other way around: append, flush, THEN apply", rec.desc()));
                }
            }
        }
    }
    Check::pass(ID, LABEL, "every state change followed its durable record; LSNs 1..=6 in order; commits carry no apply")
}

/// 2. checksum_corruption: one payload byte of a historical record is
///    flipped after death; recovery must detect it via the checksum and
///    stop cleanly at that record — the committed prefix before it stands,
///    it and everything after it drops, and nobody panics. Then the
///    truncated log must take new records and survive a second death.
pub fn check_checksum_corruption() -> Check {
    const ID: &str = "checksum_corruption";
    const LABEL: &str = "torn/corrupt tail records detected and dropped";
    let mut w = Wal::new();
    let mut model = Model::new();
    let mut universe: Vec<String> = Vec::new();
    // six single-put transactions; txn i's put is record 2i-2 (0-based)
    for i in 1..=6 {
        let (k, v) = (format!("k{i}"), format!("v{i}"));
        drive(&mut w, &mut model, &Rec::put(&k, &v));
        drive(&mut w, &mut model, &Rec::commit());
        universe.push(k);
    }
    let spans = match log_agrees(&w, &model, "before the corruption") {
        Ok(s) => s,
        Err(e) => return Check::fail(ID, LABEL, e),
    };
    // flip ONE byte inside the payload of txn 3's put (record index 4, lsn 5)
    let (rec_off, _) = spans[4];
    let klen = u16::from_le_bytes(w.disk.bytes[rec_off + 9..rec_off + 11].try_into().unwrap()) as usize;
    let flip_at = rec_off + REC_HEADER + klen; // the value's first byte
    w.crash();
    w.disk.bytes[flip_at] ^= 0xFF;
    w.recover();
    model.crash_at(rec_off); // record 4 and everything after it are forfeit
    if let Some(d) = state_diff(&w, &model.live, &universe) {
        return Check::fail(ID, LABEL, format!("bit-flip at byte {flip_at} (inside lsn 5's payload): {d} — the checksum must catch it and STOP: committed work before the record stands, it and everything after drops; no panic, no salvage"));
    }
    if w.disk.bytes.len() != rec_off {
        return Check::fail(ID, LABEL, format!("bit-flip at byte {flip_at}: after recovery the log is {} bytes but the corrupt record sits at offset {rec_off} — recover() truncates after the last valid record, or future records land behind a hole", w.disk.bytes.len()));
    }
    // the truncated log must take new records and survive a second death
    drive(&mut w, &mut model, &Rec::put("k7", "v7"));
    universe.push("k7".to_string());
    let got = w.commit_tick();
    model.push(Rec::commit());
    if got != 6 {
        return Check::fail(ID, LABEL, format!("the first commit after recovery is lsn {got}, want 6 — the valid prefix ends at lsn 4, so the high-water mark rebuilds to 5 (a truncated lsn is legally reused)"));
    }
    w.crash();
    model.crash_at(model.byte_len); // clean this time
    w.recover();
    if let Some(d) = state_diff(&w, &model.live, &universe) {
        return Check::fail(ID, LABEL, format!("second death on the reused log: {d}"));
    }
    Check::pass(ID, LABEL, "one flipped payload byte caught by the checksum; the tail dropped cleanly and the truncated log took new records")
}

/// 3. replay_idempotent: recover() twice (and three times) must leave a
///    byte-identical state, and recover() on an uncorrupted log after a
///    clean death changes nothing. An uncommitted tail dies — and repeated
///    replays must not resurrect it.
pub fn check_replay_idempotent() -> Check {
    const ID: &str = "replay_idempotent";
    const LABEL: &str = "replaying the log twice changes nothing";
    let mut w = Wal::new();
    let mut model = Model::new();
    let mut universe: Vec<String> = Vec::new();
    // a committed history: puts, deletes, re-puts, multi-op transactions
    let script = [
        Rec::put("a", "1"), Rec::put("b", "2"), Rec::commit(),
        Rec::put("c", "3"), Rec::del("a"), Rec::commit(),
        Rec::put("a", "9"), Rec::commit(),
    ];
    for rec in &script {
        drive(&mut w, &mut model, rec);
        note(&mut universe, &rec.key);
    }
    // death on an uncorrupted log: recovery rebuilds exactly the live state
    let want = model.live.clone();
    w.crash();
    w.recover();
    model.crash_at(model.byte_len);
    if let Some(d) = state_diff(&w, &want, &universe) {
        return Check::fail(ID, LABEL, format!("clean death: {d} — replaying an intact log must rebuild exactly the committed state"));
    }
    let log_len = w.disk.bytes.len();
    for round in 2..=3 {
        w.recover();
        if let Some(d) = state_diff(&w, &want, &universe) {
            return Check::fail(ID, LABEL, format!("recover() round {round}: {d} — replay is idempotent: applying applied work changes nothing"));
        }
        if w.disk.bytes.len() != log_len {
            return Check::fail(ID, LABEL, format!("recover() round {round}: the log changed length ({log_len} → {}) — recovery READS the log; its only write is truncating the torn tail, and there is none here", w.disk.bytes.len()));
        }
    }
    // an uncommitted tail dies with the process — and stays dead
    for rec in [Rec::put("x", "1"), Rec::put("y", "2")] {
        drive(&mut w, &mut model, &rec);
        note(&mut universe, &rec.key);
    }
    w.crash();
    model.crash_at(model.byte_len); // no tear — the tail is simply uncommitted
    w.recover();
    if let Some(d) = state_diff(&w, &model.live, &universe) {
        return Check::fail(ID, LABEL, format!("uncommitted tail: {d} — x and y were never committed, recovery must not resurrect them"));
    }
    w.recover();
    if let Some(d) = state_diff(&w, &model.live, &universe) {
        return Check::fail(ID, LABEL, format!("uncommitted tail, second replay: {d}"));
    }
    Check::pass(ID, LABEL, "three replays of an intact log plus two over an uncommitted tail — the state never moves")
}

/// 4. committed_durable: a seeded script of puts/deletes/commits, killed at
///    seeded op indices with seeded tears — mid-flush of the last record,
///    deep in the file, at a commit boundary, total loss. Recovery must
///    leave EXACTLY the committed prefix applied: nothing uncommitted
///    leaks, nothing committed is lost.
pub fn check_committed_durable() -> Check {
    const ID: &str = "committed_durable";
    const LABEL: &str = "kill mid-flush: every committed write survives recovery";
    // the base script: ten seeded transactions over a small key universe
    let mut rng = Rng(0xDA7A_0004);
    let mut script: Vec<Rec> = Vec::new();
    for _ in 0..10 {
        for _ in 0..1 + rng.below(3) {
            let k = format!("k{:02}", rng.below(12));
            if rng.below(4) == 0 {
                script.push(Rec::del(&k));
            } else {
                script.push(Rec::put(&k, &format!("v{}", rng.next() % 1000)));
            }
        }
        script.push(Rec::commit());
    }
    let universe: Vec<String> = (0..12).map(|i| format!("k{i:02}")).collect();
    // twelve seeded kill points: die after op `at`, tear the log per style
    let mut kill_rng = Rng(0xDA7A_0005);
    for kill in 0..12 {
        let at = kill_rng.below(script.len());
        let style = kill_rng.below(100);
        let mut w = Wal::new();
        let mut model = Model::new();
        for rec in &script[..=at] {
            drive(&mut w, &mut model, rec);
        }
        let spans = match log_agrees(&w, &model, &format!("kill #{kill}")) {
            Ok(s) => s,
            Err(e) => return Check::fail(ID, LABEL, e),
        };
        let byte_len = model.byte_len;
        let cut = match style {
            0..=24 => byte_len, // a clean death — nothing torn
            25..=54 => {
                // mid-flush of the LAST record: some bytes landed, none count
                let (s, e) = spans[spans.len() - 1];
                s + 1 + kill_rng.below(e - s - 1)
            }
            55..=79 => {
                // a tear deep in the file: everything after it is forfeit
                let (s, e) = spans[kill_rng.below(spans.len())];
                s + 1 + kill_rng.below(e - s - 1)
            }
            80..=89 => {
                // right after the last commit boundary before the kill
                match (0..=at).rev().find(|&i| script[i].op == OP_COMMIT) {
                    Some(i) => spans[i].1,
                    None => 0,
                }
            }
            _ => 0, // total loss: the file itself is gone
        };
        w.crash();
        w.disk.bytes.truncate(cut);
        w.recover();
        model.crash_at(cut);
        let ctx = format!("kill #{kill}: died after op {at} (lsn {}, {}), log torn at byte {cut} of {byte_len}", at + 1, script[at].desc());
        if w.disk.bytes.len() != model.byte_len {
            return Check::fail(ID, LABEL, format!("{ctx}: recover() left the log at {} bytes, the valid prefix is {} — truncate past the last valid record, or future writes land behind a hole", w.disk.bytes.len(), model.byte_len));
        }
        if let Some(d) = state_diff(&w, &model.live, &universe) {
            return Check::fail(ID, LABEL, format!("{ctx}: {d}"));
        }
    }
    Check::pass(ID, LABEL, format!("12 kills across a {}-op script — mid-record, mid-file, at commit boundaries, total loss: the recovered state is always exactly the committed prefix", script.len()))
}

/// 5. crash_storm: 40 seeded crashes at random op indices across a 600-op
///    workload, with random tear points including mid-record tails. After
///    every crash+recover the state must equal the reference model's
///    committed-prefix replay — and the run then continues on the truncated
///    log. Any divergence names the crash #, the op, and the first key.
pub fn check_crash_storm() -> Check {
    const ID: &str = "crash_storm";
    const LABEL: &str = "random crash points vs a reference model";
    const OPS: usize = 600;
    const CRASHES: usize = 40;
    const KEYS: usize = 64;
    let mut rng = Rng(0xCA51_0005);
    // the workload, seeded up front so every crash lands on a known op
    let mut script: Vec<Rec> = Vec::with_capacity(OPS);
    for _ in 0..OPS {
        let k = format!("k{:02}", rng.below(KEYS));
        match rng.below(100) {
            0..=54 => script.push(Rec::put(&k, &format!("v{}", rng.next() % 10_000))),
            55..=79 => script.push(Rec::del(&k)),
            _ => script.push(Rec::commit()),
        }
    }
    // the crash schedule: op index -> tear seed, drawn before the run
    let mut crashes: BTreeMap<usize, u64> = BTreeMap::new();
    while crashes.len() < CRASHES {
        crashes.insert(rng.below(OPS), rng.next());
    }
    let universe: Vec<String> = (0..KEYS).map(|i| format!("k{i:02}")).collect();
    let mut w = Wal::new();
    let mut model = Model::new();
    let mut n_crashes = 0usize;
    for (i, rec) in script.iter().enumerate() {
        drive(&mut w, &mut model, rec);
        if i % 137 == 0 {
            // live-view spot check: get() reflects every op as it happens
            let k = format!("k{:02}", (i * 7) % KEYS);
            let (got, want) = (w.get(&k), model.live.get(&k).map(String::as_str));
            if got != want {
                return Check::fail(ID, LABEL, format!("op {i} ({}): get({k}) = {got:?} but the op stream says {want:?} — every op applies before it returns", rec.desc()));
            }
        }
        let Some(&seed) = crashes.get(&i) else { continue };
        let mut crng = Rng(seed ^ 0xC0FF_EE00_0000_0000);
        n_crashes += 1;
        let ctx = format!("crash #{n_crashes} (after op {i}, {})", rec.desc());
        let spans = match log_agrees(&w, &model, &ctx) {
            Ok(s) => s,
            Err(e) => return Check::fail(ID, LABEL, e),
        };
        let byte_len = model.byte_len;
        let cut = match crng.below(100) {
            0..=19 => byte_len, // clean death
            20..=49 => {
                // torn mid-flush of the last record
                let (s, e) = spans[spans.len() - 1];
                s + 1 + crng.below(e - s - 1)
            }
            50..=79 => {
                // torn at a random record deep in the file
                let (s, e) = spans[crng.below(spans.len())];
                s + 1 + crng.below(e - s - 1)
            }
            80..=89 => {
                // right after the last commit boundary
                match model.log.iter().rposition(|r| r.op == OP_COMMIT) {
                    Some(idx) => spans[idx].1,
                    None => byte_len,
                }
            }
            _ => 0, // total loss
        };
        w.crash();
        w.disk.bytes.truncate(cut);
        w.recover();
        model.crash_at(cut);
        if w.disk.bytes.len() != model.byte_len {
            return Check::fail(ID, LABEL, format!("{ctx}, torn at byte {cut} of {byte_len}: recover() left the log at {} bytes, the valid prefix is {} — truncate past the last valid record", w.disk.bytes.len(), model.byte_len));
        }
        if let Some(d) = state_diff(&w, &model.live, &universe) {
            return Check::fail(ID, LABEL, format!("{ctx}, torn at byte {cut} of {byte_len}: {d}"));
        }
    }
    Check::pass(ID, LABEL, format!("{OPS} ops, {CRASHES} seeded deaths with mid-record tears — every recovery replays the committed prefix exactly"))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_log_first(),
        check_checksum_corruption(),
        check_replay_idempotent(),
        check_committed_durable(),
        check_crash_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "wal", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
