//! buffer-pool — forge lab 07 (tablespace).
//!
//! The engine's pulse: a buffer pool — frames, a page table, pins, dirty
//! bits — fronted by an LRU-K replacer. CMU 15-445 opens with this project;
//! we grade the O'Neil semantics to the unit: backward k-distance, the +∞
//! rule for under-historied pages, pins as untouchable, writebacks counted
//! exactly.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/pool.rs        (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The ops: fetch / unpin / flush, plus frame_page and frame_content — the
//! checkers' windows into your page table and frames. The hard parts:
//!   * LRU-K victim selection: pages with fewer than K=2 touches have
//!     backward k-distance +∞ and die ahead of EVERY fully-historied page;
//!     among the +∞s the oldest last-touch dies first; among the rest the
//!     oldest 2nd-most-recent touch dies first.
//!   * a pinned frame is never a victim — when all frames are pinned,
//!     fetch returns Err(PoolExhausted) instead of evicting;
//!   * dirty writebacks counted to the unit: on eviction, on flush, and
//!     never twice for the same bytes.

mod pool;

use kslab::{Check, Report};
use pool::{page_image, BufferPool, FetchError, NUM_PAGES, PAGE_BYTES};
use std::collections::{BTreeMap, BTreeSet};

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* --------------------------- the disk ------------------------------- */

/// The harness's own copy of the storage device — the same arithmetic as
/// the given `page_image` in pool.rs, kept independent so the fetch_pin
/// check can tell "your pool loads the right bytes" from "you edited the
/// disk".
fn disk_image(page: u32) -> [u8; PAGE_BYTES] {
    let mut img = [0u8; PAGE_BYTES];
    let mut s = (page as u64).wrapping_mul(0x9E37_79B9_7F4A_7C15);
    for chunk in img.chunks_mut(8) {
        s = s.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = s;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^= z >> 31;
        chunk.copy_from_slice(&z.to_le_bytes());
    }
    img
}

/* ------------------------- reference pool --------------------------- */

/// The contract from pool.rs, kept by the harness. The storm check runs
/// your pool and this one through the same seeded trace and demands the
/// same resident set and the same four counters after every event.
struct RefFrame {
    page: Option<u32>,
    pin: u32,
    dirty: bool,
}

struct RefPool {
    frames: Vec<RefFrame>,
    table: BTreeMap<u32, usize>,
    /// page -> (2nd-most-recent touch, most-recent touch); survives eviction
    hist: BTreeMap<u32, (Option<u64>, Option<u64>)>,
    clock: u64,
    hits: u64,
    reads: u64,
    writes: u64,
    evictions: u64,
}

impl RefPool {
    fn new(frames: usize) -> RefPool {
        RefPool {
            frames: (0..frames).map(|_| RefFrame { page: None, pin: 0, dirty: false }).collect(),
            table: BTreeMap::new(),
            hist: BTreeMap::new(),
            clock: 0,
            hits: 0,
            reads: 0,
            writes: 0,
            evictions: 0,
        }
    }

    fn fetch(&mut self, page: u32) -> Result<usize, ()> {
        // every fetch call is a touch — hit, miss, or refused
        self.clock += 1;
        let h = self.hist.entry(page).or_insert((None, None));
        h.0 = h.1;
        h.1 = Some(self.clock);

        if let Some(&f) = self.table.get(&page) {
            self.frames[f].pin += 1;
            self.hits += 1;
            return Ok(f);
        }
        let f = if let Some(f) = self.frames.iter().position(|fr| fr.page.is_none()) {
            f
        } else {
            let v = self.victim().ok_or(())?;
            let fr = &mut self.frames[v];
            let old = match fr.page {
                Some(p) => p,
                None => return Err(()), // unreachable: a victim always holds a page
            };
            if fr.dirty {
                self.writes += 1;
            }
            fr.dirty = false;
            self.table.remove(&old);
            self.evictions += 1;
            v
        };
        self.reads += 1;
        self.frames[f] = RefFrame { page: Some(page), pin: 1, dirty: false };
        self.table.insert(page, f);
        Ok(f)
    }

    /// The LRU-K victim: among UNPINNED frames, the page whose backward
    /// 2-distance is largest. Fewer than K=2 touches → +∞, ahead of every
    /// finite distance; among +∞s the oldest LAST touch dies first; among
    /// finites the oldest 2nd-most-recent touch dies first. Timestamps are
    /// unique (one touch per clock tick), so the order is total.
    fn victim(&self) -> Option<usize> {
        let mut best: Option<((u8, u64), usize)> = None;
        for (i, fr) in self.frames.iter().enumerate() {
            let page = match fr.page {
                Some(p) if fr.pin == 0 => p,
                _ => continue,
            };
            let &(prev, last) = self.hist.get(&page).unwrap_or(&(None, None));
            let key = match prev {
                None => (0u8, last.unwrap_or(0)), // +∞ class: oldest last touch
                Some(p) => (1u8, p),              // finite class: oldest kth touch
            };
            let better = match best {
                None => true,
                Some((bk, _)) => key < bk,
            };
            if better {
                best = Some((key, i));
            }
        }
        best.map(|(_, i)| i)
    }

    fn unpin(&mut self, page: u32, dirty: bool) -> bool {
        let f = match self.table.get(&page) {
            Some(&f) => f,
            None => return false,
        };
        let fr = &mut self.frames[f];
        if fr.pin == 0 {
            return false;
        }
        fr.pin -= 1;
        if dirty {
            fr.dirty = true;
        }
        true
    }

    fn flush(&mut self, page: u32) -> bool {
        let f = match self.table.get(&page) {
            Some(&f) => f,
            None => return false,
        };
        let fr = &mut self.frames[f];
        if fr.dirty {
            self.writes += 1;
            fr.dirty = false;
        }
        true
    }

    fn resident(&self) -> BTreeSet<u32> {
        self.frames.iter().filter_map(|fr| fr.page).collect()
    }
}

fn rf_touch(rf: &mut RefPool, page: u32) {
    if rf.fetch(page).is_ok() {
        rf.unpin(page, false);
    }
}

/* ----------------------------- helpers ------------------------------ */

fn verdict(id: &'static str, label: &'static str, r: Result<String, String>) -> Check {
    match r {
        Ok(m) => Check::pass(id, label, m),
        Err(m) => Check::fail(id, label, m),
    }
}

/// One reference with no lasting borrow: fetch + clean unpin.
fn touch(p: &mut BufferPool, page: u32) -> Result<(), String> {
    p.fetch(page).map_err(|_| {
        format!("fetch({page}) returned PoolExhausted — this script always leaves an unpinned frame, so a correct pool never refuses here")
    })?;
    if !p.unpin(page, false) {
        return Err(format!(
            "unpin({page}) right after a successful fetch returned false — a fresh fetch leaves the frame pinned once, so the release must succeed"
        ));
    }
    Ok(())
}

fn resident_set(p: &BufferPool, frames: usize) -> BTreeSet<u32> {
    (0..frames).filter_map(|f| p.frame_page(f)).collect()
}

/// Assert the pool's resident set, with a message that names the page that
/// should have died (or lived) and why.
fn want_resident(p: &BufferPool, frames: usize, want: &[u32], ctx: &str) -> Result<(), String> {
    let got = resident_set(p, frames);
    let w: BTreeSet<u32> = want.iter().copied().collect();
    if got != w {
        let gone: Vec<u32> = w.difference(&got).copied().collect();
        let kept: Vec<u32> = got.difference(&w).copied().collect();
        return Err(format!(
            "{ctx}: the pool holds {got:?}, want {want:?} (wrongly evicted {gone:?}, wrongly kept {kept:?})"
        ));
    }
    Ok(())
}

/* ------------------------------ checks ------------------------------ */

/// 1. fetch_pin: fetch loads and pins, a hit re-pins the same frame, unpin
///    releases exactly once, a stranger's unpin/flush is refused — and when
///    every frame is pinned, fetch fails with PoolExhausted instead of
///    evicting a pinned frame. Content is diffed against the harness's disk.
pub fn check_fetch_pin() -> Check {
    const ID: &str = "fetch_pin";
    const LABEL: &str = "fetch pins, unpin releases, a pinned frame is never evicted";
    verdict(ID, LABEL, fetch_pin_run())
}

fn fetch_pin_run() -> Result<String, String> {
    // the disk is given, not negotiable
    for pg in [0u32, 9, 255, 511] {
        if page_image(pg) != disk_image(pg) {
            return Err(format!(
                "page_image({pg}) does not match the harness's disk — the given page_image() at the top of pool.rs is not yours to edit"
            ));
        }
    }
    let mut p = BufferPool::new(4);
    if (p.hits(), p.reads(), p.writes(), p.evictions()) != (0, 0, 0, 0) {
        return Err("a fresh pool's four counters must all be zero".into());
    }

    // miss: load, pin, count the read
    let f7 = p
        .fetch(7)
        .map_err(|_| "fetch(7) on an EMPTY pool returned PoolExhausted — that error exists only for a full pool of pinned frames".to_string())?;
    if (p.hits(), p.reads()) != (0, 1) {
        return Err(format!("first fetch(7) is a miss: hits must be 0, reads 1 — got hits {} reads {}", p.hits(), p.reads()));
    }
    if p.frame_page(f7) != Some(7) {
        return Err(format!("fetch(7) returned frame {f7}, but frame_page({f7}) says {:?} — the page table must map the frame back to page 7", p.frame_page(f7)));
    }
    if p.frame_content(f7) != Some(&disk_image(7)) {
        return Err(format!("frame {f7} holds page 7 but its bytes are not the disk's — a miss must load page_image(page) into the frame"));
    }
    if p.frame_page(999).is_some() || p.frame_content(999).is_some() {
        return Err("frame 999 does not exist — out-of-range frame probes must answer None, never panic or invent".into());
    }

    // hit: same frame, second pin, count the hit — no read
    let f7b = p.fetch(7).map_err(|_| "fetch(7) on a resident page refused".to_string())?;
    if f7b != f7 {
        return Err(format!("fetch(7) hit returned frame {f7b}, the page lives in frame {f7} — a hit must hand back the SAME frame"));
    }
    if (p.hits(), p.reads()) != (1, 1) {
        return Err(format!("second fetch(7) is a hit: hits 1, reads 1 — got hits {} reads {}; a hit must not touch the disk", p.hits(), p.reads()));
    }

    // fill the pool: pages 7 (pin 2), 8, 9, 10 (pin 1 each)
    for pg in [8u32, 9, 10] {
        if p.fetch(pg).is_err() {
            return Err(format!("fetch({pg}) refused with empty frames left — fills are not evictions"));
        }
    }
    if (p.reads(), p.evictions()) != (4, 0) {
        return Err(format!("filling 4 empty frames: reads 4, evictions 0 — got reads {} evictions {}; an initial fill is a read but NEVER an eviction", p.reads(), p.evictions()));
    }

    // every frame pinned → fetch must fail, not evict
    match p.fetch(11) {
        Err(FetchError::PoolExhausted) => {}
        Ok(f) => return Err(format!(
            "fetch(11) with all 4 frames pinned returned Ok(frame {f}) — SOMEONE was evicted under a live pin. A pin is a borrow: evicting under it is a use-after-free. The only legal answer is Err(PoolExhausted)")),
    }
    if (p.hits(), p.reads(), p.writes(), p.evictions()) != (1, 4, 0, 0) {
        return Err(format!(
            "a refused fetch must change no counter — after the PoolExhausted: hits 1, reads 4, writes 0, evictions 0; got {}, {}, {}, {}",
            p.hits(), p.reads(), p.writes(), p.evictions()));
    }
    want_resident(&p, 4, &[7, 8, 9, 10], "after the refused fetch(11), every pinned page must still be resident")?;

    // release one frame; the next fetch must take exactly that frame's page
    if !p.unpin(9, false) {
        return Err("unpin(9) on a freshly fetched (pinned) page returned false".into());
    }
    let f11 = p.fetch(11).map_err(|_| "fetch(11) refused with page 9's frame unpinned — one pin-0 frame is all it takes".to_string())?;
    if p.frame_page(f11) != Some(11) || p.frame_content(f11) != Some(&disk_image(11)) {
        return Err("fetch(11) landed but the frame does not hold page 11's bytes".into());
    }
    want_resident(&p, 4, &[7, 8, 10, 11], "page 9 held the pool's only pin-0 frame — it was the only legal victim, whatever its history says")?;
    if (p.reads(), p.evictions()) != (5, 1) {
        return Err(format!("the one legal eviction: reads 5, evictions 1 — got reads {} evictions {}", p.reads(), p.evictions()));
    }

    // unpin is exact: two pins take two releases; the third is refused
    if !p.unpin(7, false) || !p.unpin(7, false) {
        return Err("page 7 was fetched twice (pin 2) — two unpins must both succeed".into());
    }
    if p.unpin(7, false) {
        return Err("a third unpin(7) succeeded with pin already 0 — a double release is a caller bug you must refuse (false), not absorb into a negative pin".into());
    }
    if p.unpin(42, false) {
        return Err("unpin(42): page 42 has never been resident — a stranger's unpin must return false and change nothing".into());
    }
    for pg in [8u32, 10, 11] {
        if !p.unpin(pg, false) {
            return Err(format!("unpin({pg}) on a pinned resident page returned false"));
        }
    }

    // the page table must never lie about residency, in either direction
    let h0 = p.hits();
    if p.fetch(7).is_err() {
        return Err("fetch(7) refused — page 7 is resident and unpinned".into());
    }
    if p.hits() != h0 + 1 {
        return Err("fetch(7) with page 7 resident must count as a hit".into());
    }
    let r0 = p.reads();
    if p.fetch(9).is_err() {
        return Err("fetch(9) refused — frames are unpinned".into());
    }
    if p.reads() != r0 + 1 {
        return Err("fetch(9) after page 9 was evicted must count a disk read — an evicted page is GONE from the page table".into());
    }
    // histories now: 7 finite, 8 ∞ (t3), 10 ∞ (t5), 11 finite — 8 dies first
    want_resident(&p, 4, &[7, 9, 10, 11], "fetch(9) evicted the wrong page — 8 and 10 are one-touch (+∞), and 8's touch is the older of the two")?;
    if (p.hits(), p.reads(), p.writes(), p.evictions()) != (2, 6, 0, 2) {
        return Err(format!(
            "final counters: hits 2, reads 6, writes 0, evictions 2 — got {}, {}, {}, {}",
            p.hits(), p.reads(), p.writes(), p.evictions()));
    }
    Ok("pins held under pressure (PoolExhausted, never a pinned eviction); releases exact; content byte-exact against the disk".into())
}

/// 2. evict_order: scripted touch sequences whose LRU-K victims are known to
///    the unit — the +∞ rule, FIFO among the +∞s, a finite contest where
///    last-touch order and kth-touch order disagree (LRU's blind spot), and
///    pins outranking every distance.
pub fn check_evict_order() -> Check {
    const ID: &str = "evict_order";
    const LABEL: &str = "LRU-K picks the true backward-k-distance victim";
    verdict(ID, LABEL, evict_order_run())
}

fn evict_order_run() -> Result<String, String> {
    // Scenario 1 — the lesson's quiz, verbatim: A touched at 1,2; B at 3;
    // C at 4,5; pool full. B is the only one-touch page: +∞, dies first —
    // even though A's LAST touch (t=2) is the oldest in the pool.
    let mut p = BufferPool::new(3);
    touch(&mut p, 1)?; // t1
    touch(&mut p, 1)?; // t2  — A: [1, 2]
    touch(&mut p, 2)?; // t3  — B: [3]
    touch(&mut p, 3)?; // t4
    touch(&mut p, 3)?; // t5  — C: [4, 5]
    touch(&mut p, 4)?; // t6  — the eviction under test
    want_resident(
        &p, 3, &[1, 3, 4],
        "scenario 1, fetch(4): page 2 (touched once, at t=3) has backward 2-distance +∞ and must die — page 1's LAST touch (t=2) being older is irrelevant; if page 1 is gone, you ranked by last touch, and that is plain LRU",
    )?;
    if p.evictions() != 1 {
        return Err(format!("scenario 1: exactly one eviction so far, got {}", p.evictions()));
    }

    // Scenario 2 — among the +∞s, the oldest LAST touch dies first: a pool
    // of one-touch pages drains FIFO.
    let mut p = BufferPool::new(3);
    touch(&mut p, 10)?; // t1
    touch(&mut p, 11)?; // t2
    touch(&mut p, 12)?; // t3
    touch(&mut p, 13)?; // t4 — victim must be 10
    want_resident(&p, 3, &[11, 12, 13], "scenario 2, fetch(13): three one-touch pages are all +∞ — the oldest touch (page 10, t=1) dies first; one-touch pages drain FIFO")?;
    touch(&mut p, 14)?; // t5 — victim must be 11
    want_resident(&p, 3, &[12, 13, 14], "scenario 2, fetch(14): page 11 (t=2) is now the oldest one-touch page")?;

    // Scenario 3 — the finite contest where LRU and LRU-2 disagree.
    let mut p = BufferPool::new(3);
    touch(&mut p, 1)?; // t1
    touch(&mut p, 2)?; // t2
    touch(&mut p, 3)?; // t3
    touch(&mut p, 2)?; // t4 — 2: [2, 4]
    touch(&mut p, 1)?; // t5 — 1: [1, 5]
    touch(&mut p, 4)?; // t6 — victim: 3, the only +∞ page
    want_resident(&p, 3, &[1, 2, 4], "scenario 3, fetch(4): page 3 is the only one-touch page (+∞) and dies ahead of both fully-historied pages")?;
    touch(&mut p, 4)?; // t7 — 4: [6, 7]
    touch(&mut p, 5)?; // t8 — victim: 1 (2nd-most-recent t=1 is the oldest)
    want_resident(
        &p, 3, &[2, 4, 5],
        "scenario 3, fetch(5): all three pages have full histories — page 1's 2nd-most-recent touch (t=1) is the oldest previous life, so page 1 dies. Page 2's LAST touch (t=4) is older than page 1's (t=5): if page 2 is gone you ranked by last touch — plain LRU, the exact blind spot LRU-K exists to fix",
    )?;

    // Scenario 4 — a pin outranks every distance.
    let mut p = BufferPool::new(2);
    p.fetch(1).map_err(|_| "fetch(1) on an empty pool refused".to_string())?; // t1 — STAYS PINNED
    touch(&mut p, 2)?; // t2
    p.fetch(3).map_err(|_| "fetch(3) refused — page 2's frame was unpinned, a legal victim".to_string())?; // t3 — victim 2; page 3 STAYS PINNED
    want_resident(&p, 2, &[1, 3], "scenario 4, fetch(3): page 1 is older but PINNED — a pin outranks every k-distance; the only candidate was page 2")?;
    match p.fetch(4) {
        Err(FetchError::PoolExhausted) => {}
        Ok(f) => return Err(format!("scenario 4, fetch(4): page 1 pinned, page 3 just fetched (pinned) — no candidate exists, yet frame {f} was handed out; a pinned frame was evicted")),
    }
    want_resident(&p, 2, &[1, 3], "scenario 4, after the refused fetch(4): nothing may change")?;

    Ok("the +∞ rule, FIFO among +∞s, the finite kth-touch contest, and pins-outrank-distance — all four victims exact".into())
}

/// 3. dirty_writeback: scripted dirtying; evictions write back exactly the
///    dirty victims; unpin(false) never clears a dirty bit; flush-then-evict
///    writes exactly once; reads/writes exact to the unit.
pub fn check_dirty_writeback() -> Check {
    const ID: &str = "dirty_writeback";
    const LABEL: &str = "dirty victim is written back; clean victim is not — counts exact";
    verdict(ID, LABEL, dirty_writeback_run())
}

fn dirty_writeback_run() -> Result<String, String> {
    let mut p = BufferPool::new(3);
    let stats = |p: &BufferPool| (p.hits(), p.reads(), p.writes(), p.evictions());

    touch(&mut p, 1)?; // t1 — clean
    p.fetch(2).map_err(|_| "fetch(2) refused".to_string())?; // t2
    if !p.unpin(2, true) {
        return Err("unpin(2, true) after a fresh fetch must succeed".into());
    }
    // page 2 is dirty. A clean-flag unpin must NOT clear it:
    p.fetch(2).map_err(|_| "fetch(2) hit refused".to_string())?; // t3 — hit
    if !p.unpin(2, false) {
        return Err("unpin(2, false) on a pinned page must succeed".into());
    }
    p.fetch(3).map_err(|_| "fetch(3) refused".to_string())?; // t4
    if !p.unpin(3, true) {
        return Err("unpin(3, true) after a fresh fetch must succeed".into());
    }
    if stats(&p) != (1, 3, 0, 0) {
        return Err(format!("setup: hits 1, reads 3, writes 0, evictions 0 — got {:?}; nothing has been evicted or written back yet", stats(&p)));
    }

    // victim 1: clean — no writeback. (∞ tie: 1's touch t1 < 3's t4)
    touch(&mut p, 4)?; // t5
    if stats(&p) != (1, 4, 0, 1) {
        return Err(format!("fetch(4) evicted page 1, a CLEAN victim: writes must stay 0 — got {:?}; a clean victim is just dropped", stats(&p)));
    }
    want_resident(&p, 3, &[2, 3, 4], "fetch(4): page 1 (∞, oldest touch) was the victim")?;

    // victim 3: dirty — exactly one writeback
    touch(&mut p, 5)?; // t6
    if stats(&p) != (1, 5, 1, 2) {
        return Err(format!("fetch(5) evicted page 3, a DIRTY victim: writes must be 1 — got {:?}; a dirty victim is written back, exactly once", stats(&p)));
    }
    want_resident(&p, 3, &[2, 4, 5], "fetch(5): page 3 (∞, touch t4 < page 4's t5) was the victim")?;

    // flush writes back a dirty page WITHOUT evicting it — and only when dirty
    if !p.flush(2) {
        return Err("flush(2): page 2 is resident — flush must return true".into());
    }
    if stats(&p).2 != 2 {
        return Err(format!("flush(2) on a dirty page: writes must be 2 — got {}. (Page 2 was dirtied at t2 and the unpin(false) at t3 must NOT have cleared it — dirty clears only on writeback.)", stats(&p).2));
    }
    if !p.flush(2) {
        return Err("flush(2) on a resident page must return true, dirty or not".into());
    }
    if stats(&p).2 != 2 {
        return Err(format!("flush(2) a second time: the page is already clean — no write is owed, writes must stay 2, got {}", stats(&p).2));
    }
    if p.flush(77) {
        return Err("flush(77): page 77 is not resident — a stranger's flush must return false".into());
    }
    p.fetch(2).map_err(|_| "fetch(2) refused".to_string())?; // t7 — flush is not an eviction: page 2 must still be here
    if !p.unpin(2, false) {
        return Err("unpin(2) after the hit must succeed".into());
    }
    if stats(&p).0 != 2 {
        return Err(format!("fetch(2) after flush(2) must be a HIT — flush writes back, it does not evict; hits {:?}", stats(&p)));
    }

    // two clean victims: writes never move
    touch(&mut p, 6)?; // t8 — victim 4 (∞: t5)
    p.fetch(7).map_err(|_| "fetch(7) refused".to_string())?; // t9 — victim 5 (∞: t6)
    if !p.unpin(7, true) {
        return Err("unpin(7, true) after a fresh fetch must succeed".into());
    }
    // page 7 is now a ONE-TOUCH dirty page
    if stats(&p) != (2, 7, 2, 4) {
        return Err(format!("two clean evictions (pages 4, 5): hits 2, reads 7, writes 2, evictions 4 — got {:?}", stats(&p)));
    }
    want_resident(&p, 3, &[2, 6, 7], "pages 4 and 5 were the oldest one-touch pages")?;

    // one more clean victim, then page 7 dies dirty: exactly one writeback
    touch(&mut p, 8)?; // t10 — victim 6 (∞: t8 < 7's t9), clean
    touch(&mut p, 9)?; // t11 — victim 7 (∞: t9), DIRTY
    if stats(&p) != (2, 9, 3, 6) {
        return Err(format!(
            "fetch(9) evicted page 7, dirtied on its release and never re-touched: hits 2, reads 9, writes 3, evictions 6 — got {:?}",
            stats(&p)));
    }
    want_resident(&p, 3, &[2, 8, 9], "page 6 (t8) then page 7 (t9) were the oldest one-touch pages")?;

    // Scenario B — flush-then-evict writes exactly once, in a fresh pool
    let mut q = BufferPool::new(2);
    q.fetch(1).map_err(|_| "fetch(1) refused".to_string())?; // t1
    if !q.unpin(1, true) {
        return Err("unpin(1, true) must succeed".into());
    }
    if !q.flush(1) || q.writes() != 1 {
        return Err(format!("flush(1) on a dirty page: one writeback, writes 1 — got {}", q.writes()));
    }
    touch(&mut q, 2)?; // t2
    touch(&mut q, 3)?; // t3 — victim 1 (∞: t1 < t2), flushed-clean
    if q.writes() != 1 {
        return Err(format!("fetch(3) evicted page 1, which was flushed clean: its flush was the ONE writeback, the eviction owes nothing — writes must stay 1, got {}", q.writes()));
    }
    want_resident(&q, 2, &[2, 3], "fetch(3): page 1 (∞, oldest touch) was the victim")?;
    if (q.hits(), q.reads(), q.writes(), q.evictions()) != (0, 3, 1, 1) {
        return Err(format!("scenario B final: hits 0, reads 3, writes 1, evictions 1 — got {:?}", (q.hits(), q.reads(), q.writes(), q.evictions())));
    }

    Ok("dirty victims written back exactly once, clean victims never; unpin(false) never clears dirty; flush-then-evict wrote once".into())
}

/// 4. scan_resistance: a 12-page working set warmed 3× in a 16-frame pool,
///    then a 64-page one-touch flood, then the working set re-touched.
///    LRU-K loses almost nothing; plain LRU scores zero.
pub fn check_scan_resistance() -> Check {
    const ID: &str = "scan_resistance";
    const LABEL: &str = "a one-touch flood does not evict the working set";
    verdict(ID, LABEL, scan_resistance_run())
}

fn scan_resistance_run() -> Result<String, String> {
    const FRAMES: usize = 16;
    const HOT: u32 = 12; // the working set — fits the pool
    const FLOOD: u32 = 64; // 4× the pool, one touch each
    let mut p = BufferPool::new(FRAMES);
    let mut rf = RefPool::new(FRAMES);

    // warm the working set: three full rounds; nothing is ever evicted
    for _ in 0..3 {
        for page in 0..HOT {
            touch(&mut p, page)?;
            rf_touch(&mut rf, page);
        }
    }
    if (p.hits(), p.reads(), p.evictions()) != (24, 12, 0) {
        return Err(format!(
            "warm-up accounting: 3 rounds over {HOT} pages in a {FRAMES}-frame pool — hits 24, reads 12, evictions 0 are policy-free counting; got hits {} reads {} evictions {}",
            p.hits(), p.reads(), p.evictions()));
    }

    // the flood: 64 pages nobody will ever touch again
    for page in 100..100 + FLOOD {
        touch(&mut p, page)?;
        rf_touch(&mut rf, page);
    }
    if (p.reads(), p.evictions()) != (76, 60) {
        return Err(format!(
            "flood accounting: reads must be 76 (12 hot + 64 one-touch), evictions 60 (the first 4 flood pages filled the pool's empty frames — fills are not evictions); got reads {} evictions {}",
            p.reads(), p.evictions()));
    }

    // the verdict: re-touch the whole working set and count the survivors
    let before = p.hits();
    let rbefore = rf.hits;
    for page in 0..HOT {
        touch(&mut p, page)?;
        rf_touch(&mut rf, page);
    }
    let score = p.hits() - before;
    let rscore = rf.hits - rbefore;
    if p.reads() != 76 + (HOT as u64 - score) {
        return Err(format!(
            "accounting after the flood: reads {} but only {score}/{HOT} hot touches hit — every miss is a disk read, so reads must be 76 + ({HOT} − {score})",
            p.reads()));
    }
    // Calibration: the reference LRU-K scores 12/12 on this trace (measured
    // live: every flood page is +∞ forever, so the flood evicts itself and
    // the whole working set survives). Plain LRU scores 0/12 — every hot
    // page's LAST touch is older than every flood page's. The floor is
    // 11/12: one page of slack for judgment, no room for recency-ranking.
    const FLOOR: u64 = 11;
    if score < FLOOR {
        return Err(format!(
            "after a {FLOOD}-page one-touch flood, only {score}/{HOT} working-set pages were still resident (reference LRU-K: {rscore}/{HOT}; plain LRU: 0/{HOT}). A page touched ONCE must never outrank a twice-touched page — check the +∞ rule: fewer than 2 touches means the page dies first, oldest touch first"
        ));
    }
    Ok(format!("{score}/{HOT} working-set pages survived a {FLOOD}-page one-touch flood (reference {rscore}/{HOT}; plain LRU scores 0) — the flood evicted itself"))
}

/// 5. storm: 2000 seeded events — a zipf-ish hot set, lukewarm traffic,
///    one-touch flood bursts, pins held and released, dirty flags, flushes —
///    run against the reference pool. After EVERY event: identical resident
///    sets, identical counters, and no outstanding pin ever violated.
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "seeded hostile trace vs a reference pool, stats to the unit";
    verdict(ID, LABEL, storm_run())
}

/// One fetch driven through both pools, with the pin/unpin coin flips.
/// Outcomes must agree in KIND (Ok/Err), unpin results must agree in bool.
fn storm_fetch(
    me: &mut BufferPool,
    rf: &mut RefPool,
    rng: &mut Rng,
    pinned: &mut Vec<u32>,
    page: u32,
    ev: usize,
    pin_prob: usize,
    dirty_prob: usize,
) -> Result<(), String> {
    let a = me.fetch(page);
    let b = rf.fetch(page);
    match (a.is_ok(), b.is_ok()) {
        (true, true) => {}
        (false, false) => return Ok(()), // both refused: every frame pinned — correct backpressure
        (true, false) => {
            return Err(format!(
                "op {ev}: fetch({page}) — the reference refused (every frame pinned) but you returned Ok — you evicted a pinned frame or invented a frame"
            ))
        }
        (false, true) => {
            return Err(format!(
                "op {ev}: fetch({page}) — the reference found a pin-0 victim but you returned PoolExhausted — a pin-0 frame must always be a candidate, whatever its history"
            ))
        }
    }
    let distinct = pinned.iter().collect::<BTreeSet<_>>().len();
    if distinct < 8 && rng.below(100) < pin_prob {
        pinned.push(page); // the borrow stays outstanding
    } else {
        let dirty = rng.below(100) < dirty_prob;
        let ua = me.unpin(page, dirty);
        let ub = rf.unpin(page, dirty);
        if ua != ub {
            return Err(format!(
                "op {ev}: unpin({page}, {dirty}) right after a successful fetch must succeed — reference returned {ub}, yours {ua}; your pin accounting drifted"
            ));
        }
    }
    Ok(())
}

fn storm_run() -> Result<String, String> {
    const FRAMES: usize = 8;
    let mut me = BufferPool::new(FRAMES);
    let mut rf = RefPool::new(FRAMES);
    let mut rng = Rng(0x5EED_B07F);
    let mut pinned: Vec<u32> = Vec::new(); // one entry per outstanding pin
    let mut flood_next: u32 = 300;
    let mut fetches = 0u64;

    for ev in 0..2000usize {
        match rng.below(100) {
            // the hot set: 24 pages, zipf-ish (low ids much hotter)
            0..=54 => {
                let k = rng.below(24);
                let page = ((k * k) / 24) as u32;
                storm_fetch(&mut me, &mut rf, &mut rng, &mut pinned, page, ev, 30, 25)?;
                fetches += 1;
            }
            // lukewarm: uniform over a wide range
            55..=69 => {
                let page = 40 + rng.below(260) as u32;
                storm_fetch(&mut me, &mut rf, &mut rng, &mut pinned, page, ev, 20, 20)?;
                fetches += 1;
            }
            // a flood burst: fresh pages, one touch each, never pinned
            70..=79 => {
                let len = 3 + rng.below(8);
                for _ in 0..len {
                    let page = flood_next;
                    flood_next += 1;
                    if flood_next >= NUM_PAGES {
                        flood_next = 300;
                    }
                    storm_fetch(&mut me, &mut rf, &mut rng, &mut pinned, page, ev, 0, 0)?;
                    fetches += 1;
                }
            }
            // release an outstanding pin, sometimes reporting a write
            80..=92 => {
                if !pinned.is_empty() {
                    let i = rng.below(pinned.len());
                    let page = pinned[i];
                    let dirty = rng.below(100) < 35;
                    let a = me.unpin(page, dirty);
                    let b = rf.unpin(page, dirty);
                    if a != b {
                        return Err(format!(
                            "op {ev}: unpin({page}, {dirty}) — reference returned {b}, yours {a} — your pin accounting drifted"
                        ));
                    }
                    pinned.swap_remove(i);
                }
            }
            // flush a resident page
            93..=96 => {
                let res: Vec<u32> = rf.resident().into_iter().collect();
                if !res.is_empty() {
                    let page = res[rng.below(res.len())];
                    let a = me.flush(page);
                    let b = rf.flush(page);
                    if a != b {
                        return Err(format!("op {ev}: flush({page}) — reference returned {b}, yours {a}; the page IS resident"));
                    }
                }
            }
            // flush a probably-absent page
            _ => {
                let page = rng.below(NUM_PAGES as usize) as u32;
                let a = me.flush(page);
                let b = rf.flush(page);
                if a != b {
                    return Err(format!(
                        "op {ev}: flush({page}) — reference returned {b}, yours {a} — your page table disagrees about residency"
                    ));
                }
            }
        }

        // after EVERY event: pins untouchable, counters identical, sets equal
        let mine = resident_set(&me, FRAMES);
        for &pg in &pinned {
            if !mine.contains(&pg) {
                return Err(format!(
                    "op {ev}: page {pg} has an outstanding pin but is no longer resident — your pool evicted a pinned frame; in a real engine that is a use-after-free"
                ));
            }
        }
        let theirs = rf.resident();
        if mine != theirs {
            let gone: Vec<u32> = theirs.difference(&mine).copied().collect();
            let kept: Vec<u32> = mine.difference(&theirs).copied().collect();
            return Err(format!(
                "op {ev}: resident sets differ — {gone:?} should still be resident, {kept:?} should be gone. The first wrong page is usually the victim rule: <2 touches is +∞ and dies FIRST (oldest touch first among them); fully-historied pages rank by 2nd-most-recent touch, NOT by last touch"
            ));
        }
        let (mh, mr, mw, mv) = (me.hits(), me.reads(), me.writes(), me.evictions());
        let (rh, rr, rw, rv) = (rf.hits, rf.reads, rf.writes, rf.evictions);
        if (mh, mr, mw, mv) != (rh, rr, rw, rv) {
            return Err(format!(
                "op {ev}: counters differ (yours/reference) — hits {mh}/{rh}, reads {mr}/{rr}, writes {mw}/{rw}, evictions {mv}/{rv}. hits + reads + refused = fetch calls; writes = dirty evictions + dirty flushes; fills are reads, not evictions"
            ));
        }
    }

    // final: every resident frame's bytes must be the disk's
    for f in 0..FRAMES {
        if let Some(pg) = me.frame_page(f) {
            if me.frame_content(f) != Some(&disk_image(pg)) {
                return Err(format!(
                    "after the storm: frame {f} claims page {pg} but its bytes are not the disk's — a load or a writeback corrupted content"
                ));
            }
        }
    }
    Ok(format!(
        "2000 events ({fetches} fetches) model-exact: resident set, hits {}, reads {}, writes {}, evictions {} — and not one pinned frame violated",
        rf.hits, rf.reads, rf.writes, rf.evictions
    ))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_fetch_pin(),
        check_evict_order(),
        check_dirty_writeback(),
        check_scan_resistance(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "buffer-pool", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
