//! optimizer — forge lab 08 (tablespace).
//!
//! The planner you blamed in T5 is, underneath, one beautiful algorithm:
//! Selinger's dynamic program. The harness is the statistics sketch (exact
//! here — no estimation error to hide behind); the student writes the
//! search: System R's left-deep enumeration over join subsets, priced in
//! fixed-point milliunits, keeping cheapest plans per (subset, interesting
//! order). Graded on exact arithmetic against a reference optimizer over
//! seeded random query graphs.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/planner.rs     (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The five checks, in grading order:
//!   * cost_model         — the student's cost_of against hand-computed
//!                          milliunit answers on three scripted scenarios.
//!   * left_deep_dp       — a 4-table chain where the naive id-order is
//!                          provably wrong; exact optimum + order + methods.
//!   * interesting_orders — a scenario where the 2nd-cheapest pair join's
//!                          sorted output makes the top merge free.
//!   * beats_naive        — 200 seeded graphs: never worse than naive;
//!                          star graphs must win by a calibrated factor.
//!   * storm              — 100 seeded graphs: cost EXACTLY the reference
//!                          DP's optimum, plan structurally valid, and the
//!                          reported total_cost honest to the bit.

pub mod planner;

use kslab::{Check, Report};
use planner::{cost_of, plan, Edge, JoinMethod, Plan, ScanMethod, StatsCard, TableId, TableStat};
use std::collections::BTreeMap;

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* --------------------- cost model (graded copy) --------------------- */
/* Mirror of the pinned constants in planner.rs. The harness grades against
 * THESE — editing the student file's copies only breaks the student side. */

const SEQ: u64 = 1000; // seq_page_cost 1.0, in milliunits
const RANDOM: u64 = 4000; // random_page_cost 4.0
const CPU: u64 = 10; // cpu_tuple_cost 0.01
const PROBE: u64 = 3; // index descent pages per probe (T5.L2)
const ROW_BYTES: u64 = 400; // ~20 rows per 8192-byte page
const RPP: u64 = 20; // rows per page for a spilled intermediate
const WORK_MEM: u64 = 4 * 1024 * 1024;
const SEL_DENOM: u64 = 1_000_000;

/// Saturating fixed-point: products run in u128 and clamp to u64::MAX.
/// A plan priced past that is never the answer, and clamping keeps the
/// arithmetic total — no overflow panics on monster costs, native or wasm.
fn sat(x: u128) -> u64 {
    x.min(u64::MAX as u128) as u64
}

fn pages_of(rows: u64) -> u64 {
    rows / RPP + u64::from(rows % RPP != 0) // ceil, overflow-safe
}

fn ceil_log2(x: u64) -> u64 {
    if x <= 1 {
        0
    } else {
        64 - (x - 1).leading_zeros() as u64
    }
}

/// The pinned cardinality rule, harness copy: pure in the subset (see
/// planner.rs::rows_of for the contract).
fn rows_of(card: &StatsCard, mask: u32) -> u64 {
    let mut acc: u128 = 0;
    for t in 0..card.tables.len() {
        if mask & (1 << t) != 0 {
            let r = card.tables[t].rows as u128;
            acc = if acc == 0 { r } else { acc * r };
        }
    }
    if acc == 0 {
        return 0;
    }
    for e in &card.edges {
        if mask & (1 << e.a) != 0 && mask & (1 << e.b) != 0 {
            let sel = e.sel_ppm as u128;
            let den = SEL_DENOM as u128;
            acc = acc / den * sel + (acc % den) * sel / den;
        }
    }
    let r = acc.min(u64::MAX as u128) as u64;
    r.max(1)
}

fn has_index(card: &StatsCard, t: TableId, col: u8) -> bool {
    card.edges.iter().any(|e| {
        (e.a == t && e.col_a == col && e.index_a) || (e.b == t && e.col_b == col && e.index_b)
    })
}

fn connecting_edge(card: &StatsCard, t: TableId, mask: u32) -> Option<usize> {
    card.edges
        .iter()
        .position(|e| (e.a == t && mask & (1 << e.b) != 0) || (e.b == t && mask & (1 << e.a) != 0))
}

fn scan_milli(card: &StatsCard, t: TableId, s: ScanMethod) -> u64 {
    let st = &card.tables[t];
    let pages = match s {
        ScanMethod::Seq => st.pages as u128 * SEQ as u128,
        ScanMethod::Index(_) => st.pages as u128 * RANDOM as u128,
    };
    sat(pages + st.rows as u128 * CPU as u128)
}

fn sort_milli(rows: u64) -> u64 {
    let mut c = rows as u128 * ceil_log2(rows) as u128 * CPU as u128;
    if rows as u128 * ROW_BYTES as u128 > WORK_MEM as u128 {
        c += 2 * pages_of(rows) as u128 * SEQ as u128;
    }
    sat(c)
}

/// One left-deep join step under the pinned model: price of bringing table
/// `t` into the accumulated subset `mask` (whose plan has `outer_rows` rows
/// and emits `outs` sortedness) via method `m` with inner scan `s`.
/// Returns (added milliunits, output sortedness).
fn step_milli(
    card: &StatsCard,
    mask: u32,
    outer_rows: u64,
    outs: &[(TableId, u8)],
    t: TableId,
    m: JoinMethod,
    s: ScanMethod,
) -> (u64, Vec<(TableId, u8)>) {
    let ei = connecting_edge(card, t, mask).expect("join step needs a connecting edge");
    let e = &card.edges[ei];
    let (other, col_o, col_t) = if e.a == t {
        (e.b, e.col_b, e.col_a)
    } else {
        (e.a, e.col_a, e.col_b)
    };
    let rt = card.tables[t].rows as u128;
    let pt = card.tables[t].pages as u128;
    let or = outer_rows as u128;
    match m {
        JoinMethod::NestLoop => {
            let add = match s {
                ScanMethod::Seq => or * (pt * SEQ as u128 + rt * CPU as u128),
                ScanMethod::Index(_) => or * (PROBE as u128 * RANDOM as u128 + CPU as u128),
            };
            (sat(add), outs.to_vec()) // the loop preserves the outer's order
        }
        JoinMethod::Hash => {
            let mut add = scan_milli(card, t, s) as u128 + (or + rt) * CPU as u128;
            if rt * ROW_BYTES as u128 > WORK_MEM as u128 {
                // Grace spill: both sides written and re-read, sequentially
                add += 2 * (pages_of(outer_rows) as u128 + pt) * SEQ as u128 + (or + rt) * CPU as u128;
            }
            (sat(add), Vec::new())
        }
        JoinMethod::Merge => {
            let mut add = if outs.contains(&(other, col_o)) {
                0
            } else {
                sort_milli(outer_rows) as u128
            };
            add += scan_milli(card, t, s) as u128;
            if s != ScanMethod::Index(col_t) {
                add += sort_milli(card.tables[t].rows) as u128;
            }
            add += (or + rt) * CPU as u128;
            (sat(add), vec![(other, col_o), (t, col_t)])
        }
    }
}

/// Price an arbitrary (valid) plan — the harness's own arithmetic, used to
/// grade every plan the student returns.
fn cost_walk(card: &StatsCard, p: &Plan) -> u64 {
    let mut mask = 1u32 << p.join_order[0];
    let mut cost = scan_milli(card, p.join_order[0], p.scans[0]);
    let mut rows = rows_of(card, mask);
    let mut outs: Vec<(TableId, u8)> = match p.scans[0] {
        ScanMethod::Seq => Vec::new(),
        ScanMethod::Index(c) => vec![(p.join_order[0], c)],
    };
    for i in 1..p.join_order.len() {
        let t = p.join_order[i];
        let (add, outs2) = step_milli(card, mask, rows, &outs, t, p.methods[i - 1], p.scans[i]);
        cost = sat(cost as u128 + add as u128);
        outs = outs2;
        mask |= 1 << t;
        rows = rows_of(card, mask);
    }
    cost
}

/* ------------------------- reference search ------------------------- */

#[derive(Clone)]
struct Cand {
    cost: u64,
    order: Vec<TableId>,
    methods: Vec<JoinMethod>,
    scans: Vec<ScanMethod>,
    outs: Vec<(TableId, u8)>, // sortedness this plan emits
}

/// The interesting orders of a card: every (table, column) any edge
/// mentions, sorted for a deterministic tag numbering. Tag 0 is "cheapest,
/// any order"; tag 1+k is the k-th pair.
fn interesting_tags(card: &StatsCard) -> Vec<(TableId, u8)> {
    let mut tags: Vec<(TableId, u8)> = Vec::new();
    for e in &card.edges {
        for tc in [(e.a, e.col_a), (e.b, e.col_b)] {
            if !tags.contains(&tc) {
                tags.push(tc);
            }
        }
    }
    tags.sort();
    tags
}

/// Indexed columns of a table, ascending (deterministic enumeration).
fn indexed_cols(card: &StatsCard, t: TableId) -> Vec<u8> {
    let mut cols: Vec<u8> = Vec::new();
    for e in &card.edges {
        if e.a == t && e.index_a {
            cols.push(e.col_a);
        }
        if e.b == t && e.index_b {
            cols.push(e.col_b);
        }
    }
    cols.sort();
    cols.dedup();
    cols
}

/// Inner scan options for a join step, in the pinned enumeration order
/// (Seq, then the join-column index). Hash never wants the index — it reads
/// every row either way and cannot use the order.
fn inner_options(card: &StatsCard, t: TableId, col_t: u8, m: JoinMethod) -> Vec<ScanMethod> {
    let mut v = vec![ScanMethod::Seq];
    if m != JoinMethod::Hash && has_index(card, t, col_t) {
        v.push(ScanMethod::Index(col_t));
    }
    v
}

/// Offer a candidate to the DP table: it competes for slot (mask, 0) and —
/// when interesting orders are kept — for one slot per sortedness it emits.
/// Strictly cheaper evicts; a tie keeps the incumbent.
fn register(
    states: &mut BTreeMap<(u32, u8), Cand>,
    tags: &[(TableId, u8)],
    keep_orders: bool,
    mask: u32,
    cand: Cand,
) {
    let mut keys: Vec<(u32, u8)> = vec![(mask, 0)];
    if keep_orders {
        for out in &cand.outs {
            if let Some(pos) = tags.iter().position(|tc| tc == out) {
                keys.push((mask, 1 + pos as u8));
            }
        }
    }
    for k in keys {
        if states.get(&k).map_or(true, |old| cand.cost < old.cost) {
            states.insert(k, cand.clone());
        }
    }
}

/// The System R dynamic program, reference edition. `keep_orders = false`
/// is the cheapest-per-subset-only variant — the interesting_orders check's
/// punching bag.
fn ref_dp(card: &StatsCard, keep_orders: bool) -> Cand {
    let n = card.tables.len();
    let tags = interesting_tags(card);
    let mut states: BTreeMap<(u32, u8), Cand> = BTreeMap::new();
    // level 1: access paths
    for t in 0..n {
        let mask = 1u32 << t;
        register(
            &mut states,
            &tags,
            keep_orders,
            mask,
            Cand {
                cost: scan_milli(card, t, ScanMethod::Seq),
                order: vec![t],
                methods: vec![],
                scans: vec![ScanMethod::Seq],
                outs: vec![],
            },
        );
        for c in indexed_cols(card, t) {
            register(
                &mut states,
                &tags,
                keep_orders,
                mask,
                Cand {
                    cost: scan_milli(card, t, ScanMethod::Index(c)),
                    order: vec![t],
                    methods: vec![],
                    scans: vec![ScanMethod::Index(c)],
                    outs: vec![(t, c)],
                },
            );
        }
    }
    // levels 2..=n: extend every kept plan with every connected table
    for size in 1..n {
        let entries: Vec<(u32, Cand)> = states
            .iter()
            .filter(|((m, _), _)| m.count_ones() as usize == size)
            .map(|((m, _), c)| (*m, c.clone()))
            .collect();
        for (mask, cand) in entries {
            let rows = rows_of(card, mask);
            for t in 0..n {
                if mask & (1 << t) != 0 {
                    continue;
                }
                let Some(ei) = connecting_edge(card, t, mask) else {
                    continue;
                };
                let e = &card.edges[ei];
                let col_t = if e.a == t { e.col_a } else { e.col_b };
                for m in [JoinMethod::NestLoop, JoinMethod::Hash, JoinMethod::Merge] {
                    for s in inner_options(card, t, col_t, m) {
                        let (add, outs2) = step_milli(card, mask, rows, &cand.outs, t, m, s);
                        let mut c2 = cand.clone();
                        c2.cost = sat(c2.cost as u128 + add as u128);
                        c2.order.push(t);
                        c2.methods.push(m);
                        c2.scans.push(s);
                        c2.outs = outs2;
                        register(&mut states, &tags, keep_orders, mask | (1 << t), c2);
                    }
                }
            }
        }
    }
    let full = (1u32 << n) - 1;
    states
        .remove(&(full, 0))
        .expect("a connected card always yields a full plan")
}

/// The punching bag: start at table 0, keep adding the lowest-id table that
/// connects (id-order along whatever graph), each step locally cheapest
/// (method, scan) — honest pricing, no lookahead, no interesting orders.
fn naive_plan(card: &StatsCard) -> (Plan, u64) {
    let n = card.tables.len();
    let mut order = vec![0usize];
    let mut mask = 1u32;
    while order.len() < n {
        let t = (0..n)
            .find(|&t| mask & (1 << t) == 0 && connecting_edge(card, t, mask).is_some())
            .expect("generated cards are connected");
        order.push(t);
        mask |= 1 << t;
    }
    let mut cost = scan_milli(card, 0, ScanMethod::Seq);
    let mut rows = card.tables[0].rows;
    let mut outs: Vec<(TableId, u8)> = Vec::new();
    let mut methods: Vec<JoinMethod> = Vec::new();
    let mut scans: Vec<ScanMethod> = vec![ScanMethod::Seq];
    let mut mask = 1u32;
    for i in 1..n {
        let t = order[i];
        let e = &card.edges[connecting_edge(card, t, mask).expect("connected")];
        let col_t = if e.a == t { e.col_a } else { e.col_b };
        let mut best: Option<(u64, JoinMethod, ScanMethod, Vec<(TableId, u8)>)> = None;
        for m in [JoinMethod::NestLoop, JoinMethod::Hash, JoinMethod::Merge] {
            for s in inner_options(card, t, col_t, m) {
                let (add, o2) = step_milli(card, mask, rows, &outs, t, m, s);
                if best.as_ref().map_or(true, |b| add < b.0) {
                    best = Some((add, m, s, o2));
                }
            }
        }
        let (add, m, s, o2) = best.expect("a connected step has options");
        cost = sat(cost as u128 + add as u128);
        methods.push(m);
        scans.push(s);
        outs = o2;
        mask |= 1 << t;
        rows = rows_of(card, mask);
    }
    (
        Plan {
            join_order: order,
            methods,
            scans,
            total_cost: cost as f64 / 1000.0,
        },
        cost,
    )
}

/* --------------------------- validation ----------------------------- */

/// Structural validity: a permutation, legal lengths, no cross products,
/// real indexes only, indexed nested-loops probing on the join column.
fn validate(card: &StatsCard, p: &Plan) -> Result<(), String> {
    let n = card.tables.len();
    if p.join_order.len() != n {
        return Err(format!(
            "join_order has {} entries, the card has {} tables",
            p.join_order.len(),
            n
        ));
    }
    let mut sorted = p.join_order.clone();
    sorted.sort();
    if sorted != (0..n).collect::<Vec<_>>() {
        return Err(format!(
            "join_order {:?} is not a permutation of the {n} tables — every table joined exactly once",
            p.join_order
        ));
    }
    if p.methods.len() + 1 != n || p.scans.len() != n {
        return Err(format!(
            "shape error: {} order entries, {} methods, {} scans — methods = order − 1, scans = order",
            p.join_order.len(),
            p.methods.len(),
            p.scans.len()
        ));
    }
    if let ScanMethod::Index(c) = p.scans[0] {
        if !has_index(card, p.join_order[0], c) {
            return Err(format!(
                "scans[0] = Index({c}) but table {} has no index on column {c}",
                p.join_order[0]
            ));
        }
    }
    let mut mask = 1u32 << p.join_order[0];
    for i in 1..n {
        let t = p.join_order[i];
        let ei = match connecting_edge(card, t, mask) {
            Some(ei) => ei,
            None => {
                return Err(format!(
                    "step {i}: table {t} has no predicate edge into the tables already joined — System R plans no cross products"
                ))
            }
        };
        let e = &card.edges[ei];
        let col_t = if e.a == t { e.col_a } else { e.col_b };
        if let ScanMethod::Index(c) = p.scans[i] {
            if !has_index(card, t, c) {
                return Err(format!(
                    "step {i}: Index({c}) on table {t} — the card grants no such index"
                ));
            }
            if p.methods[i - 1] == JoinMethod::NestLoop && c != col_t {
                return Err(format!(
                    "step {i}: an indexed nested-loop probes on the join column ({col_t}), not column {c}"
                ));
            }
        }
        mask |= 1 << t;
    }
    Ok(())
}

/* --------------------------- card factory --------------------------- */

#[derive(Clone, Copy)]
enum Shape {
    Chain,
    Star,
    Cycle,
}

impl Shape {
    fn name(self) -> &'static str {
        match self {
            Shape::Chain => "chain",
            Shape::Star => "star",
            Shape::Cycle => "cycle",
        }
    }
}

/// Seeded random query graphs. Stars get a big hub (50k–250k rows, so its
/// hash build ALWAYS spills work_mem) with small leaves at foreign-key
/// selectivity (~1/hub_rows); chains/cycles draw rows 1k–300k and
/// selectivities scaled to the tables — a pair's output is 2–64× the
/// smaller side, so estimates stay in the cost model's sane regime.
/// Columns: an endpoint shares the table's column 0 half the time (merge
/// cascades possible), else a fresh column; an index exists on a
/// (table, column) with p = 0.45 — except a star hub, which is never
/// indexed (no probe path around the spilled build).
fn gen_card(rng: &mut Rng, shape: Shape, n: usize) -> StatsCard {
    let mut perm: Vec<usize> = (0..n).collect();
    for i in (1..n).rev() {
        let j = rng.below(i + 1);
        perm.swap(i, j);
    }
    if let Shape::Star = shape {
        if perm[0] == 0 {
            // keep table 0 a leaf: the naive id order must eat the hub as an inner
            perm.swap(0, 1);
        }
    }
    let hub = perm[0];
    let mut tables: Vec<TableStat> = Vec::with_capacity(n);
    for t in 0..n {
        let rows = match shape {
            Shape::Star if t == hub => 50_000 + 10_000 * rng.below(21) as u64,
            Shape::Star => 1_000 + 500 * rng.below(19) as u64,
            _ => 1_000 * (1 + rng.below(300) as u64),
        };
        let rpp = 10 + rng.below(31) as u64;
        tables.push(TableStat {
            rows,
            pages: (rows + rpp - 1) / rpp,
        });
    }
    let pairs: Vec<(usize, usize)> = match shape {
        Shape::Chain => (0..n - 1).map(|i| (perm[i], perm[i + 1])).collect(),
        Shape::Star => (1..n).map(|i| (perm[0], perm[i])).collect(),
        Shape::Cycle => {
            let mut v: Vec<(usize, usize)> = (0..n - 1).map(|i| (perm[i], perm[i + 1])).collect();
            v.push((perm[n - 1], perm[0]));
            v
        }
    };
    let mut next_col = vec![1u8; n];
    let mut cols: Vec<(u8, u8)> = Vec::with_capacity(pairs.len());
    for &(a, b) in &pairs {
        let ca = if rng.below(2) == 0 {
            0
        } else {
            let c = next_col[a];
            next_col[a] += 1;
            c
        };
        let cb = if rng.below(2) == 0 {
            0
        } else {
            let c = next_col[b];
            next_col[b] += 1;
            c
        };
        cols.push((ca, cb));
    }
    let mut idx: BTreeMap<(usize, u8), bool> = BTreeMap::new();
    for (k, &(a, b)) in pairs.iter().enumerate() {
        let (ca, cb) = cols[k];
        for tc in [(a, ca), (b, cb)] {
            // a star hub is NEVER indexed: with no probe path the naive
            // order cannot dodge the spilled hub build — that is the factor
            let star_hub = matches!(shape, Shape::Star) && tc.0 == hub;
            idx.entry(tc).or_insert_with(|| !star_hub && rng.below(100) < 45);
        }
    }
    let mut edges = Vec::with_capacity(pairs.len());
    for (k, &(a, b)) in pairs.iter().enumerate() {
        let (ca, cb) = cols[k];
        let sel_ppm = match shape {
            Shape::Star => (SEL_DENOM / tables[hub].rows).max(1) as u32 + 1,
            _ => {
                // join-size-realistic: a pair's output ≈ c × the smaller
                // side, c ∈ {2,…,64} — selectivity shrinks as tables grow,
                // so estimates never leave the cost model's sane regime
                let c = 2u64 << rng.below(6);
                let bigger = tables[a].rows.max(tables[b].rows);
                ((c * SEL_DENOM / bigger).clamp(100, 50_000)) as u32
            }
        };
        edges.push(Edge {
            a,
            b,
            col_a: ca,
            col_b: cb,
            sel_ppm,
            index_a: idx[&(a, ca)],
            index_b: idx[&(b, cb)],
        });
    }
    StatsCard { tables, edges }
}

/* -------------- scripted scenarios (fixed, hand-priced) -------------- */

/// left_deep_dp: a 4-table chain 0–1–2–3. The selective edge (2⋈3 at
/// 10 ppm, with an index on table 3's side and on table 2's col 1) sits at
/// the END of id order: joining left-to-right builds a 320,000-row
/// intermediate at the first step and a 3,200,000-row one at the second.
/// The DP starts at the selective edge and never sees five figures.
fn card_chain4() -> StatsCard {
    StatsCard {
        tables: vec![
            TableStat { rows: 20_000, pages: 1_000 },
            TableStat { rows: 8_000, pages: 400 },
            TableStat { rows: 100_000, pages: 5_000 },
            TableStat { rows: 300, pages: 15 },
        ],
        edges: vec![
            Edge { a: 0, b: 1, col_a: 0, col_b: 0, sel_ppm: 2_000, index_a: false, index_b: false },
            Edge { a: 1, b: 2, col_a: 0, col_b: 0, sel_ppm: 100, index_a: false, index_b: false },
            Edge { a: 2, b: 3, col_a: 1, col_b: 0, sel_ppm: 10, index_a: true, index_b: true },
        ],
    }
}

/// interesting_orders: a 3-table chain 0–1–2 where EVERY join is on
/// column 0 — so a merge join's output order serves the next merge
/// directly. {0,1} by hash is the cheapest pair plan, but the pair merge
/// (2nd cheapest) arrives sorted on (1, col 0), which makes the top merge
/// with table 2 free of any outer sort — and table 2's index feeds the
/// merge's inner side sorted. Cheapest-per-subset pruning loses.
fn card_interesting() -> StatsCard {
    StatsCard {
        tables: vec![
            TableStat { rows: 300_000, pages: 15_000 },
            TableStat { rows: 30_000, pages: 1_500 },
            TableStat { rows: 20_000, pages: 1_000 },
        ],
        edges: vec![
            Edge { a: 0, b: 1, col_a: 0, col_b: 0, sel_ppm: 50, index_a: true, index_b: true },
            Edge { a: 1, b: 2, col_a: 0, col_b: 0, sel_ppm: 2_000, index_a: true, index_b: true },
        ],
    }
}

/* --------------------------- CALIBRATION ----------------------------
 * Reference solution (labs/_solutions/optimizer), these pins, native
 * x86-64, 2026-08 — with a brute-force cross-check that enumerates EVERY
 * valid plan (connected order × method × legal scan) for the scripted
 * cards and prices it with the harness walker:
 *
 *   left_deep_dp: optimum 7,812,800 milliunits via [3,2,1,0] with
 *     (NestLoop,Hash,Hash) — the ONLY plan at that cost out of 792 valid
 *     plans. Naive [0,1,2,3] = 90,381,000 — 11.57× worse.
 *   interesting_orders: optimum 81,500,000 via (Merge,Merge) — exactly two
 *     plans reach it, orders [0,1,2] and [1,0,2], both with all-index
 *     scans; no other method mix comes close. Cheapest-per-subset-only
 *     (and the naive order) = 117,000,000 — 1.436× worse.
 *   beats_naive: 67 stars in the seeded 200; reference naive/dp ratio
 *     min 2.000×, mean 2.453×. STAR_FACTOR_MILLI = 1200 (1.20×) is 60% of
 *     the measured minimum — headroom for legitimate variation.
 *   storm: max reference cost over the 100 cards ≈ 6.4×10¹³ milliunits —
 *     nowhere near the u64 clamp, so every card grades real arithmetic.
 */

/// beats_naive: required worst-case naive/dp ratio over the seeded star
/// graphs, in milli-ratio (1200 = 1.20×). Measured reference minimum over
/// the 67 seeded stars: 2.000× — the constant is 60% of that (CALIBRATION).
const STAR_FACTOR_MILLI: u64 = 1_200;

/* ------------------------------ checks ------------------------------ */

/// 1. cost_model: three hand-built scenarios, five plans, answers known to
///    the milliunit by hand — the student's cost_of must reproduce the
///    pinned arithmetic before any search may be graded.
pub fn check_cost_model() -> Check {
    const ID: &str = "cost_model";
    const LABEL: &str = "cost arithmetic matches the harness model exactly";

    // scenario 1: an in-memory hash join, priced end to end
    let card1 = StatsCard {
        tables: vec![
            TableStat { rows: 2_000, pages: 100 },
            TableStat { rows: 8_000, pages: 400 },
        ],
        edges: vec![Edge { a: 0, b: 1, col_a: 0, col_b: 0, sel_ppm: 500, index_a: false, index_b: false }],
    };
    let p1 = Plan {
        join_order: vec![0, 1],
        methods: vec![JoinMethod::Hash],
        scans: vec![ScanMethod::Seq, ScanMethod::Seq],
        total_cost: 700.0,
    };
    // scenario 2: the OLTP probe vs the Grace spill
    let card2 = StatsCard {
        tables: vec![
            TableStat { rows: 300, pages: 15 },
            TableStat { rows: 200_000, pages: 10_000 },
        ],
        edges: vec![Edge { a: 0, b: 1, col_a: 0, col_b: 0, sel_ppm: 5, index_a: false, index_b: true }],
    };
    let p2a = Plan {
        join_order: vec![0, 1],
        methods: vec![JoinMethod::NestLoop],
        scans: vec![ScanMethod::Seq, ScanMethod::Index(0)],
        total_cost: 3_621.0,
    };
    let p2b = Plan {
        join_order: vec![0, 1],
        methods: vec![JoinMethod::Hash],
        scans: vec![ScanMethod::Seq, ScanMethod::Seq],
        total_cost: 36_054.0,
    };
    // scenario 3: a merge join that buys one sort, vs the cheap hash
    let card3 = StatsCard {
        tables: vec![
            TableStat { rows: 50_000, pages: 2_500 },
            TableStat { rows: 4_000, pages: 200 },
        ],
        edges: vec![Edge { a: 0, b: 1, col_a: 0, col_b: 0, sel_ppm: 100, index_a: true, index_b: false }],
    };
    let p3a = Plan {
        join_order: vec![0, 1],
        methods: vec![JoinMethod::Merge],
        scans: vec![ScanMethod::Index(0), ScanMethod::Seq],
        total_cost: 11_760.0,
    };
    let p3b = Plan {
        join_order: vec![0, 1],
        methods: vec![JoinMethod::Hash],
        scans: vec![ScanMethod::Seq, ScanMethod::Seq],
        total_cost: 3_780.0,
    };

    let scenarios: Vec<(&str, StatsCard, Vec<(Plan, u64, &str)>)> = vec![
        (
            "in-memory hash join",
            card1,
            vec![(
                p1,
                700_000,
                "scan A = 100·1000 + 2,000·10 = 120,000; hash adds scan B (400·1000 + 8,000·10) = 480,000 + cpu (2,000+8,000)·10 = 100,000; the 8,000-row build is 3.2 MB ≤ work_mem — no spill",
            )],
        ),
        (
            "indexed nested-loop vs Grace hash",
            card2,
            vec![
                (
                    p2a,
                    3_621_000,
                    "scan C = 15·1000 + 300·10 = 18,000; then 300 probes × (3·4000 + 10) = 3,603,000 — INDEX_PROBE_PAGES random pages per outer row",
                ),
                (
                    p2b,
                    36_054_000,
                    "scan C 18,000 + scan D (10,000·1000 + 200,000·10) 12,000,000 + cpu 2,003,000; the 200,000-row build is 80 MB > work_mem → Grace: + 2·(15+10,000)·1000 = 20,030,000 spill I/O + another 2,003,000 cpu",
                ),
            ],
        ),
        (
            "merge join buying one sort",
            card3,
            vec![
                (
                    p3a,
                    11_760_000,
                    "outer arrives sorted via the index scan (2,500·4000 + 50,000·10) = 10,500,000; inner seq 240,000 + sort(4,000) = 4,000·12·10 = 480,000 (fits work_mem); merge walk (50,000+4,000)·10 = 540,000",
                ),
                (
                    p3b,
                    3_780_000,
                    "seq E (2,500·1000 + 50,000·10) 3,000,000 + seq F 240,000 + cpu 540,000; build fits — the hash wins here and the model must SAY so",
                ),
            ],
        ),
    ];

    for (name, card, plans) in &scenarios {
        for (p, want, walk) in plans {
            let got = cost_of(p, card);
            if got != *want {
                return Check::fail(
                    ID,
                    LABEL,
                    format!(
                        "scenario \"{name}\": cost_of returned {got} milliunits, the pinned arithmetic says {want} — {walk}"
                    ),
                );
            }
        }
    }
    Check::pass(
        ID,
        LABEL,
        "5 plans across 3 scenarios priced to the milliunit — seq/index scans, indexed probes, the Grace spill, a bought sort",
    )
}

/// 2. left_deep_dp: the 4-table chain where the naive id-order is provably
///    wrong — exact optimum cost, order, and methods.
pub fn check_left_deep_dp() -> Check {
    const ID: &str = "left_deep_dp";
    const LABEL: &str = "cheapest left-deep plan on a 4-table chain";
    let card = card_chain4();
    let best = ref_dp(&card, true);
    let (naive, naive_cost) = naive_plan(&card);
    if naive_cost < best.cost * 4 {
        return Check::fail(
            ID,
            LABEL,
            format!("harness calibration bug: the scripted chain barely punishes naive ({naive_cost} vs {})", best.cost),
        );
    }
    let got = plan(&card);
    if let Err(e) = validate(&card, &got) {
        return Check::fail(ID, LABEL, format!("invalid plan: {e}"));
    }
    let got_cost = cost_walk(&card, &got);
    if got_cost != best.cost {
        return Check::fail(
            ID,
            LABEL,
            format!(
                "your plan costs {got_cost} milliunits; the DP optimum is {} via {:?} with {:?} — the naive {:?} pays {} because it builds a 320,000-row intermediate at step 1 while the selective edge (2⋈3, 10 ppm) waits its turn. Optimal substructure: price every SUBSET, don't walk left to right",
                best.cost, best.order, best.methods, naive.join_order, naive_cost
            ),
        );
    }
    if got.join_order != best.order || got.methods != best.methods {
        return Check::fail(
            ID,
            LABEL,
            format!(
                "right cost, wrong plan: the unique optimum is {:?} with {:?}, you returned {:?} with {:?} (uniqueness brute-forced over every connected order × method × scan)",
                best.order, best.methods, got.join_order, got.methods
            ),
        );
    }
    Check::pass(
        ID,
        LABEL,
        format!(
            "found {:?} with {:?} at {} milliunits — {:.1}× under the naive left-to-right plan",
            best.order,
            best.methods,
            best.cost,
            naive_cost as f64 / best.cost as f64
        ),
    )
}

/// 3. interesting_orders: the 2nd-cheapest pair plan's sorted output makes
///    the top merge free; cheapest-per-subset pruning is not enough.
pub fn check_interesting_orders() -> Check {
    const ID: &str = "interesting_orders";
    const LABEL: &str = "a sorted intermediate kept when it saves a sort later";
    let card = card_interesting();
    let best = ref_dp(&card, true);
    let flat = ref_dp(&card, false);
    if flat.cost <= best.cost {
        return Check::fail(
            ID,
            LABEL,
            "harness calibration bug: cheapest-per-subset ties the full DP — the scenario teaches nothing",
        );
    }
    let got = plan(&card);
    if let Err(e) = validate(&card, &got) {
        return Check::fail(ID, LABEL, format!("invalid plan: {e}"));
    }
    let got_cost = cost_walk(&card, &got);
    if got_cost == flat.cost {
        return Check::fail(
            ID,
            LABEL,
            format!(
                "{got_cost} milliunits is exactly the cheapest-per-subset answer: the hash join won {{0,1}} and you pruned the rest. But the 2nd-cheapest plan for {{0,1}} is a MERGE whose output arrives sorted on (table 1, col 0) — and the top join needs exactly that order, so its outer sort vanishes: {} milliunits total. A plan dominated on price is not dominated when its order is an asset",
                best.cost
            ),
        );
    }
    if got_cost != best.cost {
        return Check::fail(
            ID,
            LABEL,
            format!("your plan costs {got_cost} milliunits; the interesting-orders optimum is {} (cheapest-per-subset gets {})", best.cost, flat.cost),
        );
    }
    if got.methods.iter().any(|m| *m != JoinMethod::Merge) {
        return Check::fail(
            ID,
            LABEL,
            format!(
                "optimal cost but the methods are {:?} — the point of the scenario is merge all the way up: sorted pair output, free outer order on top",
                got.methods
            ),
        );
    }
    Check::pass(
        ID,
        LABEL,
        format!(
            "kept the sorted pair plan: {} milliunits with merges on top — {:.1}% under cheapest-per-subset's {}",
            best.cost,
            100.0 * (flat.cost - best.cost) as f64 / flat.cost as f64,
            flat.cost
        ),
    )
}

/// 4. beats_naive: 200 seeded graphs — never worse than naive left-to-right;
///    on star graphs the DP must win by the calibrated factor.
pub fn check_beats_naive() -> Check {
    const ID: &str = "beats_naive";
    const LABEL: &str = "DP plan never loses to the naive left-to-right order";
    let mut rng = Rng(0x5EED_0804);
    let mut star_min = u64::MAX; // naive/dp milli-ratio over star graphs
    let mut stars = 0usize;
    for i in 0..200usize {
        let shape = [Shape::Chain, Shape::Star, Shape::Cycle][i % 3];
        let n = 3 + rng.below(4);
        let card = gen_card(&mut rng, shape, n);
        let (naive, naive_cost) = naive_plan(&card);
        let got = plan(&card);
        if let Err(e) = validate(&card, &got) {
            return Check::fail(ID, LABEL, format!("graph {i} ({} {n} tables): invalid plan — {e}", shape.name()));
        }
        let got_cost = cost_walk(&card, &got);
        if got_cost > naive_cost {
            return Check::fail(
                ID,
                LABEL,
                format!(
                    "graph {i} ({}, {n} tables): your plan costs {got_cost} milliunits, naive left-to-right {:?} costs {naive_cost} — the DP optimizes over a space that CONTAINS the naive plan, so losing to it means the search or the pricing is broken",
                    shape.name(),
                    naive.join_order
                ),
            );
        }
        if let Shape::Star = shape {
            stars += 1;
            star_min = star_min.min(naive_cost * 1000 / got_cost.max(1));
        }
    }
    let need = STAR_FACTOR_MILLI as f64 / 1000.0;
    if star_min < STAR_FACTOR_MILLI {
        return Check::fail(
            ID,
            LABEL,
            format!(
                "on star graphs the DP must humiliate the naive order: worst improvement {:.2}× over {stars} seeded stars, required {need:.2}× — naive drags the hub in as a spilled hash build (three passes over its pages); the DP scans the hub once and probes tiny dimension hashes",
                star_min as f64 / 1000.0
            ),
        );
    }
    Check::pass(
        ID,
        LABEL,
        format!(
            "200 seeded graphs: never worse than naive; worst star-graph improvement {:.2}× (required {need:.2}×)",
            star_min as f64 / 1000.0
        ),
    )
}

/// 5. storm: 100 seeded random query graphs — exact cost match against the
///    reference DP, structural validity, honest reported total_cost.
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "seeded random query graphs: exact cost + plan match vs reference DP";
    let mut rng = Rng(0x5EED_0805);
    for i in 0..100usize {
        let shape = [Shape::Chain, Shape::Star, Shape::Cycle][i % 3];
        let n = 3 + rng.below(4);
        let card = gen_card(&mut rng, shape, n);
        let best = ref_dp(&card, true);
        let got = plan(&card);
        if let Err(e) = validate(&card, &got) {
            return Check::fail(ID, LABEL, format!("graph {i} ({} {n} tables): invalid plan — {e}", shape.name()));
        }
        let got_cost = cost_walk(&card, &got);
        if got_cost != best.cost {
            return Check::fail(
                ID,
                LABEL,
                format!(
                    "graph {i} ({} {n} tables): your {:?} costs {got_cost} milliunits; the reference DP finds {:?} at {} — the DP keeps cheapest per (subset, interesting order); a dropped order-property or a skipped legal method surfaces exactly here",
                    shape.name(),
                    got.join_order,
                    best.order,
                    best.cost
                ),
            );
        }
        let reported = got_cost as f64 / 1000.0;
        if got.total_cost != reported {
            return Check::fail(
                ID,
                LABEL,
                format!(
                    "graph {i}: the plan reports total_cost {} but the pinned model prices it at {reported} — total_cost = cost_of(plan, card) as f64 / 1000.0, to the bit",
                    got.total_cost
                ),
            );
        }
    }
    Check::pass(
        ID,
        LABEL,
        "100 seeded graphs (chains, stars, cycles, 3–6 tables): every plan valid, every cost exact vs the reference DP",
    )
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_cost_model(),
        check_left_deep_dp(),
        check_interesting_orders(),
        check_beats_naive(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "optimizer", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
