//! columnar — forge lab 09 (tablespace). The analytical engine in miniature.
//!
//! Eight labs of rows end here. This one turns the page sideways: DSM, the
//! decomposition storage model — every column stored on its own, compressed
//! block by block, with a zone map per block and an executor that works on
//! 2048-value batches behind selection masks instead of pulling one tuple
//! at a time (T7.L1/L2). Same algebra as lab 05's volcano, different
//! physics: the scan reads 2% of the bytes and never lets a tuple be born.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/column.rs      (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The corpus is seeded and integer-only, so native and wasm agree to the
//! bit. A synthetic `events` table, 50,000 rows × 4 columns, in blocks of
//! BLOCK (2048) values — 24 full blocks plus a short one:
//!
//! ```text
//!   ts      i64 epoch-ms, monotone non-decreasing with ~65% repeated
//!           values — run-length heaven, narrow ascending zones
//!   status  one of 6 strings, iid-ish per row, 3% NULL — dictionary heaven
//!   region  one of 16 strings, CONSTANT within each block (physically
//!           clustered — the zone map's best case; blocks are shuffled)
//!   amount  i64, zipf-ish (small values common, large rare); ~2% NULL,
//!           blocks 5–6 are NULL-heavy (~40%), and blocks 9 and 17 are
//!           ALL NULL — the outage windows, where the sensor was down
//! ```
//!
//! The five checks, in grading order:
//!   * encode_roundtrip — decode(encode(x)) == x for every column × every
//!     encoding, byte-exact, NULLs included; a constant block is ONE run.
//!   * zone_skip        — zones match the canonical min/max/nulls exactly,
//!     and engineered predicates read exactly the blocks they must.
//!   * vectorized_ops   — scripted filter+sum queries vs the row-store
//!     reference: rows_matched and sum exact, NULL semantics included.
//!   * compression_band — total encoded size of the seeded corpus inside a
//!     band calibrated on the reference build (see CALIBRATION below).
//!   * storm            — 300 seeded mixed queries: exact answers, and
//!     blocks_read ≤ the canonical-zone ceiling on every single one.

mod column;

use column::{Block, ColumnStore, Pred, Value, Zone, BLOCK};
use kslab::{Check, Report};

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* ----------------------------- corpus ------------------------------- */

const N_ROWS: usize = 50_000;

/// Region block populations, r00..r15 — sums to 25 blocks. r00 lives in
/// exactly 1 block, r03 and r07 in exactly 3; the checks lean on that.
const REGION_COUNTS: [usize; 16] = [1, 2, 1, 3, 1, 2, 1, 3, 1, 2, 1, 2, 1, 2, 1, 1];

const STATUSES: [&str; 6] = ["paid", "pending", "failed", "refunded", "chargeback", "disputed"];

/// The outage windows: every amount in these blocks is NULL.
const OUTAGE_BLOCKS: [usize; 2] = [9, 17];
/// NULL-heavy blocks: ~40% of amounts are NULL.
const NULL_HEAVY_BLOCKS: [usize; 2] = [5, 6];

struct Corpus {
    ts: Vec<Value>,
    status: Vec<Value>,
    region: Vec<Value>,
    amount: Vec<Value>,
    block_region: Vec<usize>, // region index per block — the clustered assignment
}

impl Corpus {
    fn col(&self, name: &str) -> &Vec<Value> {
        match name {
            "ts" => &self.ts,
            "status" => &self.status,
            "region" => &self.region,
            "amount" => &self.amount,
            _ => panic!("harness bug: unknown column {name}"),
        }
    }
    fn n_blocks(&self) -> usize {
        self.ts.len().div_ceil(BLOCK)
    }
    fn block(&self, col: &str, b: usize) -> &[Value] {
        let c = self.col(col);
        &c[b * BLOCK..((b + 1) * BLOCK).min(c.len())]
    }
    fn t_min(&self) -> i64 {
        match &self.ts[0] {
            Value::Int(t) => *t,
            _ => unreachable!(),
        }
    }
    fn t_max(&self) -> i64 {
        match self.ts.last() {
            Some(Value::Int(t)) => *t,
            _ => unreachable!(),
        }
    }
}

fn region_name(i: usize) -> String {
    format!("r{i:02}")
}

/// The seeded corpus. Draw order is fixed (ts, region assignment, status,
/// amount), integer-only — bit-identical on native and wasm.
fn corpus() -> Corpus {
    let mut rng = Rng(0x5EED_0909);
    let n_blocks = N_ROWS.div_ceil(BLOCK);

    // ts: monotone non-decreasing; ~65% of rows repeat the previous tick,
    // else advance 1..=8 ms. Long runs, narrow ascending zones.
    let mut ts = Vec::with_capacity(N_ROWS);
    let mut t: i64 = 1_752_200_000_000; // 2026-01-01-ish, epoch ms
    for _ in 0..N_ROWS {
        ts.push(Value::Int(t));
        let roll = rng.below(100);
        let step = rng.below(8);
        if roll >= 65 {
            t += 1 + step as i64;
        }
    }

    // region: each block holds exactly ONE region (physical clustering);
    // the per-region block counts are pinned, the block order shuffled.
    let mut block_region: Vec<usize> = Vec::with_capacity(n_blocks);
    for (r, &count) in REGION_COUNTS.iter().enumerate() {
        for _ in 0..count {
            block_region.push(r);
        }
    }
    for i in (1..block_region.len()).rev() {
        let j = rng.below(i + 1);
        block_region.swap(i, j);
    }
    let mut region = Vec::with_capacity(N_ROWS);
    for i in 0..N_ROWS {
        region.push(Value::Text(region_name(block_region[i / BLOCK])));
    }

    // status: 3% NULL, else weighted over the six statuses.
    let mut status = Vec::with_capacity(N_ROWS);
    for _ in 0..N_ROWS {
        if rng.below(100) < 3 {
            status.push(Value::Null);
            continue;
        }
        let w = rng.below(100);
        let i = if w < 45 {
            0
        } else if w < 65 {
            1
        } else if w < 80 {
            2
        } else if w < 90 {
            3
        } else if w < 96 {
            4
        } else {
            5
        };
        status.push(Value::Text(STATUSES[i].to_string()));
    }

    // amount: zipf-ish (a² for a in 0..100, plus crumbs). NULLs: the two
    // outage blocks entirely, ~40% in the NULL-heavy blocks, ~2% elsewhere.
    let mut amount = Vec::with_capacity(N_ROWS);
    for i in 0..N_ROWS {
        let b = i / BLOCK;
        if OUTAGE_BLOCKS.contains(&b) {
            amount.push(Value::Null);
            continue;
        }
        let roll = rng.below(100);
        let null = if NULL_HEAVY_BLOCKS.contains(&b) { roll < 40 } else { roll < 2 };
        if null {
            amount.push(Value::Null);
            continue;
        }
        let a = rng.below(100) as i64;
        amount.push(Value::Int(a * a + rng.below(10) as i64));
    }

    Corpus { ts, status, region, amount, block_region }
}

/// Build the student store: the four columns, in row order.
fn build_store(c: &Corpus) -> ColumnStore {
    let mut store = ColumnStore::new();
    for name in ["ts", "status", "region", "amount"] {
        store.add_column(name, c.col(name));
    }
    store
}

/* ------------------ row-store reference + zone canon ---------------- */

/// The reference predicate, row at a time — lab 05's three-valued logic:
/// any comparison touching NULL (or a type mismatch) is UNKNOWN → false.
fn ref_matches(p: &Pred, v: &Value) -> bool {
    fn like(a: &Value, b: &Value) -> bool {
        matches!(
            (a, b),
            (Value::Int(_), Value::Int(_)) | (Value::Text(_), Value::Text(_))
        )
    }
    match p {
        Pred::Eq(w) => like(v, w) && v == w,
        Pred::Lt(w) => like(v, w) && v < w,
        Pred::Le(w) => like(v, w) && v <= w,
        Pred::Gt(w) => like(v, w) && v > w,
        Pred::Ge(w) => like(v, w) && v >= w,
        Pred::Between(lo, hi) => like(v, lo) && like(v, hi) && v >= lo && v <= hi,
    }
}

/// The naive row store: every row, both columns, no zones, no skipping.
/// Answers are exact; its cost model is "read everything, always".
fn reference(c: &Corpus, col_filter: &str, p: &Pred, col_sum: &str) -> (u64, i128) {
    let f = c.col(col_filter);
    let s = c.col(col_sum);
    let (mut rows, mut sum) = (0u64, 0i128);
    for i in 0..f.len() {
        if ref_matches(p, &f[i]) {
            rows += 1;
            if let Value::Int(x) = s[i] {
                sum += x as i128;
            }
        }
    }
    (rows, sum)
}

/// The canonical zone of a raw block: min/max over NON-NULL values.
fn canonical_zone(values: &[Value]) -> Zone {
    let mut z = Zone { rows: values.len() as u32, nulls: 0, min: None, max: None };
    for v in values {
        if matches!(v, Value::Null) {
            z.nulls += 1;
            continue;
        }
        z.min = Some(match z.min {
            None => v.clone(),
            Some(m) if *v < m => v.clone(),
            Some(m) => m,
        });
        z.max = Some(match z.max {
            None => v.clone(),
            Some(m) if *v > m => v.clone(),
            Some(m) => m,
        });
    }
    z
}

/// The canonical skip rule — the one the student's Zone::may_match must
/// implement, and the one every blocks_read expectation below is built from.
fn canonical_may_match(z: &Zone, p: &Pred) -> bool {
    let (min, max) = match (&z.min, &z.max) {
        (Some(min), Some(max)) => (min, max),
        _ => return false,
    };
    match p {
        Pred::Eq(w) => !matches!(w, Value::Null) && min <= w && w <= max,
        Pred::Lt(w) => min < w,
        Pred::Le(w) => min <= w,
        Pred::Gt(w) => max > w,
        Pred::Ge(w) => max >= w,
        Pred::Between(lo, hi) => !(max < lo || min > hi),
    }
}

/// What a correct zone-guided scan reads for this query: the filter block
/// iff its zone cannot rule the predicate out; the sum block iff the filter
/// block was read AND at least one row truly survives (late materialization
/// — an empty mask costs no second read). Same column: decoded once.
fn canonical_blocks_read(c: &Corpus, col_filter: &str, p: &Pred, col_sum: &str) -> u32 {
    let mut n = 0;
    for b in 0..c.n_blocks() {
        let fb = c.block(col_filter, b);
        if !canonical_may_match(&canonical_zone(fb), p) {
            continue;
        }
        n += 1;
        let any_hit = fb.iter().any(|v| ref_matches(p, v));
        if any_hit && col_filter != col_sum {
            n += 1;
        }
    }
    n
}

/* --------------------------- pinned sizes --------------------------- */

/// The tape measure from column.rs — the harness owns it, so a lossy or
/// imaginary encoding cannot lie about its size.
fn value_size(v: &Value) -> usize {
    1 + match v {
        Value::Null => 0,
        Value::Int(_) => 8,
        Value::Text(s) => 2 + s.len(),
    }
}

fn pinned_size(b: &Block) -> usize {
    match b {
        Block::Raw { values } => 4 + values.iter().map(value_size).sum::<usize>(),
        Block::Dict { dict, codes } => {
            4 + 2 + dict.iter().map(value_size).sum::<usize>() + 2 * codes.len()
        }
        Block::Rle { runs } => 4 + 2 + runs.iter().map(|(v, _)| value_size(v) + 4).sum::<usize>(),
    }
}

/// The Raw size of a raw value slice — what an uncompressed block costs.
fn raw_size(values: &[Value]) -> usize {
    4 + values.iter().map(value_size).sum::<usize>()
}

/* ---------------------------- CALIBRATION ---------------------------
 * Measured on the reference solution (labs/_solutions/columnar), this
 * corpus, native x86-64, 2026-08. Bytes are the pinned formula above.
 *
 *   column    encoded     raw       ratio   why
 *   ts        227,546     450,100   1.98x   RLE: ~65% repeated ticks
 *   status    101,700     430,066   4.23x   dictionary: 7 entries, u16 codes
 *   region        400     300,100   750x    RLE: ONE run per block (clustered)
 *   amount    261,371     397,604   1.52x   dictionary wins on the zipf skew
 *   TOTAL     591,017   1,577,870   2.67x
 *
 * BAND_LO/HI = REF_TOTAL × 0.85 / 1.25, integer math. A correct
 * choose_encoding lands exactly on REF_TOTAL: every block takes its
 * smallest pinned encoding, and ties are equal bytes. The low side exists
 * to catch lossy cheats — nothing honest is smaller than the minimum.
 */
const REF_TOTAL: usize = 591_017;
const BAND_LO: usize = REF_TOTAL * 85 / 100;
const BAND_HI: usize = REF_TOTAL * 125 / 100;

/* ------------------------------ checks ------------------------------ */

/// 1. encode_roundtrip: every codec is a byte-exact bijection — on a
///    synthetic battery (empty, constant, all-NULL, alternating, peppered),
///    on every block of every corpus column, and through the store itself.
///    A constant block must come back as ONE RLE run.
pub fn check_encode_roundtrip() -> Check {
    const ID: &str = "encode_roundtrip";
    const LABEL: &str = "dictionary + RLE round-trip is byte-exact";

    let constant: Vec<Value> = (0..BLOCK).map(|_| Value::Text("paid".to_string())).collect();
    let all_null: Vec<Value> = (0..BLOCK).map(|_| Value::Null).collect();
    let alternating: Vec<Value> =
        (0..BLOCK).map(|i| Value::Int((i % 2) as i64)).collect();
    let peppered: Vec<Value> = (0..BLOCK)
        .map(|i| if i % 3 == 1 { Value::Null } else { Value::Int(i as i64) })
        .collect();
    let runs_of_three: Vec<Value> =
        (0..BLOCK).map(|i| Value::Int(1_752_200_000_000 + (i / 3) as i64)).collect();
    let battery: Vec<(&str, Vec<Value>)> = vec![
        ("the empty block", vec![]),
        ("a single value", vec![Value::Int(42)]),
        ("the constant block", constant.clone()),
        ("the all-NULL block", all_null.clone()),
        ("alternating pairs", alternating),
        ("peppered with NULLs", peppered.clone()),
        ("runs of three", runs_of_three),
    ];

    for (name, values) in &battery {
        for (enc_name, block) in [
            ("Raw", column::encode_raw(values)),
            ("Dict", column::encode_dict(values)),
            ("Rle", column::encode_rle(values)),
            ("choose_encoding", column::choose_encoding(values)),
        ] {
            let got = column::decode(&block);
            if got != *values {
                return Check::fail(ID, LABEL, format!(
                    "{name} via {enc_name}: decoded {} values, {} went in{} — decode(encode(x)) == x, byte-exact, is the whole contract; a lossy column store is a bug farm",
                    got.len(),
                    values.len(),
                    if got.len() == values.len() { ", and some value differs" } else { "" }));
            }
        }
    }

    // the constant block is ONE run — if your RLE does not merge adjacent
    // equals it is not RLE, it is a noisier Raw
    match column::choose_encoding(&constant) {
        Block::Rle { ref runs } if runs.len() == 1 && runs[0].1 == BLOCK as u32 => {}
        Block::Rle { ref runs } => {
            return Check::fail(ID, LABEL, format!(
                "the constant block encoded as {} runs — maximal runs merge adjacent equals: a constant block is exactly ONE (value, {BLOCK}) run",
                runs.len()));
        }
        other => {
            return Check::fail(ID, LABEL, format!(
                "the constant block chose {other:?} — one RLE run is 16 bytes against thousands; choose_encoding picks the smallest pinned size"));
        }
    }

    // zone_of on the synthetic edge cases: NULLs are counted, never min/max
    let z = column::zone_of(&all_null);
    if z.min.is_some() || z.max.is_some() || z.nulls != BLOCK as u32 || z.rows != BLOCK as u32 {
        return Check::fail(ID, LABEL, format!(
            "zone_of(the all-NULL block) = rows {}, nulls {}, min {:?}, max {:?} — want rows {BLOCK}, nulls {BLOCK}, min/max None: min/max are over NON-NULL values, and an all-NULL block has none",
            z.rows, z.nulls, z.min, z.max));
    }
    let z = column::zone_of(&peppered);
    let want_nulls = peppered.iter().filter(|v| matches!(v, Value::Null)).count() as u32;
    if z.nulls != want_nulls || z.min != Some(Value::Int(0)) || z.max != Some(Value::Int((BLOCK - 2) as i64)) {
        return Check::fail(ID, LABEL, format!(
            "zone_of(peppered) = nulls {}, min {:?}, max {:?} — want nulls {want_nulls}, min Int(0), max Int({}): NULLs sit out of min/max entirely",
            z.nulls, z.min, z.max, BLOCK - 2));
    }

    // the corpus itself: every column × every block × every encoder
    let c = corpus();
    for name in ["ts", "status", "region", "amount"] {
        for b in 0..c.n_blocks() {
            let values = c.block(name, b);
            for (enc_name, block) in [
                ("Raw", column::encode_raw(values)),
                ("Dict", column::encode_dict(values)),
                ("Rle", column::encode_rle(values)),
                ("choose_encoding", column::choose_encoding(values)),
            ] {
                if column::decode(&block) != values {
                    return Check::fail(ID, LABEL, format!(
                        "column {name}, block {b} via {enc_name}: the round-trip changed the values — NULLs and repeated values are the usual suspects"));
                }
            }
        }
    }

    // and through the store: add_column must store blocks that decode back
    let store = build_store(&c);
    for name in ["ts", "status", "region", "amount"] {
        let blocks = store.blocks(name);
        if blocks.len() != c.n_blocks() {
            return Check::fail(ID, LABEL, format!(
                "store.blocks({name:?}) holds {} blocks, want {} — one compressed block per {BLOCK} values, short block included",
                blocks.len(), c.n_blocks()));
        }
        for (b, block) in blocks.iter().enumerate() {
            if column::decode(block) != c.block(name, b) {
                return Check::fail(ID, LABEL, format!(
                    "the store's {name} block {b} does not decode back to what add_column was given — the store compresses, it never alters"));
            }
        }
    }

    Check::pass(ID, LABEL, format!(
        "3 encodings + choose_encoding byte-exact on 7 synthetic blocks and {} columns × {} blocks; a constant block is one RLE run; NULLs survive every codec",
        4, c.n_blocks()))
}

/// 2. zone_skip: the store's zones equal the canonical min/max/nulls on
///    every block, and engineered predicates read EXACTLY the blocks the
///    canonical zones admit — no more (you decoded a condemned block), no
///    fewer (you skipped survivors).
pub fn check_zone_skip() -> Check {
    const ID: &str = "zone_skip";
    const LABEL: &str = "min-max zones skip exactly the blocks they should";
    let c = corpus();
    let mut store = build_store(&c);

    // part 1: zone structure, block by block
    for name in ["ts", "status", "region", "amount"] {
        let zones = store.zones(name);
        if zones.len() != c.n_blocks() {
            return Check::fail(ID, LABEL, format!(
                "zones({name:?}) has {} entries, want {} — one zone per block",
                zones.len(), c.n_blocks()));
        }
        for b in 0..c.n_blocks() {
            let want = canonical_zone(c.block(name, b));
            let z = &zones[b];
            if *z != want {
                return Check::fail(ID, LABEL, format!(
                    "{name} block {b}: your zone is (rows {}, nulls {}, min {:?}, max {:?}), the block holds (rows {}, nulls {}, min {:?}, max {:?}) — min/max run over NON-NULL values only",
                    z.rows, z.nulls, z.min, z.max, want.rows, want.nulls, want.min, want.max));
            }
        }
    }

    // part 2: behavior. (filter col, pred, sum col, story) — the expected
    // blocks_read is computed from the canonical zones, not guessed.
    let lo = c.t_min().max(match c.block("ts", 10)[0] {
        Value::Int(t) => t,
        _ => unreachable!(),
    });
    let hi = match c.block("ts", 12).last() {
        Some(Value::Int(t)) => *t,
        _ => unreachable!(),
    };
    let queries: Vec<(&str, Pred, &str, String)> = vec![
        ("region", Pred::Eq(Value::Text(region_name(3))), "amount",
         "region 'r03' lives in exactly 3 blocks (the column is physically clustered, so min == max proves it); the scan owes 3 filter reads + 3 sum reads and nothing else".to_string()),
        ("region", Pred::Eq(Value::Text(region_name(0))), "amount",
         "region 'r00' lives in exactly 1 block".to_string()),
        ("region", Pred::Eq(Value::Text("r42".to_string())), "amount",
         "'r42' exists in NO block — a value the zones have never seen costs zero reads; the zone map answers the whole query".to_string()),
        ("ts", Pred::Between(Value::Int(lo), Value::Int(hi)), "amount",
         format!("ts BETWEEN {lo} AND {hi} is the span of blocks 10–12; on a monotone column the zones bracket it tightly")),
        ("amount", Pred::Ge(Value::Int(0)), "amount",
         "amount >= 0 matches everything non-NULL — but the two outage blocks (9 and 17) are all-NULL: their zones have no min/max at all, and no comparison matches NULL. Same column for filter and sum: decode once, count once".to_string()),
        ("region", Pred::Le(Value::Text(region_name(2))), "amount",
         "region <= 'r02' covers 'r00'..'r02' — 1 + 2 + 1 = 4 blocks".to_string()),
    ];
    for (f, p, s, story) in &queries {
        let want = canonical_blocks_read(&c, f, p, s);
        let (rows, sum, got) = store.scan_filter_sum(f, p, s);
        if got != want {
            return Check::fail(ID, LABEL, format!(
                "{story}.\nThe canonical zones read exactly {want} blocks; you read {got} — {}",
                if got > want {
                    "you decoded blocks the zone map had already condemned. Zone check FIRST, decode SECOND — and the sum block only when the mask is non-empty"
                } else {
                    "you read fewer blocks than hold survivors — a zone that skips a matching block is a wrong answer waiting to happen"
                }));
        }
        let (want_rows, want_sum) = reference(&c, f, p, s);
        if rows != want_rows || sum != want_sum {
            return Check::fail(ID, LABEL, format!(
                "{story}.\nSkipping was exact, but the answer is (rows {rows}, sum {sum}) vs the row store's (rows {want_rows}, sum {want_sum}) — the mask and the aggregate must agree with the naive scan"));
        }
    }
    Check::pass(ID, LABEL, format!(
        "zones canonical on all {} blocks; 6 engineered predicates read exactly their survivors' blocks — including 0 for a value that does not exist",
        4 * c.n_blocks()))
}

/// 3. vectorized_ops: scripted filter+sum queries against the row-store
///    reference. rows_matched and sum, exact — NULL semantics included.
pub fn check_vectorized_ops() -> Check {
    const ID: &str = "vectorized_ops";
    const LABEL: &str = "batched filter + sum over compressed columns, exact";
    let c = corpus();
    let mut store = build_store(&c);
    let ts_at = |row: usize| match c.ts[row] {
        Value::Int(t) => t,
        _ => unreachable!(),
    };
    let queries: Vec<(&str, Pred, &str, &str)> = vec![
        ("status", Pred::Eq(Value::Text("paid".to_string())), "amount",
         "the workhorse: equality on an UNCLUSTERED column — zones cannot help, every status block is read, and the answer must still be exact"),
        ("status", Pred::Eq(Value::Text("disputed".to_string())), "amount", "the rarest status"),
        ("region", Pred::Eq(Value::Text(region_name(7))), "amount", "clustered equality"),
        ("region", Pred::Le(Value::Text(region_name(2))), "amount", "a string range — comparisons are like-typed, Text orders lexicographically"),
        ("ts", Pred::Between(Value::Int(ts_at(45_000)), Value::Int(ts_at(49_000))), "amount", "a narrow time window"),
        ("ts", Pred::Ge(Value::Int(ts_at(30_000))), "amount", "everything since a cutoff — the dashboard query"),
        ("amount", Pred::Gt(Value::Int(9000)), "amount", "the big spenders — filter and sum are the SAME column: decode once, count once"),
        ("amount", Pred::Between(Value::Int(0), Value::Int(9)), "amount", "dust amounts — crosses the NULL-heavy blocks 5–6; NULLs never match, and SUM never adds them"),
        ("amount", Pred::Eq(Value::Null), "amount", "amount = NULL matches NOTHING: SQL is three-valued, UNKNOWN is not true — lab 05's rule, turned sideways"),
        ("status", Pred::Eq(Value::Text("failed".to_string())), "ts", "the sum column is yours to choose — here it is ts"),
        ("ts", Pred::Lt(Value::Int(0)), "amount", "an impossible predicate: the empty stream is not an error"),
        ("region", Pred::Eq(Value::Text("r42".to_string())), "amount", "a value that does not exist"),
    ];
    for (i, (f, p, s, story)) in queries.iter().enumerate() {
        let (rows, sum, _) = store.scan_filter_sum(f, p, s);
        let (want_rows, want_sum) = reference(&c, f, p, s);
        if rows != want_rows {
            return Check::fail(ID, LABEL, format!(
                "q{i} ({story}): rows_matched {rows}, the row store says {want_rows}"));
        }
        if sum != want_sum {
            return Check::fail(ID, LABEL, format!(
                "q{i} ({story}): sum {sum}, the row store says {want_sum} (off by {:+}) — rows_matched counts every surviving position; the sum adds only the non-NULL Int values at those positions",
                sum - want_sum));
        }
    }
    Check::pass(ID, LABEL, format!(
        "{} scripted queries exact vs the row store — ranges, unclustered equality, NULL-heavy blocks, the NULL predicate, the empty stream",
        queries.len()))
}

/// 4. compression_band: the seeded corpus, as YOUR store encoded it, inside
///    the calibrated band (see CALIBRATION above — measured on the reference
///    build, not guessed).
pub fn check_compression_band() -> Check {
    const ID: &str = "compression_band";
    const LABEL: &str = "ratio within the calibrated band on the seeded corpus";
    let c = corpus();
    let store = build_store(&c);
    let mut total = 0usize;
    let mut raw_total = 0usize;
    let mut per_column = String::new();
    for name in ["ts", "status", "region", "amount"] {
        let enc: usize = store.blocks(name).iter().map(pinned_size).sum();
        let raw: usize = (0..c.n_blocks()).map(|b| raw_size(c.block(name, b))).sum();
        total += enc;
        raw_total += raw;
        if !per_column.is_empty() {
            per_column.push_str(", ");
        }
        // integer tenths for the ratio — no floats, native ≡ wasm
        per_column.push_str(&format!("{name} {enc} B vs {raw} B raw ({}.{:01}x)", raw / enc.max(1), (raw * 10 / enc.max(1)) % 10));
    }
    if total > BAND_HI {
        return Check::fail(ID, LABEL, format!(
            "your store holds the corpus in {total} bytes — the calibrated band is [{BAND_LO}, {BAND_HI}] (reference {REF_TOTAL}, raw {raw_total}). Per column: {per_column}. A column store that does not compress is a row store with extra steps: choose_encoding must take the SMALLEST pinned encoding per block — dictionary for the few-distinct columns, RLE for the runs"));
    }
    if total < BAND_LO {
        return Check::fail(ID, LABEL, format!(
            "your store claims {total} bytes — below the calibrated floor {BAND_LO}: smaller than every honest encoding of this corpus. Compression is a bijection: decode() must return every value back, byte-exact. Smaller-than-minimum is not compression, it is data loss"));
    }
    Check::pass(ID, LABEL, format!(
        "{total} bytes where raw is {raw_total} — inside the band around the reference {REF_TOTAL}. Per column: {per_column}"))
}

/// 5. storm: 300 seeded mixed queries — varied selectivities, present and
///    absent values, NULL-heavy regions — each graded twice: the answer
///    equals the row store's, and blocks_read stays under the canonical-zone
///    ceiling. Zones that are decoration fail the ceiling; zones that lie
///    fail the answer.
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "mixed query storm vs a row-store reference model";
    const QUERIES: usize = 300;
    let c = corpus();
    let mut store = build_store(&c);
    let mut rng = Rng(0x5EED_090B);
    let span = (c.t_max() - c.t_min()) as usize;
    let mut total_read = 0u64;
    for q in 0..QUERIES {
        let (f, p, s, desc): (&str, Pred, &str, String) = match rng.below(100) {
            0..=24 => {
                let r = region_name(rng.below(16));
                ("region", Pred::Eq(Value::Text(r.clone())), "amount", format!("region = '{r}'"))
            }
            25..=39 => {
                let r = format!("r{:02}", 16 + rng.below(27)); // r16..r42: never present
                ("region", Pred::Eq(Value::Text(r.clone())), "amount", format!("region = '{r}' (absent)"))
            }
            40..=51 => {
                let st = STATUSES[rng.below(6)];
                ("status", Pred::Eq(Value::Text(st.to_string())), "amount", format!("status = '{st}'"))
            }
            52..=76 => {
                let lo = c.t_min() + rng.below(span) as i64;
                let width = match rng.below(10) {
                    0 => rng.below(50),
                    1..=5 => span / 20,
                    _ => span / 3,
                };
                let hi = (lo + width as i64).min(c.t_max());
                ("ts", Pred::Between(Value::Int(lo), Value::Int(hi)), "amount", format!("ts BETWEEN {lo} AND {hi}"))
            }
            77..=86 => {
                let a = rng.below(9000) as i64;
                ("amount", Pred::Gt(Value::Int(a)), "amount", format!("amount > {a} (same column)"))
            }
            87..=91 => {
                let lo = rng.below(9000) as i64;
                let hi = lo + rng.below(500) as i64;
                ("amount", Pred::Between(Value::Int(lo), Value::Int(hi)), "amount", format!("amount BETWEEN {lo} AND {hi} (same column)"))
            }
            _ => {
                // the NULL-heavy regions: whoever owns the outage blocks
                let r = region_name(c.block_region[OUTAGE_BLOCKS[q % 2]]);
                ("region", Pred::Eq(Value::Text(r.clone())), "amount", format!("region = '{r}' (owns an outage block)"))
            }
        };
        let (rows, sum, read) = store.scan_filter_sum(f, &p, s);
        total_read += read as u64;
        let (want_rows, want_sum) = reference(&c, f, &p, s);
        if rows != want_rows || sum != want_sum {
            return Check::fail(ID, LABEL, format!(
                "query {q} ({desc}): you answered (rows {rows}, sum {sum}), the row store says (rows {want_rows}, sum {want_sum}) — the storm tolerates no drift: same questions, same answers, fewer reads"));
        }
        let ceiling = canonical_blocks_read(&c, f, &p, s);
        if read > ceiling {
            return Check::fail(ID, LABEL, format!(
                "query {q} ({desc}): you read {read} blocks, the canonical zones need {ceiling} — your zones are leaking reads. The order is: zone check (free) → decode the filter block → decode the sum block ONLY when the selection mask is non-empty (and never twice when filter == sum)"));
        }
    }
    let row_store_reads = QUERIES as u64 * c.n_blocks() as u64;
    Check::pass(ID, LABEL, format!(
        "{QUERIES} seeded queries, every answer exact vs the row store, every scan under its zone ceiling — you read {total_read} blocks where the row store pays {row_store_reads} block-reads ({}.{:01}%): the T7 thesis, graded",
        total_read * 100 / row_store_reads,
        (total_read * 1000 / row_store_reads) % 10))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_encode_roundtrip(),
        check_zone_skip(),
        check_vectorized_ops(),
        check_compression_band(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "columnar", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
