/**
 * gen-public-trace — emit the tablespace PUBLIC trace: a seeded,
 * TPC-C-shaped page-reference stream shared by two consumers:
 *
 *   1. The Engine (site sim) — reads public/traces/bp-public-trace.json
 *   2. The buffer-pool lab harness — embeds labs/buffer-pool/src/public_trace.rs
 *
 * Both files are generated HERE so they can never drift. Deterministic:
 * xorshift32, integer math only. Re-run after changing shape constants.
 *
 *   bun scripts/gen-public-trace.ts
 */

import { writeFileSync, mkdirSync } from 'fs'

const SEED = 0x7acc01
const PAGES = 10_000
const REFS = 12_000

/* TPC-C shape, honestly labeled: payment/new-order traffic hammers a tiny
 * warehouse+district hot set; order-line lookups form a skewed mid set;
 * item/stock reads are near-uniform; a periodic stock-level scan floods. */
const HOT_PAGES = 200 // warehouse+district rows: 2% of pages
const MID_PAGES = 2_000 // order-line/items mid set
const FLOOD_EVERY = 800
const FLOOD_LEN = 140

function xorshift32(state: { s: number }): number {
  let x = state.s >>> 0
  x ^= x << 13; x >>>= 0
  x ^= x >> 17
  x ^= x << 5; x >>>= 0
  state.s = x
  return x
}

// zipf-ish rank: r = floor(exp(u * ln(max))) - 1, u∈[0,1) → heavy head
function zipfRank(st: { s: number }, max: number): number {
  const u = xorshift32(st) / 0x1_0000_0000
  return Math.min(max - 1, Math.floor(Math.exp(u * Math.log(max))) - 1)
}

const st = { s: SEED }
const refs: number[] = []
let floodCursor = 0
let sinceFlood = 0

for (let i = 0; i < REFS; i++) {
  sinceFlood++
  if (sinceFlood >= FLOOD_EVERY && i + FLOOD_LEN <= REFS) {
    // stock-level scan: a sequential burst through cold pages
    for (let j = 0; j < FLOOD_LEN; j++) {
      refs.push(floodCursor)
      floodCursor = (floodCursor + 1) % PAGES
      i++
    }
    sinceFlood = 0
    continue
  }
  const roll = xorshift32(st) % 100
  if (roll < 45) {
    refs.push(zipfRank(st, HOT_PAGES)) // hot set: pages 0..199
  } else if (roll < 80) {
    refs.push(HOT_PAGES + zipfRank(st, MID_PAGES)) // mid set: 200..2199
  } else {
    refs.push(xorshift32(st) % PAGES) // uniform background
  }
}

const json = {
  name: 'bp-public-trace',
  shape: 'tpcc-shaped: 45% hot(200p) 35% zipf-mid(2000p) 20% uniform + 140-ref flood every 800',
  seed: SEED,
  pages: PAGES,
  refs,
}

mkdirSync('public/traces', { recursive: true })
writeFileSync('public/traces/bp-public-trace.json', JSON.stringify(json))

const rust = `//! GENERATED by scripts/gen-public-trace.ts — do not edit by hand.
//! The public leaderboard trace (TPC-C-shaped). The Engine serves the same
//! stream from public/traces/bp-public-trace.json; the two are one source.

pub const PUBLIC_TRACE_PAGES: u32 = ${PAGES};
pub const PUBLIC_TRACE: [u32; ${refs.length}] = [
${Array.from({ length: Math.ceil(refs.length / 16) }, (_, i) => `    ${refs.slice(i * 16, i * 16 + 16).join(', ')},`).join('\n')}
];
`
writeFileSync('labs/buffer-pool/src/public_trace.rs', rust)

console.log(`trace: ${refs.length} refs over ${PAGES} pages, seed 0x${SEED.toString(16)}`)
console.log('wrote public/traces/bp-public-trace.json + labs/buffer-pool/src/public_trace.rs')
