//! slotted-pages — forge lab 01 (tablespace).
//!
//! The atom of the whole engine: one 8192-byte slotted page. Header up
//! front, slot array growing down, record bytes growing up, free space in
//! the middle — and bookkeeping that must be exact to the byte. Lab 02
//! hangs a B+tree on these pages; lab 03 makes them durable.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/page.rs        (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The ops: insert / read / delete / defrag / free_space (plus slot_range,
//! the checker's window into your layout). The hard parts:
//!   * free_space() is a number you MAINTAIN, not a hope: it must equal the
//!     reference books after every single op, to the byte.
//!   * delete frees accounting immediately but the bytes only at defrag;
//!     insert draws from the contiguous region alone.
//!   * defrag moves records but must never change what a live slot id reads.

mod page;

use kslab::{Check, Report};
use page::{Page, HEADER_SIZE, PAGE_SIZE, SLOT_SIZE};

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
    fn bytes(&mut self, n: usize) -> Vec<u8> {
        (0..n).map(|_| (self.next() >> 32) as u8).collect()
    }
}

/* ------------------------- reference books -------------------------- */

/// The accounting contract from page.rs, kept by the harness. `free()` must
/// equal `page.free_space()` after EVERY op — to the byte.
struct Books {
    contiguous: usize, // the middle region: [8 + slots*6, records_start)
    dead: usize,       // record bytes marked dead, awaiting defrag
    live: usize,       // live slot count
    tombstones: usize, // dead slots an insert may reuse
}

impl Books {
    fn new() -> Books {
        Books { contiguous: PAGE_SIZE - HEADER_SIZE, dead: 0, live: 0, tombstones: 0 }
    }
    fn free(&self) -> usize {
        self.contiguous + self.dead
    }
    /// Mirrors the insert contract: reuse a tombstone if one exists (claims
    /// no slot bytes), else append a slot. Record bytes come from the
    /// contiguous region alone; dead space waits for defrag.
    fn insert(&mut self, len: usize) -> bool {
        if len == 0 {
            return false;
        }
        let reuse = self.tombstones > 0;
        let need = len + if reuse { 0 } else { SLOT_SIZE };
        if self.contiguous < need {
            return false;
        }
        self.contiguous -= need;
        if reuse {
            self.tombstones -= 1;
        }
        self.live += 1;
        true
    }
    fn delete(&mut self, len: usize) {
        self.dead += len;
        self.tombstones += 1;
        self.live -= 1;
    }
    fn defrag(&mut self) {
        if self.live == 0 {
            *self = Books::new(); // no outstanding slot ids — back to mint
            return;
        }
        self.contiguous += self.dead;
        self.dead = 0;
    }
}

/* ------------------------------ checks ------------------------------ */

/// 1. insert_read: records of many sizes round-trip byte-exact; the page
///    refuses gracefully (None, no panic, no corruption) when full.
pub fn check_insert_read() -> Check {
    const ID: &str = "insert_read";
    const LABEL: &str = "records round-trip byte-exact";
    if std::mem::size_of::<Page>() != PAGE_SIZE {
        return Check::fail(ID, LABEL, format!(
            "size_of::<Page>() = {}, want {PAGE_SIZE} — all state lives in the page's own bytes (no side tables; lab 03 writes these bytes to disk)",
            std::mem::size_of::<Page>()));
    }
    let mut p = Page::new();
    if p.free_space() != PAGE_SIZE - HEADER_SIZE {
        return Check::fail(ID, LABEL, format!(
            "a fresh page has free_space {}, want {} (8192 minus the 8-byte header)",
            p.free_space(), PAGE_SIZE - HEADER_SIZE));
    }
    if p.read(0).is_some() {
        return Check::fail(ID, LABEL, "read on an empty page must be None");
    }
    if p.insert(b"").is_some() {
        return Check::fail(ID, LABEL, "0-byte records are not storable — insert must return None (a len-0 slot is how bugs hide)");
    }
    let mut rng = Rng(0x5EED_0001);
    let mut kept: Vec<(u16, Vec<u8>)> = Vec::new();
    // a deliberate spread: tiny, awkward, and a near-page-filling 4 KiB
    for (i, sz) in [1usize, 2, 3, 7, 13, 64, 255, 256, 777, 1024, 4096].into_iter().enumerate() {
        let rec = rng.bytes(sz);
        let id = match p.insert(&rec) {
            Some(id) => id,
            None => return Check::fail(ID, LABEL, format!("insert #{i} ({sz} B) refused on a page that must fit it")),
        };
        match p.read(id) {
            Some(got) if got == rec.as_slice() => {}
            Some(got) => return Check::fail(ID, LABEL, format!("slot {id}: inserted {sz} bytes, read back {}", got.len())),
            None => return Check::fail(ID, LABEL, format!("slot {id}: a live insert reads back None")),
        }
        kept.push((id, rec));
    }
    // fill to refusal: the page must say None eventually — and a refused
    // insert must change nothing
    let rec = rng.bytes(64);
    loop {
        match p.insert(&rec) {
            Some(id) => kept.push((id, rec.clone())),
            None => break,
        }
        if kept.len() > PAGE_SIZE {
            return Check::fail(ID, LABEL, "insert never says None — an 8192-byte page holding 8193 records is a neat trick");
        }
    }
    if p.insert(&vec![0u8; 4096]).is_some() {
        return Check::fail(ID, LABEL, "a 4 KiB record must not fit into the crumbs of a full page — insert must say None");
    }
    for (id, want) in &kept {
        match p.read(*id) {
            Some(got) if got == want.as_slice() => {}
            _ => return Check::fail(ID, LABEL, format!("slot {id} corrupted after the page filled up — a refused insert must change nothing")),
        }
    }
    Check::pass(ID, LABEL, format!("{} records byte-exact; refusal at capacity is clean", kept.len()))
}

/// 2. no_overlap: after a seeded mix of inserts/deletes/defrags, every pair
///    of live records occupies disjoint bytes inside the page body — and
///    every live slot still reads back what was inserted.
pub fn check_no_overlap() -> Check {
    const ID: &str = "no_overlap";
    const LABEL: &str = "no two live records overlap";
    let mut p = Page::new();
    let mut rng = Rng(0x5EED_0002);
    let mut live: Vec<(u16, Vec<u8>)> = Vec::new();
    for _ in 0..150 {
        match rng.below(100) {
            0..=54 => {
                let sz = 8 + rng.below(120);
                let rec = rng.bytes(sz);
                if let Some(id) = p.insert(&rec) {
                    live.push((id, rec));
                }
            }
            55..=84 => {
                if !live.is_empty() {
                    let (id, _) = live.swap_remove(rng.below(live.len()));
                    if !p.delete(id) {
                        return Check::fail(ID, LABEL, format!("delete of live slot {id} returned false"));
                    }
                }
            }
            _ => p.defrag(),
        }
    }
    if live.len() < 8 {
        return Check::fail(ID, LABEL, format!("only {} live records left — the page is losing records it should keep", live.len()));
    }
    let mut ranges: Vec<(u16, usize, usize)> = Vec::new();
    for (id, want) in &live {
        match p.read(*id) {
            Some(got) if got == want.as_slice() => {}
            _ => return Check::fail(ID, LABEL, format!("slot {id} no longer reads back what was inserted — something is writing over it")),
        }
        let (start, end) = match p.slot_range(*id) {
            Some(r) => r,
            None => return Check::fail(ID, LABEL, format!("slot_range({id}) is None for a live slot")),
        };
        if end <= start || start < HEADER_SIZE || end > PAGE_SIZE {
            return Check::fail(ID, LABEL, format!("slot {id} range [{start},{end}) escapes the page body"));
        }
        if end - start != want.len() {
            return Check::fail(ID, LABEL, format!("slot {id} range spans {} bytes, the record is {}", end - start, want.len()));
        }
        ranges.push((*id, start, end));
    }
    for a in 0..ranges.len() {
        for b in a + 1..ranges.len() {
            let (ia, sa, ea) = ranges[a];
            let (ib, sb, eb) = ranges[b];
            if sa < eb && sb < ea {
                return Check::fail(ID, LABEL, format!("overlap: slot {ia} range [{sa},{ea}) intersects slot {ib} [{sb},{eb})"));
            }
        }
    }
    Check::pass(ID, LABEL, format!("{} live records, all disjoint, all byte-exact", ranges.len()))
}

/// 3. freespace_accounting: a scripted scenario that walks every accounting
///    branch; after EVERY op free_space() must equal the books to the byte.
pub fn check_freespace_accounting() -> Check {
    const ID: &str = "freespace_accounting";
    const LABEL: &str = "free space exact after every insert/delete";

    #[derive(Debug)]
    enum Op {
        Ins(usize),   // insert a record of this many bytes
        Del(usize),   // delete the k-th live slot id (insertion order)
        DelSlot(u16), // delete this raw slot id — must be refused, no change
        Defrag,
    }
    use Op::*;

    let script = [
        Ins(100), Ins(200), Ins(1),
        Del(0),          // 100 B dies: free_space reflects dead bytes NOW
        Ins(50),         // reuses the tombstone — claims no slot bytes
        Del(0),          // the 200 B record dies
        Defrag,          // dead record bytes return to the contiguous region
        Ins(300), Ins(60),
        Del(3), Del(0),  // two more tombstones
        Ins(4000),       // a 4 KiB record through a reused slot
        Ins(3800),       // too big for what is left: None, books unchanged
        Ins(3700),       // just fits
        Ins(10),
        Ins(40),         // needs 46 contiguous, only 33 left: None
        Ins(20),         // needs 26: fits
        Del(5), Del(0),
        Defrag,          // live records stay put id-wise; dead bytes reclaimed
        Del(0), Del(0), Del(0), Del(0), // every record dies
        Defrag,          // zero live records: the page resets to mint
        Ins(64),
        Del(0),
        DelSlot(0),      // already dead: refused, no change
        DelSlot(9999),   // never existed: refused, no change
        Defrag,          // mint again
        Ins(0),          // empty record: refused
        Ins(8192),       // bigger than the page: refused
    ];

    let mut p = Page::new();
    let mut books = Books::new();
    let mut live: Vec<(u16, usize)> = Vec::new(); // (slot id, len), insertion order
    for (i, op) in script.iter().enumerate() {
        match *op {
            Ins(len) => {
                let fits = books.insert(len);
                let rec = vec![0xA5u8; len];
                match (p.insert(&rec), fits) {
                    (Some(id), true) => {
                        live.push((id, len));
                        if p.read(id) != Some(rec.as_slice()) {
                            return Check::fail(ID, LABEL, format!("op {i} Ins({len}): the fresh insert does not read back"));
                        }
                    }
                    (Some(id), false) => {
                        return Check::fail(ID, LABEL, format!("op {i} Ins({len}): returned Some({id}) but the books say it cannot fit — space from nowhere"));
                    }
                    (None, true) => {
                        return Check::fail(ID, LABEL, format!("op {i} Ins({len}): refused, but the books say it fits — check your contiguous-space test (and the tombstone-reuse rule)"));
                    }
                    (None, false) => {}
                }
            }
            Del(k) => {
                let (id, len) = live.remove(k);
                books.delete(len);
                if !p.delete(id) {
                    return Check::fail(ID, LABEL, format!("op {i} Del({k}) → slot {id}: delete of a live slot returned false"));
                }
                if p.read(id).is_some() {
                    return Check::fail(ID, LABEL, format!("op {i} Del({k}) → slot {id}: a dead slot must read None"));
                }
            }
            DelSlot(id) => {
                if p.delete(id) {
                    return Check::fail(ID, LABEL, format!("op {i}: delete of slot {id} (not live) returned true — dead/invalid deletes are refused, no change"));
                }
            }
            Defrag => {
                p.defrag();
                books.defrag();
                for (id, len) in &live {
                    match p.read(*id) {
                        Some(got) if got.len() == *len => {}
                        _ => return Check::fail(ID, LABEL, format!("op {i} Defrag: live slot {id} broke — defrag must not change what a live id reads")),
                    }
                }
            }
        }
        let (got, want) = (p.free_space(), books.free());
        if got != want {
            let diff = got as isize - want as isize;
            return Check::fail(ID, LABEL, format!(
                "op {i} {op:?}: free_space() = {got}, the books say {want} (off by {diff:+}) — {}",
                if diff > 0 { "promising bytes you do not have" } else { "bytes vanished, a leak" }));
        }
    }
    Check::pass(ID, LABEL, format!("{} scripted ops, books exact to the byte, page ends mint at {} free", script.len(), PAGE_SIZE - HEADER_SIZE))
}

/// 4. delete_reuse: fill the page, delete half, prove a big record is
///    refused while the space is dead-but-not-defragged, then prove defrag
///    makes it fit — with every survivor byte-exact.
pub fn check_delete_reuse() -> Check {
    const ID: &str = "delete_reuse";
    const LABEL: &str = "deleted space is reclaimable (defrag works)";
    let mut p = Page::new();
    let initial = PAGE_SIZE - HEADER_SIZE;
    let mut ids: Vec<(u16, Vec<u8>)> = Vec::new();
    loop {
        let rec = vec![(ids.len() % 250 + 1) as u8; 100];
        match p.insert(&rec) {
            Some(id) => ids.push((id, rec)),
            None => break,
        }
        if ids.len() > 1000 {
            return Check::fail(ID, LABEL, "insert never refuses — cannot fill the page");
        }
    }
    if p.free_space() * 10 > initial {
        return Check::fail(ID, LABEL, format!("the page refused with {} of {initial} bytes still free — under 90% full, so space is leaking per insert", p.free_space()));
    }
    let total = ids.len();
    let mut survivors: Vec<(u16, Vec<u8>)> = Vec::new();
    for (k, (id, rec)) in ids.into_iter().enumerate() {
        if k % 2 == 0 {
            if !p.delete(id) {
                return Check::fail(ID, LABEL, format!("delete of live slot {id} returned false"));
            }
            if p.read(id).is_some() || p.slot_range(id).is_some() {
                return Check::fail(ID, LABEL, format!("slot {id} deleted but still readable — a dead slot must be invisible"));
            }
        } else {
            survivors.push((id, rec));
        }
    }
    // free_space jumped (dead counts immediately) but the contiguous region
    // is still crumbs: a 512 B record must be REFUSED
    let big = vec![0xEEu8; 512];
    if p.insert(&big).is_some() {
        return Check::fail(ID, LABEL, "a 512 B record landed in dead space — deleted bytes are accounting-only until defrag makes them contiguous");
    }
    p.defrag();
    for (id, want) in &survivors {
        match p.read(*id) {
            Some(got) if got == want.as_slice() => {}
            _ => return Check::fail(ID, LABEL, format!("slot {id} changed across defrag — a live slot id must keep reading the same bytes")),
        }
    }
    match p.insert(&big) {
        Some(id) => {
            if p.read(id) != Some(big.as_slice()) {
                return Check::fail(ID, LABEL, "the post-defrag big record does not read back");
            }
        }
        None => return Check::fail(ID, LABEL, format!("defrag should have reclaimed ~{} B, but a 512 B record still does not fit", total / 2 * 100)),
    }
    Check::pass(ID, LABEL, format!("{total} records in, half deleted, defrag reclaimed the space, {} survivors byte-exact", survivors.len()))
}

/// 5. storm: 2000 seeded ops against the reference books + a slot model.
///    Byte-exact reads throughout, free_space exact after every op — and a
///    final defrag of an emptied page must return it to mint (leak check).
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "2000 ops vs a reference page model";
    let mut p = Page::new();
    let mut books = Books::new();
    let mut model: Vec<(u16, Vec<u8>)> = Vec::new();
    let mut rng = Rng(0x5EED);
    for i in 0..2000usize {
        match rng.below(100) {
            0..=54 => {
                let sz = 8 + rng.below(193); // 8..=200 B
                let rec = rng.bytes(sz);
                let fits = books.insert(rec.len());
                match (p.insert(&rec), fits) {
                    (Some(id), true) => model.push((id, rec)),
                    (Some(id), false) => return Check::fail(ID, LABEL, format!("op {i}: insert of {} B returned Some({id}) but the contiguous region was too small — space from nowhere means overlap", rec.len())),
                    (None, true) => return Check::fail(ID, LABEL, format!("op {i}: insert of {} B refused but the books say it fits", rec.len())),
                    (None, false) => {}
                }
            }
            55..=89 => {
                if !model.is_empty() {
                    let k = rng.below(model.len());
                    let (id, rec) = model.swap_remove(k);
                    books.delete(rec.len());
                    if !p.delete(id) {
                        return Check::fail(ID, LABEL, format!("op {i}: delete of live slot {id} returned false"));
                    }
                }
            }
            _ => {
                p.defrag();
                books.defrag();
                for (id, want) in model.iter().take(6) {
                    match p.read(*id) {
                        Some(got) if got == want.as_slice() => {}
                        _ => return Check::fail(ID, LABEL, format!("op {i}: defrag changed what live slot {id} reads")),
                    }
                }
            }
        }
        let (got, want) = (p.free_space(), books.free());
        if got != want {
            return Check::fail(ID, LABEL, format!("op {i}: free_space() = {got}, the books say {want} (off by {:+}) — every byte accounted for, every op", got as isize - want as isize));
        }
        if i % 250 == 0 {
            for (id, want) in &model {
                match p.read(*id) {
                    Some(got) if got == want.as_slice() => {}
                    _ => return Check::fail(ID, LABEL, format!("op {i}: slot {id} no longer reads back its record")),
                }
            }
        }
    }
    // final reckoning: every live record matches the model, no two overlap
    let mut ranges: Vec<(u16, usize, usize)> = Vec::new();
    for (id, want) in &model {
        match p.read(*id) {
            Some(got) if got == want.as_slice() => {}
            _ => return Check::fail(ID, LABEL, format!("after the storm: slot {id} lost or changed its record")),
        }
        match p.slot_range(*id) {
            Some((s, e)) if e - s == want.len() && s >= HEADER_SIZE && e <= PAGE_SIZE => ranges.push((*id, s, e)),
            _ => return Check::fail(ID, LABEL, format!("after the storm: slot_range({id}) is wrong for a live slot")),
        }
    }
    for a in 0..ranges.len() {
        for b in a + 1..ranges.len() {
            let (ia, sa, ea) = ranges[a];
            let (ib, sb, eb) = ranges[b];
            if sa < eb && sb < ea {
                return Check::fail(ID, LABEL, format!("after the storm — overlap: slot {ia} range [{sa},{ea}) intersects slot {ib} [{sb},{eb})"));
            }
        }
    }
    // ...then every record dies, one defrag runs, and the page must be mint
    for (id, _) in model.drain(..) {
        if !p.delete(id) {
            return Check::fail(ID, LABEL, format!("final sweep: delete of live slot {id} refused"));
        }
    }
    p.defrag();
    let mint = PAGE_SIZE - HEADER_SIZE;
    if p.free_space() != mint {
        return Check::fail(ID, LABEL, format!("leak: an empty, defragged page has {} free bytes, want {mint} — {} bytes never came back", p.free_space(), mint as isize - p.free_space() as isize));
    }
    Check::pass(ID, LABEL, "2000 ops model-exact; the page ends mint — not one leaked byte")
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_insert_read(),
        check_no_overlap(),
        check_freespace_accounting(),
        check_delete_reuse(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "slotted-pages", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
