//! hnsw — forge lab 06 (tablespace). The capstone.
//!
//! Every lab before this one graded something exact: bytes, order,
//! durability, visibility. This one grades APPROXIMATION — and the honest
//! way to grade approximation is to measure. The corpus is seeded, the
//! truth is brute force, latency is a distance-computation count on the
//! Meter, and every band below was calibrated against the reference
//! solution's measured numbers, never guessed (see the CALIBRATION block).
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/hnsw.rs       (the only file with TODO(you))  │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The five checks, in grading order:
//!   * graph_invariants — structural proof: caps, symmetry, reachability.
//!   * recall_band      — mean recall@10 over 50 seeded queries, in a band.
//!   * latency_win      — mean metered distances/query vs the exact scan.
//!   * planner_choice   — choose_index matches the cost verdict on a grid.
//!   * curve            — your build dominates a naive one on (recall, cost).

mod hnsw;

use hnsw::{choose_index, Hnsw, Meter};
use kslab::{Check, Report};

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
    /// Uniform in [lo, hi) from integer bits — no transcendentals, so the
    /// corpus is bit-identical on native and wasm.
    fn uniform(&mut self, lo: f32, hi: f32) -> f32 {
        const S: f32 = 1.0 / (1u64 << 24) as f32;
        lo + (hi - lo) * ((self.next() >> 40) as f32 * S)
    }
    /// Approximate N(0,1): Irwin–Hall (sum of 12 uniforms, minus 6).
    /// Distribution-free determinism — no sin/cos/ln across libm's.
    fn gauss(&mut self) -> f32 {
        const S: f32 = 1.0 / (1u64 << 24) as f32;
        let mut s = 0.0f32;
        for _ in 0..12 {
            s += (self.next() >> 40) as f32 * S;
        }
        s - 6.0
    }
}

/* ----------------------------- corpus ------------------------------- */

const DIM: usize = 32;
const N_VECTORS: usize = 4000;
const N_CLUSTERS: usize = 12;
const N_QUERIES: usize = 50;
const K: usize = 10;

/// Squared L2 — the harness's own copy for ground truth. Unmetered: the
/// exact scan's cost is N_VECTORS per query by definition.
fn l2(a: &[f32], b: &[f32]) -> f32 {
    a.iter().zip(b).map(|(x, y)| (x - y) * (x - y)).sum()
}

struct Corpus {
    vectors: Vec<Vec<f32>>,
    queries: Vec<Vec<f32>>,
    truth: Vec<Vec<u32>>, // exact top-K ids per query, (dist asc, id asc)
}

/// The seeded corpus: ~4000 vectors in 32 dimensions from 12 gaussian
/// clusters plus uniform noise; 50 queries — 40 near cluster centers, 10
/// uniform outliers. Bit-identical on native and wasm (integer-derived
/// floats only).
fn corpus() -> Corpus {
    let mut rng = Rng(0x5EED_0606);
    let centers: Vec<Vec<f32>> = (0..N_CLUSTERS)
        .map(|_| (0..DIM).map(|_| rng.uniform(-7.0, 7.0)).collect())
        .collect();
    let mut vectors = Vec::with_capacity(N_VECTORS);
    for _ in 0..N_VECTORS {
        if rng.below(100) < 15 {
            // uniform noise — the outliers no index should chase home
            vectors.push((0..DIM).map(|_| rng.uniform(-9.0, 9.0)).collect());
        } else {
            let c = &centers[rng.below(N_CLUSTERS)];
            vectors.push((0..DIM).map(|d| c[d] + rng.gauss() * 0.55).collect());
        }
    }
    let mut queries = Vec::with_capacity(N_QUERIES);
    for i in 0..N_QUERIES {
        if i < 40 {
            let c = &centers[i % N_CLUSTERS];
            queries.push((0..DIM).map(|d| c[d] + rng.gauss() * 0.30).collect());
        } else {
            queries.push((0..DIM).map(|_| rng.uniform(-9.0, 9.0)).collect());
        }
    }
    let truth = queries.iter().map(|q| brute_force(&vectors, q)).collect();
    Corpus { vectors, queries, truth }
}

/// Exact top-K by full scan — the ground truth every check grades against.
fn brute_force(vectors: &[Vec<f32>], query: &[f32]) -> Vec<u32> {
    let mut scored: Vec<(f32, u32)> = vectors
        .iter()
        .enumerate()
        .map(|(i, v)| (l2(query, v), i as u32))
        .collect();
    scored.sort_by(|a, b| a.partial_cmp(b).unwrap());
    scored.truncate(K);
    scored.into_iter().map(|(_, i)| i).collect()
}

/* ------------------------- pinned parameters ------------------------ */

const BUILD_M: usize = 16;
const BUILD_EFC: usize = 64;
const EF_SEARCH: usize = 48; // beam width for recall/latency/curve
const NAIVE_M: usize = 4;
const NAIVE_EFC: usize = 20;
const NAIVE_EF: usize = 200; // the superstition-tuned build's big beam
const INDEX_SEED: u64 = 0x5EED_1606;

/* --------------------------- CALIBRATION ----------------------------
 * Every band below is a measured number, not a hope. Reference solution
 * (labs/_solutions/hnsw), this corpus, these pins, native x86-64:
 *
 *   good build (m=16, efc=64) at ef=48:   recall@10 0.XXX, mean XXX.X dists/query
 *   naive build (m=4, efc=20) at ef=200:  recall@10 0.XXX, mean XXX.X dists/query
 *
 * RECALL_FLOOR  = reference recall minus ~6 points of headroom for
 *                 legitimate implementation variation; ceiling is 1.0.
 * LATENCY_MAX   = ~2.5x the reference's measured mean, and ~1/8 of the
 *                 4000-distance exact scan either way.
 * The curve check needs no constants: dominance is computed, not banded.
 */
const RECALL_FLOOR: f64 = 0.80; // PROVISIONAL — recalibrate
const LATENCY_MAX: f64 = 700.0; // PROVISIONAL — recalibrate

/* ---------------------------- build/measure ------------------------- */

fn setup(n: usize, m: usize, efc: usize) -> (Corpus, Hnsw) {
    let c = corpus();
    let mut h = Hnsw::new(m, efc, INDEX_SEED);
    for (i, v) in c.vectors.iter().take(n).enumerate() {
        h.insert(i as u32, v.clone());
    }
    (c, h)
}

/// Run the query suite: (mean recall@K, mean metered distances per query).
/// Err(msg) on a malformed result — the calling check fails with that msg.
fn measure(c: &Corpus, h: &Hnsw, ef: usize) -> Result<(f64, f64), String> {
    let mut recall_sum = 0.0f64;
    let mut dist_sum = 0u64;
    for (qi, q) in c.queries.iter().enumerate() {
        let mut meter = Meter::new();
        let res = h.search(&mut meter, q, K, ef);
        if res.len() != K {
            return Err(format!(
                "query {qi}: search returned {} results, want exactly {K} (ef_search = {ef}, graph holds {} nodes)",
                res.len(), h.len()));
        }
        for w in res.windows(2) {
            if w[0].1 > w[1].1 {
                return Err(format!(
                    "query {qi}: results not sorted by distance — {} before {}",
                    w[0].1, w[1].1));
            }
        }
        let mut ids: Vec<u32> = res.iter().map(|&(id, _)| id).collect();
        ids.sort_unstable();
        if ids.windows(2).any(|w| w[0] == w[1]) {
            return Err(format!("query {qi}: duplicate ids in the top-{K}"));
        }
        let hits = ids.iter().filter(|id| c.truth[qi].contains(id)).count();
        recall_sum += hits as f64 / K as f64;
        dist_sum += meter.count();
    }
    Ok((recall_sum / N_QUERIES as f64, dist_sum as f64 / N_QUERIES as f64))
}

/* ------------------------------ checks ------------------------------ */

/// 1. graph_invariants: after inserting 2000 vectors with pinned params —
/// every node reachable from the entry point at layer 0, degree caps
/// honored per layer, no self-edges, no duplicates, edges symmetric.
pub fn check_graph_invariants() -> Check {
    const ID: &str = "graph_invariants";
    const LABEL: &str = "layers bounded, every node reachable from the entry point";
    const N: usize = 2000;

    let fresh = Hnsw::new(BUILD_M, BUILD_EFC, INDEX_SEED);
    if fresh.len() != 0 || fresh.entry_point().is_some() {
        return Check::fail(ID, LABEL, "a fresh index must have len 0 and no entry point");
    }
    let (_, h) = setup(N, BUILD_M, BUILD_EFC);

    if h.len() != N {
        return Check::fail(ID, LABEL, format!("inserted {N} vectors, len() says {} — ids are dense: 0,1,2,… in insert order", h.len()));
    }
    let ep = match h.entry_point() {
        Some(ep) if (ep as usize) < N => ep,
        Some(ep) => return Check::fail(ID, LABEL, format!("entry_point() = {ep}, but only {N} nodes exist (ids 0..{N})")),
        None => return Check::fail(ID, LABEL, format!("entry_point() = None after {N} inserts — the first node crowns itself, and a new maximum level re-crowns")),
    };
    let mut max_layers = 0usize;
    for id in 0..N as u32 {
        let lv = h.layers_of(id);
        if lv == 0 {
            return Check::fail(ID, LABEL, format!("node {id}: layers_of() = 0 — every node spans at least layer 0"));
        }
        if lv > hnsw::MAX_LAYERS {
            return Check::fail(ID, LABEL, format!("node {id}: spans {lv} layers, over the MAX_LAYERS clamp of {} — geometric levels still need a ceiling", hnsw::MAX_LAYERS));
        }
        max_layers = max_layers.max(lv);
    }
    if h.layers_of(ep) != max_layers {
        return Check::fail(ID, LABEL, format!(
            "entry point {ep} spans {} layers, but some node spans {max_layers} — the entry point is always a node at the maximum level",
            h.layers_of(ep)));
    }

    // per-layer structure: caps, self-edges, duplicates, dangling ids, symmetry
    let cap = |l: usize| if l == 0 { 2 * BUILD_M } else { BUILD_M };
    for id in 0..N as u32 {
        for l in 0..h.layers_of(id) {
            let nb = h.neighbors(id, l);
            if nb.len() > cap(l) {
                return Check::fail(ID, LABEL, format!(
                    "node {id} layer {l}: {} neighbors, over the cap of {} (layer 0 allows 2*m, higher layers m)",
                    nb.len(), cap(l)));
            }
            let mut sorted = nb.clone();
            sorted.sort_unstable();
            for w in sorted.windows(2) {
                if w[0] == w[1] {
                    return Check::fail(ID, LABEL, format!("node {id} layer {l}: duplicate edge to node {}", w[0]));
                }
            }
            for &v in &nb {
                if v == id {
                    return Check::fail(ID, LABEL, format!("node {id} layer {l}: self-edge — a node is never its own neighbor"));
                }
                if (v as usize) >= N {
                    return Check::fail(ID, LABEL, format!("node {id} layer {l}: edge to node {v}, which does not exist (ids 0..{N})"));
                }
                if h.layers_of(v) <= l {
                    return Check::fail(ID, LABEL, format!(
                        "node {id} layer {l}: edge to node {v}, but node {v} only spans {} layer(s) — edges never dangle above a node's top",
                        h.layers_of(v)));
                }
                if !h.neighbors(v, l).contains(&id) {
                    return Check::fail(ID, LABEL, format!(
                        "asymmetry: node {id} lists node {v} at layer {l}, but {v} does not list {id} back — edges are symmetric; when you evict the farthest entry, remove the reverse edge too"));
                }
            }
        }
    }

    // reachability: BFS from the entry point at layer 0, pops capped at 10x
    let mut seen = vec![false; N];
    let mut queue = std::collections::VecDeque::from([ep]);
    seen[ep as usize] = true;
    let mut reached = 1usize;
    let mut pops = 0usize;
    while let Some(u) = queue.pop_front() {
        pops += 1;
        if pops > 10 * N {
            return Check::fail(ID, LABEL, format!("BFS walked past the safety cap of {} pops — your neighbor lists cycle or corrupt", 10 * N));
        }
        for &v in &h.neighbors(u, 0) {
            if !seen[v as usize] {
                seen[v as usize] = true;
                reached += 1;
                queue.push_back(v);
            }
        }
    }
    if reached != N {
        return Check::fail(ID, LABEL, format!(
            "only {reached} of {N} nodes reachable from entry point {ep} at layer 0 — the graph is fragmented; insert must connect every node to at least one existing node at layer 0"));
    }
    Check::pass(ID, LABEL, format!(
        "{N} nodes, {max_layers} layers deep, every node reachable from entry point {ep}, degrees within caps, edges symmetric"))
}

/// 2. recall_band: pinned build, pinned ef_search — mean recall@10 over the
///    50 seeded queries must land inside the calibrated band (see the
///    CALIBRATION block above: the floor is the reference build's measured
///    recall minus headroom, the ceiling 1.0).
pub fn check_recall_band() -> Check {
    const ID: &str = "recall_band";
    const LABEL: &str = "recall@10 within the calibrated band vs brute force";
    let (c, h) = setup(N_VECTORS, BUILD_M, BUILD_EFC);
    let (recall, _) = match measure(&c, &h, EF_SEARCH) {
        Ok(m) => m,
        Err(msg) => return Check::fail(ID, LABEL, msg),
    };
    if recall < RECALL_FLOOR {
        return Check::fail(ID, LABEL, format!(
            "mean recall@10 = {recall:.3} over {N_QUERIES} seeded queries — below the calibrated floor of {RECALL_FLOOR:.2}. Suspect the beam: layer-0 search must keep ef = max(ef_search, k) live candidates, and insert must connect the CLOSEST candidates, not just any m"));
    }
    Check::pass(ID, LABEL, format!(
        "mean recall@10 = {recall:.3} over {N_QUERIES} queries — inside the calibrated band [{RECALL_FLOOR:.2}, 1.00]"))
}

/// 3. latency_win: same pinned build and queries — the mean metered
///    distance count per query must beat the calibrated cap: a fraction of
///    the N_VECTORS-distance exact scan (see CALIBRATION).
pub fn check_latency_win() -> Check {
    const ID: &str = "latency_win";
    const LABEL: &str = "beats exact scan by the required margin";
    let (c, h) = setup(N_VECTORS, BUILD_M, BUILD_EFC);
    let (_, cost) = match measure(&c, &h, EF_SEARCH) {
        Ok(m) => m,
        Err(msg) => return Check::fail(ID, LABEL, msg),
    };
    if cost >= LATENCY_MAX {
        return Check::fail(ID, LABEL, format!(
            "mean {cost:.0} distance computations/query — the exact scan costs {N_VECTORS}, and the calibrated cap is {LATENCY_MAX:.0} ({:.0}% of scan). Your beam is wandering: check the greedy descent (beam 1 above layer 0) and that the layer-0 beam STOPS once its candidates are all farther than the ef-th best",
            100.0 * LATENCY_MAX / N_VECTORS as f64));
    }
    Check::pass(ID, LABEL, format!(
        "mean {cost:.0} distance computations/query = {:.1}% of the {N_VECTORS}-distance exact scan (cap {LATENCY_MAX:.0})",
        100.0 * cost / N_VECTORS as f64))
}

/// 4. planner_choice: choose_index over a scripted grid of scenarios. The
///    harness's own verdict is the one-line rule — index iff strictly
///    cheaper; a tie is a scan — and the student's choice must match it on
///    every cell.
pub fn check_planner_choice() -> Check {
    const ID: &str = "planner_choice";
    const LABEL: &str = "scan-vs-index chosen iff the index actually wins";
    // (scenario, n_rows, dim, k, est_index_cost, est_scan_cost)
    let grid: &[(&str, usize, usize, usize, f64, f64)] = &[
        ("tiny hot table (2k rows — the scan fits in cache)", 2_000, 32, 10, 96_000.0, 64_000.0),
        ("huge table (50M rows)", 50_000_000, 32, 10, 1.2e6, 1.6e9),
        ("high-dim flip (1536 dims — per-distance cost inflates the index estimate too)", 400_000, 1536, 10, 9.8e8, 6.1e8),
        ("an exact tie", 1_000_000, 64, 10, 3.2e6, 3.2e6),
        ("photo finish — the index cheaper by one unit", 1_000_000, 64, 10, 3.2e6 - 1.0, 3.2e6),
        ("big k (500 neighbors requested)", 8_000_000, 64, 500, 8.5e6, 5.1e8),
    ];
    for &(name, n, dim, k, ei, es) in grid {
        let want = ei < es; // the verdict: index iff STRICTLY cheaper; a tie goes to the scan
        let got = choose_index(n, dim, k, ei, es);
        if got != want {
            return Check::fail(ID, LABEL, format!(
                "{name}: n_rows={n}, dim={dim}, k={k}, est_index_cost={ei:.0}, est_scan_cost={es:.0} — you chose {}, the cost verdict is {} (index iff est_index_cost < est_scan_cost, strictly; a tie is a scan)",
                if got { "index" } else { "scan" },
                if want { "index" } else { "scan" }));
        }
    }
    Check::pass(ID, LABEL, format!("{} scenarios, every choice matches the cost verdict — the index is chosen iff it actually wins", grid.len()))
}

/// 5. curve: the capstone. Both indexes are built through the STUDENT's own
///    Hnsw on the same corpus and measured on the harness's meter against
///    brute-force truth: the pinned build (m=16, ef_construction=64) at
///    ef_search=48 must DOMINATE the naive build (m=4, ef_construction=20)
///    cranked to ef_search=200 — strictly better recall at equal-or-lower
///    cost, or strictly lower cost at equal-or-better recall. No bands:
///    dominance is computed from the two measured points.
pub fn check_curve() -> Check {
    const ID: &str = "curve";
    const LABEL: &str = "your (recall, latency) point dominates the naive build";
    let (c, good) = setup(N_VECTORS, BUILD_M, BUILD_EFC);
    let (r_good, c_good) = match measure(&c, &good, EF_SEARCH) {
        Ok(m) => m,
        Err(msg) => return Check::fail(ID, LABEL, msg),
    };
    let mut naive = Hnsw::new(NAIVE_M, NAIVE_EFC, INDEX_SEED);
    for (i, v) in c.vectors.iter().enumerate() {
        naive.insert(i as u32, v.clone());
    }
    let (r_naive, c_naive) = match measure(&c, &naive, NAIVE_EF) {
        Ok(m) => m,
        Err(msg) => return Check::fail(ID, LABEL, msg),
    };
    let dominates = (r_good > r_naive && c_good <= c_naive) || (c_good < c_naive && r_good >= r_naive);
    if !dominates {
        return Check::fail(ID, LABEL, format!(
            "your build (m={BUILD_M}, efc={BUILD_EFC}, ef={EF_SEARCH}): recall {r_good:.3} at {c_good:.0} dists/query; naive (m={NAIVE_M}, efc={NAIVE_EFC}, ef={NAIVE_EF}): recall {r_naive:.3} at {c_naive:.0}. You dominate neither axis — a well-built graph finds more truth with fewer distance evaluations; check neighbor selection (closest candidates) and the beam's stop rule"));
    }
    Check::pass(ID, LABEL, format!(
        "your build: recall {r_good:.3} at {c_good:.0} dists/query; naive: recall {r_naive:.3} at {c_naive:.0} — your point dominates. That IS the vector-database business case, measured"))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_graph_invariants(),
        check_recall_band(),
        check_latency_win(),
        check_planner_choice(),
        check_curve(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "hnsw", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
